### ISSUE TITLE
关于引擎对局的高级时间设置的问题

### ISSUE THREAD

**Issue by NotoOotori** [yzyray/lizzieyzy#1]
- 当前使用的 lizzieyzy 版本: 20210423-windows64
- 问题类型: bug 反馈

我在电脑上测试了几局 Genmove 模式的引擎对局, 采用的时长为 120  分钟 60 秒 5 次 (保留时间, 读秒时长, 读秒次数),
所对应的命令是 `kata-time_settings byoyomi 120 60 5`. 不过引擎在对局时始终保持 180 秒一步的行棋速度, 哪怕是每方总用时已经超过 4 小时 (远超 2 小时的保留用时) 的时候. 当我运行命令 `time_left b 0 5` 以及 `time_left w 0 5` 告知引擎剩余时间耗尽时, 引擎便终于按照 60 秒一步的速度行棋.
我确信这是因为界面没有通过 `time_left <main_time_left> <byoyomo_periods_left>` 命令告诉引擎剩余保留时间与读秒次数,
导致引擎一直以为自己有充足的保留时间来思考.

相关代码我猜测是在 src/main/java/featurecat/lizzie/analysis/EngineManager.java 中第 1446 行开始的这一组 "`if` ... `else` ..." 代码块中, 可能需要添加计时模块, 计算并通知引擎剩余时间.

**Comment by yzyray** [comment]
kata-time_settings byoyomi 这个命令我不是很清楚,好像是某个版本的katago引擎之后才有的 
不知道20210423的整合包里的引擎是否支持这个命令
我用最新的release(0702)里的主程序,高级时间设置中使用简单的命令:,黑:time_settings 0 5 1 白:time_settings 0 2 1
结果黑5秒一手,白2秒一手,看起来一切正常,你可以这样测试一下试试

**Comment by NotoOotori** [comment]
嗯，20210423整合包里的引擎已经支持 `kata-time_settings byoyomi` 了，通过在 GTP 命令行运行 `kata-list_time_settings` 可以看到已经支持 “byoyomi” 时间设置了。

`time_settings <main_time> <byoyomi_time> <byoyomi_stones>` 命令会告诉引擎保留时间为 `<main_time>` 分钟，读秒是需要在 `<byoyomi_time>` 中走 `<byoyomi_stones>` 步棋，所以 `time_settings 0 5 1` 会告诉引擎已经进入 5 秒钟 1 次的读秒，于是 5 秒 1 手是正常的现象。可以测试一下保留时间不为 0 的情况，比如说 `time_settings 1 15 1`，在我的电脑上观察到引擎会一直保持 16 秒的步时，哪怕 4 手之后它本应该耗尽保留时间进入读秒。

在这个[链接](https://www.gnu.org/software/gnugo/gnugo_19.html)中可以看到详细的关于 GTP 命令的介绍，其中说到

> time_settings: Set time allowance
> Arguments: int main_time, int byo_yomi_time, int byo_yomi_stones
> Fails:     syntax error
> Returns:   nothing
> 
> Status:    GTP version 2 standard command.
>
> time_left: Report remaining time
> Arguments: color color, int time, int stones
> Fails:     syntax error
> Returns:   nothing
> Status:    GTP version 2 standard command.

（这里的解释其实也蛮迷惑的，不过至少比[官方文档](http://www.lysator.liu.se/~gunnar/gtp/gtp2-spec-draft2/gtp2-spec.html#SECTION00073000000000000000)讲的详细多了……）我的理解是 `time_settings` 命令只用来告诉引擎限时，而还需要一直通过 `time_left` 命令告诉引擎剩余时间，否则的话引擎会一直认为保留时间未被消耗依旧为 `<main_time>`，于是就能观察到引擎始终保持固定步时的现象。

而目前界面在引擎对战初始化完成之后，只调用了 `play`，`kata-genmove_analysis` 和 `stop` 命令，从未调用过 `time_left` 命令，我想这应该是问题所在。

**Comment by yzyray** [comment]
我debug了一下katago的引擎,确实如此,不论genmove b多少次,剩余时间都没有变化
必须有time_left命令配合使用,需要在保留时间结束后发送time_left命令才行
这样看起来就比较麻烦了, 需要界面上解析高级时间设置里的命令并且计算剩余时间,没有时间之后发送time_left
这个byoyomo 120 60 5中的60 5应该是60秒内下5手吧,如果要完全支持还得把剩余时间和手数显示出来
看来比较麻烦...暂时不考虑支持这部分功能了,先在高级时间设置上加个tooltips 说明一下暂未实现发送time_left指令告知引擎剩余时间的部分,可能无法正确起效吧....

**Comment by NotoOotori** [comment]
> 这个byoyomo 120 60 5中的60 5应该是60秒内下5手吧

`byoyomi` 应该对应的是职业围棋大赛里的时间格式, `60 5` 代表每次读秒 60 秒, 在第 5 次读到 60 的时候判超时负, 参考[KataGo/GTP_Extensions.md](https://github.com/lightvector/KataGo/blob/master/docs/GTP_Extensions.md).

> `byoyomi` should be followed by `MAINTIME BYOYOMITIME BYOYOMIPERIODS` (float,float,int) specifying the main time, the length of each byo-yomi period, and the number of byo-yomi periods.

想要完全实现的话确实挺麻烦的... 非常感谢大大能帮忙看这个问题了! 祝好!

**Comment by yzyray** [comment]
我仔细查看了一下[KataGo/GTP_Extensions.md](https://github.com/lightvector/KataGo/blob/master/docs/GTP_Extensions.md)
kata-time_settings里的byoyomi确实是职业比赛的形式
简单的实现了一下kata-time_settings和标准gtp命令time_settings里的几种时间设置中需要发送time_left的部分,不知道是否正确
我把主程序上传在[这里](https://github.com/yzyray/lizzieyzy/releases/tag/2.4.2)

**Comment by NotoOotori** [comment]
非常抱歉, 是我疏忽了, `MAINTIME` 的单位确实应该是秒.

简单测试了一下, `time_settings` 命令对应的时间设置没发现问题, 但是 `kata-time_settings byoyomi` 似乎会出现无法进入读秒的问题. 举例来说:

- 时间设置为 0.1 秒 5 秒 1 次, `kata-time_settings byoyomi 0.10 5 1`.
- 下一步棋以及之后的棋白棋收到的命令均为 `time_left W 0.00 0`, **即一直未进入读秒**.

**Comment by yzyray** [comment]
嗯,有个bug..kata的都不行..我重新上传了
