### ISSUE TITLE
[Suggest] Dynamic button width for other languages

### ISSUE THREAD

**Issue by wonsiks** [yzyray/lizzieyzy#10]
I've tried to translate some button names into Korean but the width of each button was fixed so the changed name couldn't show properly.
Could you change the button width to dynamic in the next version?

Thanks

<img width="925" alt="20211105_174345" src="https://user-images.githubusercontent.com/37356450/140482856-c23192ea-7d96-472e-bc64-47f658ac4b69.png">
.

**Comment by yzyray** [comment]
Due to this is my first attempt to modify a program,some code are messy specially at beginning,some frame not using layout...
I will try to fix the bottom toolbar first.but there is still many position like the toolbar,may take a long time to fix them all.
