### ISSUE TITLE
Leela0110 also ponders the opponent's turn 

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#100]
I wanted to check the strength of Leela 0110's "500 visits / s". 
The settings are as shown in the screenshot below. 
![無題1](https://user-images.githubusercontent.com/63999713/149065961-c9c7fdf0-d999-4928-a387-9b8217dc5acb.png)
When I checked the situation during the game on the GTP console, I noticed that "500 visits / s" was not observed. 
When I checked the task manager, the CPU usage was always high. Leela0110 seems to be pondering even in the opponent's turn. 
![無題](https://user-images.githubusercontent.com/63999713/149066189-2ae67861-c3f7-4cb3-acc3-682675b8753c.png)

**Comment by yzyray** [comment]
I'm not sure if it is a bug in lizzie or just send name command too soon after analyze command and leads to leela engine ignore the name command(name command is used to stop ponder).
But this issue should be fixed now any why,cause I remove the useless analyze command after engine play a move.

**Comment by hope366** [comment]
That was good news. 😄
