### ISSUE TITLE
About engine management function 

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#101]
I'm not sure how to use or mean the red frame in the screenshot below.
Can you tell me how to use it? 
Thank you 
![無題](https://user-images.githubusercontent.com/63999713/149273781-d4fc6a28-6b10-4afa-b2a0-b3f8472214ee.png)

**Comment by yzyray** [comment]
The init cmds is initial commands,these commands should be splited by `;` and will be executed immediate after load the engine.
example:
![image](https://user-images.githubusercontent.com/49384584/150744123-64ccb01f-9936-4bde-92dd-58b4aec17671.png)
when loaded engine:
![image](https://user-images.githubusercontent.com/49384584/150744070-22689419-3239-4cb6-a27d-b2a3ccfdf132.png)
The remote line is set to link to a remote computer by ssh2 protocol,just like openssh or putty-plink.
The encryptCommand button can  encrypt  the command line for hiding some information like password(when using openssh or plink sometimes the command line will have those infos)

**Comment by yzyray** [comment]
For most linux based system,especially cloud server ssh server function will be pre-installed and enabled.So lizzieyzy could use these remote server directly without third-part software.

**Comment by hope366** [comment]
>So lizzieyzy could use these remote server directly without third-part software.

I have little knowledge of the cloud or remote.
I'm sorry for the unscrupulous request, but could you please tell me the specific usage of remote in Lizzieyzy?

**Comment by yzyray** [comment]
Given a example: rent a cloud server with gpus , you will recieve an static IP(maybe with a port or default 22) and root account/password so you can control the server with these infomations,usually I use open-ssh or putty to login the server.After I setup katago on the server I can no longer use open-ssh or putty, just put the IP account and password  into lizzieyzy remote line,and set engine command like I'm using native katago engine on the cloud server,it will works fine.

**Comment by hope366** [comment]
Thank you for your detailed explanation. I don't use it right away, but your commentary will be very helpful for anyone who wants to use a remote line in Japan.
