### ISSUE TITLE
About pop-up display 

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#102]
There seems to be an opinion that it is difficult to use because the pop-up display of the lower menu overlaps with the part clicked with the mouse when Lizzieyzy is displayed in full screen.
Also, the pop-up disappears in a few seconds, but I think it's useful to keep it visible forever unless you move the mouse, but what about? 
![無題](https://user-images.githubusercontent.com/63999713/149529706-d947997c-1c25-42ae-b95e-47af02296b59.png)

**Comment by yzyray** [comment]
`visible forever unless you move the mouse` 
this should be applied now.But I dont know how to change the position of tooltips...

**Comment by hope366** [comment]
Thank you for your support.
It's pretty handy just to see the tooltip forever. 😄
