### ISSUE TITLE
New introduction document(Chinese and English)

### ISSUE THREAD

**Issue by yzyray** [yzyray/lizzieyzy#103]
[readme_en.pdf](https://github.com/yzyray/lizzieyzy/files/7923763/readme_en.pdf)
[readme_en.docx](https://github.com/yzyray/lizzieyzy/files/7923764/readme_en.docx)
[readme_cn.pdf](https://github.com/yzyray/lizzieyzy/files/7923765/readme_cn.pdf)
[readme_cn.docx](https://github.com/yzyray/lizzieyzy/files/7923768/readme_cn.docx)
I have made a new version of introduction,sorry for the long delay due to the busy work before new year.@hope366

**Comment by yzyray** [comment]
I have added a language item `Menu.introduction.fileName` to assign the file name of introduction document.

**Comment by hope366** [comment]
Thank you for creating the file for the new manual.
Last time I created a Japanese version of the commentary file,
https://www.h-eba.com/Lizzie/LizzieYzy/manual.html
I feel that there is little need to create a new one, as this site has a fairly detailed explanation. It is already possible to open the site from the GUI of Lizzieyzy.

**Comment by yzyray** [comment]
Yes, the link is very detailed and convinence for update,seems no need to create another pdf for Japanese version.
