### ISSUE TITLE
About "Show score as difference" 

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#104]
In this way, if you hide the win rate and the number of visits, the normal score will be displayed on the board even if "Show score as difference" is checked. 
In other words, "Show score as difference" is only valid if the win rate, number of visits, score, all three are set to be displayed. 
"Number of visits and loss score" or "Loss score only". There seems to be an opinion that wants such a display. 
![無題](https://user-images.githubusercontent.com/63999713/150842353-f37bde61-eb7a-4d55-9895-67a3c852b8de.png)

**Comment by yzyray** [comment]
I forgot other situation...should be fixed now

**Comment by hope366** [comment]
Thank you for your support.

**Comment by hope366** [comment]
This screenshot is a compilation of the latest main branch. 
If I enable only two, score lead and score as difference, it seems that the score lead is displayed instead of score as difference.
For other patterns, score as difference seems to work well. 
![無題](https://user-images.githubusercontent.com/63999713/150952549-99816943-4f1d-4c3e-a2df-6bcde7c5d5f5.png)

**Comment by yzyray** [comment]
aha,still forget single score situation..

**Comment by hope366** [comment]
Thank you for your prompt response.
As you can see, it's working fine 😄 
![無題3](https://user-images.githubusercontent.com/63999713/150967962-558e014f-110a-45f4-970e-6bfedb39b08b.jpg)
