### ISSUE TITLE
About the scale of the score line 

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#105]
The score display on the winning percentage graph now appears to be set between -30 and 30. Is it possible to add the ability to adjust this scale? 
The winning percentage line fluctuates violently up and down, but the score line fluctuates only slightly near the center. There seems to be some dissatisfaction with this situation. 
There seems to be an opinion that the score scale should be -10 to 10 by default. What do you think?

**Comment by yzyray** [comment]
I have tried -10 to 10,in most situation score line will fluctuates as much as winrate line,but it maybe lead to overlap,so I set default value as -15 to 15 and add an option to change the value under view-winrate graphy settings.

**Comment by hope366** [comment]
Thank you so much.
Thank you for your positive efforts.
