### ISSUE TITLE
Functions when finishing distributed training 

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#108]
I recently learned from Discord chat that there is a "Ctrl-C" feature to exit when running distributed training from the command line. 
The first Ctrl-C will automatically end the distributed training as soon as the currently running game is over.(New games will not start) 
A second Ctrl-C will immediately end the distributed training. 

Is it possible to implement these features in Lizzieyzy?

**Comment by yzyray** [comment]
It is a little tricky to send Ctrl-C to engine,especially for java.
Currently,I implemented it through another program based on C#,so it will only works in winows system.

**Comment by hope366** [comment]
Thank you for your prompt support.
I made a pull request by translating it into Japanese together with the stone review. 

I tried using the stone review function. Clicking on a stone replays the bluespot change map from the analysis when the stone was placed. It seems that the value specified in the "View-> Autoplay" branch is applied to the playback speed. 
Are there any other features I'm missing?

**Comment by yzyray** [comment]
Yes,that is all the changes,I have merged your pr.@hope366

**Comment by hope366** [comment]
Thx a lot.
