### ISSUE TITLE
The display of the winning percentage graph panel is strange. 

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#112]
After compiling the latest main branch, it looks strange as shown in the screenshot below.
It is normal in English mode, but it seems to be strange in default mode (Japanese display).
How should I solve it? 
![無題](https://user-images.githubusercontent.com/63999713/151522797-2487c3ed-cedb-42ad-b92a-0d7ce3607a48.png)

**Comment by yzyray** [comment]
Maybe I messed up Japanese translation...

**Comment by hope366** [comment]
`LizzieFrame.display.lastMove=\u76EE \u6700\u7d42\u624b\`
Upon careful observation, it seems that the last `\` was superfluous. After deleting it, the display became normal. If there is a `\` at the end, is it considered to be continuous with the next line? 
I created a PR.

**Comment by yzyray** [comment]
Yes the `\` is the reason,in previous commits,I modified the `last move` part to insert a order if last move matched a top 9 candidate like `Lastmove(#3): ` means the last move was placed right on the NO.3 candidate. Then I have to remove `:` in the tag `LizzieFrame.display.lastMove` and  move it after (#3)  and I forget to remove the last `\`.

**Comment by hope366** [comment]
There was a change in the Japanese file `LizzieFrame.display.lastMove` in your new commit, so it seems that I guessed that there was a hint to solve it. 
By the way, the new feature `show lastmove match candidate order` is pretty good. 
![無題](https://user-images.githubusercontent.com/63999713/151566534-a32c0d9c-36c9-4de8-a10a-b81adfb1ef71.png)
