### ISSUE TITLE
Bug with jdk 17.0.1 

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#114]
Help → Introduction did not work on jdk 17.0.1 (Windows 10) 
The computer seems to be doing something for a moment, but nothing happens after that. Also, the window is displayed but remains blank and nothing is displayed. I don't know what caused these differences. 
After changing to jdk14.0.2, it was displayed normally.

**Comment by yzyray** [comment]
Currently using an old version of jxbrowser for yike live which does not support jdk17,It is replaced by JCEF now,should be fine.

**Comment by hope366** [comment]
For the latest main branch, "Help-> Introduction" worked under the environment of jdk-17.0.2 😄
Thank you.
There seem to be some recent changes, but I'm interested in the following two items. 
* [add noRatingMatches option](https://github.com/yzyray/lizzieyzy/commit/95f0dc57a6205524e913ed495e4a1b9ee0a9167c)
* [Fix about contribute game after pass](https://github.com/yzyray/lizzieyzy/commit/1c29fd7141f5bce205e53d31975e33769c492104)
Is the first option to exclude rating games when making contributions?
The second seems to be a fix after the path, but what exactly is it? After the pass, it seems that it takes a long time to finish the game. Is this improved?

**Comment by yzyray** [comment]
>Is the first option to exclude rating games when making contributions?

Yes.
>The second seems to be a fix after the path, but what exactly is it? After the pass, it seems that it takes a long time to finish the >game. Is this improved?

I used to consider it is normal to take long time to finish the game,but recently I found it was a bug that move all the moves  after first pass doest not displayed any more.Usually, there are many moves after the first pass.

**Comment by hope366** [comment]
Even with the latest main branch, there are no new moves after the pass and it seems to be waiting for a while.
Where can I see the difference from the previous version?

**Comment by yzyray** [comment]
Can you check on offcial website:https://katagotraining.org/contributions/yzyray/training-games/
See if the game really no new moves after the pass,or just lizzieyzy can not displayed.

**Comment by hope366** [comment]
https://katagotraining.org/sgfplayer/training-games/28762801/
I confirmed here. The game has a total of 3 passes, but lizzieyzy and the above site were a perfect match. I was able to confirm the movement after the pass in lizzieyzy as well.
After the last pass, I waited about 4 minutes for the contribution to shut down, is this normal behavior?

**Comment by yzyray** [comment]
>After the last pass, I waited about 4 minutes for the contribution to shut down, is this normal behavior?

I think it is probably normal,but depends on your hardware,in my environment(GPU RTX2080) it is only few seconds.

**Comment by hope366** [comment]
My PC is RTX2060. It's slower than the RTX2080, but should have more than 50% performance of the 2080.
There is a big difference between a few seconds and 4 minutes (number of simultaneous games = 1), but we haven't done much verification yet. I would like to verify it several times and see how it looks.

**Comment by hope366** [comment]
I ran distributed training with a compilation of the latest main branch about an hour ago. 
Lizzieyzy ends with a 330 move, but the saved game on the KataGo site has a final move of 351. 
https://katagotraining.org/sgfplayer/training-games/28811020/
The game took about three and a half minutes to shut down after the last 330th move (pass), but it is estimated that the 331-351 moves were being processed internally. 
![無題](https://user-images.githubusercontent.com/63999713/152759952-def296ab-cbe2-4e48-afc9-3ef4e78c4cb2.png)

**Comment by yzyray** [comment]
I have done several tests,and eventually was able to confirm,there is some games without any output infomations during last several moves in ending stages,maybe usually after double passes.
There is no ouput infos after move 313 Black at H6,https://katagotraining.org/sgfplayer/training-games/28857089/ 
So I think even without any bugs,we will still see some game hangs for minutes before finished.

**Comment by hope366** [comment]
Thank you for verifying. 
It's not very pleasant to look like it's hung, but I'll keep it in mind as a KataGo spec.
