### ISSUE TITLE
About "useGraphSearch" 

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#115]
At the end of the KataGo configuration file, you will find the following items.
`useGraphSearch = true `
All of the KataGo engines included with Lizzieyzy have been changed to the new version. Is it the latest KataGo with `useGraphSearch` implemented? 
Is this parameter related to KataGo's internal behavior? Or is it something that the user can visually recognize?

**Comment by yzyray** [comment]
It is a parameter to enable `GraphSearch` in katago engine,graph search is newly implemented by lightvector,to replace tree search.In my understanding,graph search can avoid repeated search,If a board position is searched under one variation and  it is not good enough then it will not be searched too much again under another variation.

**Comment by hope366** [comment]
thank you for teaching me.
So it's an internal behavior, not something that the user can see visually. It seems interesting to think about how this feature changes the strength of KataGo.

**Comment by yzyray** [comment]
Yes,it can not be easily seen.
IIRC,some tests result have been put on discord,but I can't remember how much elo the graph search gained and katago engine with graph search is not officially released,I think  it will be introduced by then.
