### ISSUE TITLE
人机对局，能设置难度吗？

### ISSUE THREAD

**Issue by 1067511899** [yzyray/lizzieyzy#118]
ktrain是可以设置难度的，虽然原理不清楚。

请问能在人机对局当中，增加难度设置吗？也就是段位设置。

主要是实在不喜欢让子棋。

谢谢。

**Comment by yzyray** [comment]
katrain有自己的bot设置,不属于katago引擎内的.
Lizzieyzy主要还是针对分析,对局功能只是附带的,不会在人机对局中增加段位之类的设置了.

**Comment by 1067511899** [comment]
哦，收到。谢谢您的答复。
