### ISSUE TITLE
File config.txt scratch using jar file on Mac

### ISSUE THREAD

**Issue by joancorbella** [yzyray/lizzieyzy#119]
Hi, I have a Mac user (iMac M1). I'm using LizzieYzy jar application. When I open application calling jar file, the config.txt file is reinitiate and I lose all engine settings.

Thanks

**Comment by yzyray** [comment]
Maybe the lizzie jar is lanched without the privilege of modify config.txt.
How do you lanch the jar application,just click and open or from command like `java -jar lizzieyzy-2.4.7-shaded.jar`,and can you try to check this option in menu `settings-config` like:
![image](https://user-images.githubusercontent.com/49384584/153520871-9df4b9cc-90f2-413b-ab2c-61389ae13064.png)
and see if these files will be produced along with jar file
![image](https://user-images.githubusercontent.com/49384584/153520931-79f9ac3e-9b55-4faa-9f0d-b52cb10e6fa6.png)

I'm not familiar with MAC,maybe need more infos and help from other MAC users.

**Comment by joancorbella** [comment]
Hi, It's solved after I have executed the command java -jar
lizzie-yzy2.4.7-shaded-mac.jar and not double click on the jar file.

Thanks so much.

Missatge de yzyray ***@***.***> del dia dv., 11 de febr. 2022
a les 1:49:

**Comment by yzyray** [comment]
It is still strange,why double click open will caouse the issue.
If it is not too troublesome,can you try to check the log option in previous mentioned and open with double click,see if some log infos will be generated.

**Comment by joancorbella** [comment]
Hi,

Now is working, probably was problem about path. 
Thanks a lot.
