### ISSUE TITLE
Flash analyze issues 

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#12]
If you save the flash-analyzed game record and reload it, it will not be displayed properly. 
The SGF data saved by performing flash analysis is shown below. I will do only the beginning part. 

>(;FF[4]TT[15]KM[6.5]RU[Japanese]GM[1]SZ[19]GN[]PW[我想静静了]AP[Lizzie: yzy2.4.5]TC[3]DT[2021-11-06]BR[10段]PB[潜伏]RE[B+1.50]DZ[G]HA[0]TM[60]RL[0]WR[9段]CA[UTF-8]C[Engine Rules: Japanese];B[pd]C[Black win rate: 48.4% (-1.6%)
lead: -0.2  stdev: 16.9
(FlashAnalyze / 53 visits)
komi: 6.5]LZ[Flash Analyze 48.4 53 0.2 16.9
move D4 visits 14 winrate 5160 prior 5171 scoreMean 0.17 pv D4 D16 Q4 R6 info move D16 visits 5 winrate 5160 prior 1821 scoreMean 0.19 pv D16 D4 Q4 C14 info move Q4 visits 5 winrate 5160 prior 1821 scoreMean 0.19 pv Q4 D4 D16 O3 info move C4 visits 5 winrate 5039 prior 184 scoreMean 0.08 pv C4 Q4 D17 info move D3 visits 5 winrate 5039 prior 184 scoreMean 0.08 pv D3 D16 R4 info move C16 visits 4 winrate 4997 prior 134 scoreMean 0.06 pv C16 Q4 D3 info move Q3 visits 4 winrate 4997 prior 134 scoreMean 0.06 pv Q3 D16 C4 info move C3 visits 3 winrate 4961 prior 126 scoreMean -0.10 pv C3 Q3 info move D17 visits 2 winrate 4965 prior 123 scoreMean -0.01 pv D17 D4 info move R4 visits 2 winrate 4965 prior 123 scoreMean -0.01 pv R4 D4 info move C17 visits 2 winrate 5023 prior 122 scoreMean 0.00 pv C17 Q3 info move R3 visits 2 winrate 5023 prior 122 scoreMean 0.00 pv R3 C16];W[dp]C[White win rate: 51.9% (+0.3%)
lead: 0.2 (+0.0) stdev: 16.8

Loading the above SGF will result in an incorrect display. And I saved this malformed state. The saved SGF is shown below.This is all the information contained in the SGF, not just a portion. 

>(;DT[2021-11-06]KM[6.5]PB[]RE[]DZ[G]PW[]SZ[19]CA[UTF-8]AP[Lizzie: yzy2.4.5]C[Engine Rules: Japanese];B[pd]C[Black win rate: 48.4% (-1.6%)
lead: -0.2  stdev: 16.9
(FlashAnalyze / 53 visits)
komi: 6.5])

**Comment by yzyray** [comment]
I've catched the reason,'flash analyze' in english language has a blank in it,lead to some error in parsing sgf.Will be fixed in next release.

**Comment by hope366** [comment]
Thank you.
