### ISSUE TITLE
Some opinions and requests 

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#121]
I would like to inform you that there are opinions and requests around me regarding some features. 

1. In the small window that appears in Game → Final score, there are "Area scoring" and "Territory scoring", but there is an opinion that this should be reversed. It is an opinion that it is not good for Area scoring to be performed with "Territory scoring" displayed. 
2. When calculating the handicap game with Area scoring of Chinese rule and Area scoring of Japanese rule, the result is different. 
3. In a game between engines, if you try to start just by specifying the engine, an error will occur. 
4. When you load the game record (Komi = 0.5) of the handicap game, the GUI Komi automatically becomes 0.5, but when you switch the engine, it becomes the Komi set for that engine. 
5. Currently, if you try to delete the middle part of the game record, all the parts after that will be deleted, but some people are requesting a function to delete only a part. 

Regarding 1., it is possible to deal with it by reversing the Japanese translation, but I do not want to do much to ignore the original display. 
Regarding 2., it can be said that it is a natural result because there is no concept of a white handicap bonus in the Japanese rule, but there are people who are wondering that the calculation result is significantly different between the Japanese rule and the Chinese rule. 
Regarding 3., it seems that beginners will not be confused if numerical values such as consideration time and maximum number of analyzes are specified by default, such as automatic analysis and flash analysis. 
Regarding 4., it is an opinion that komi should not be changed when the engine is switched while the game record is loaded. In normal Lizzie, this problem doesn't seem to occur because komi is not set in the engine. 
Regarding 5., there are people who want to know how the engine evaluates a game record if there is no part of the game record. 

In my opinion, for 1 to 4, if you remember the GUI specifications, you shouldn't have much trouble with the current status.
Regarding 5., I have never felt that such a function is necessary, but it may be useful if it has such a function because it enables a wide range of analysis.

**Comment by hebaeba** [comment]
Here's my take on the above suggestion.
1. I think it would be easier to understand if the final score is calculated by the rules set at the time.
4. If the engine is changed, the komi becomes the default value, but since the engine is often changed during the analysis stage, it would be better if the user can choose whether to change the komi or not.

**Comment by yzyray** [comment]
For 1 added a label to show current rule,it might be much clearer
![image](https://user-images.githubusercontent.com/49384584/154635097-e87d3db1-a49e-48d2-9655-35fe8746461e.png)

For 2 In my opinion,It is all right to get different results between different rules,even in normal games not handicap.

For 3 added default contiditon: 2 seconds per move

For 4 Some engine only works with certian komi like leela zero or Chinese rules katago dont work with komi 6.5,and change engine during one game may not be very frequent,so I think it is better to load new engine's default komi when engine changed.

For 5 you can delete some stones by right click.

**Comment by hope366** [comment]
Thank you for your prompt response. 
Thank you for making the score result display easier to understand. I don't think you'll be confused by this. Please check the PR for translation. 
I verified it on the latest main branch, but for games between engines, the consideration time is not set to "2 seconds" by default, and all three items are blank ... 
I forgot the ability to right-click to remove stones. If you use this function, it will be effective for captured stone at the same time as removing stones, so I think that those who requested this function will be satisfied.

**Comment by yzyray** [comment]
>I verified it on the latest main branch, but for games between engines, the consideration time is not set to "2 seconds" by default, and all three items are blank ...

These settings will be remembered,so you must delete two files first `config.txt` and `persist` or copy jar/exe to a new folder.
