### ISSUE TITLE
在非1080P分辨率下打开任何小窗口都会出现字体以及背景重叠

### ISSUE THREAD

**Issue by kevinyyh** [yzyray/lizzieyzy#122]
我是2K分辨率，打开设置，引擎规则，当鼠标移到小窗内时，字体完全重叠，1080P下没有问题

**Comment by kevinyyh** [comment]
![WeChat Screenshot_20220217095736](https://user-images.githubusercontent.com/29715069/154519862-4bf08daa-4977-4670-9677-04979e058ec3.png)

**Comment by yzyray** [comment]
很奇怪的问题,之前也有人反馈过说是和刷新率有关系....
你的显示器的刷新率是多少,还有显示缩放是多少的?
可以试试这个测试版的主程序正常么,https://aistudio.baidu.com/aistudio/datasetdetail/120771

**Comment by kevinyyh** [comment]
> 很奇怪的问题,之前也有人反馈过说是和刷新率有关系.... 你的显示器的刷新率是多少,还有显示缩放是多少的? 可以试试这个测试版的主程序正常么,https://aistudio.baidu.com/aistudio/datasetdetail/120771

2k144hz,之前有个1080p60hz的显示器没问题，缩放是125%

**Comment by yzyray** [comment]
![image](https://user-images.githubusercontent.com/49384584/154638746-d3098993-0659-47b9-a52c-fa1596442a57.png)
我又上传了一个主程序,如果有空的话两个都帮忙测试一下吧

**Comment by forjoke2013** [comment]
自定义theme切换其他模式经常会重叠
![2022-03-11_235637](https://user-images.githubusercontent.com/94590005/157902876-3c127e98-233d-4972-a1e1-0b8bec6c9920.jpg)

**Comment by nicewk** [comment]
出现同样问题，1080 100%比率屏幕 144频率。

**Comment by yzyray** [comment]
最新的整合包加了一个"Lizzieyzy64(仅在显示异常时尝试)"的主程序,是否可以解决问题

**Comment by nicewk** [comment]
Hi，
是的，新加的包可以正常显示。谢谢！

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
