### ISSUE TITLE
公开棋谱查询失败

### ISSUE THREAD

**Issue by lizhihome** [yzyray/lizzieyzy#125]
连接失败...请重试或下载最新版LizzieYzy,链接: https://aistudio.baidu.com/aistudio/datasetdetail/116865

不知道是什么问题

**Comment by yzyray** [comment]
网络问题吧 目前应该是好的

**Comment by forjoke2013** [comment]
我也出现获取棋谱失败，connection timed out，和野狐同步可以用的

**Comment by lizhihome** [comment]
我发现这个是一些 VPN 阻止了网页访问。
