### ISSUE TITLE
About "add review to right click menu" 

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#126]
Please tell us about the latest commit, `add review to right click menu`. 
"Review" is not displayed even if you right-click on the candidate move.
Right-clicking on the stone, there was "Review" in the menu. 
However, when I clicked "Review", nothing happened.
How do you use this new feature?

**Comment by yzyray** [comment]
It is same as click on exsited stones,if there was candidates at that move,it's variation will be displayed.

**Comment by hope366** [comment]
"Edit → Enable click stone review" was not enabled 😅
If this wasn't enabled, right-click review wouldn't work either.
