### ISSUE TITLE
"Analyze all branches" not found 

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#129]
I compiled the latest main branch, but couldn't find `Analyze all branches`.
Where does this appear? 
There is a `Analyze all branch` in the auto analyze dialog window, but the` Analyze all branches` is a new addition, isn't it?

**Comment by yzyray** [comment]
Its in the flash analyze menu:
![image](https://user-images.githubusercontent.com/49384584/155977858-b5f9ceaa-63ab-4c10-91a3-0d78a65ee3f3.png)

**Comment by hope366** [comment]
I think you're presenting `Menu.flashAnalyzeAllBranches = Flash analyze (All branches)`. This is in the flash analysis icon and in the analysis in the top menu. This is easy to find.
In addition to this, `StartAnaDialog.chkAllBranches = Analyze all branches` has been newly added to DisplayStrings.properties. I can't find this on the GUI.

**Comment by hope366** [comment]
It seems that my observing power was lacking.
What I was looking for was Analyze → Batch analyze (Flash), which was in the window that appeared after I specified the game record. 
![無題](https://user-images.githubusercontent.com/63999713/155985616-a853e5f0-c0cd-4e81-bd08-106152e57e3e.png)

**Comment by yzyray** [comment]
Yes,it is there.

**Comment by hope366** [comment]
I'm sorry for making a noise.
