### ISSUE TITLE
About Hawk Eye 

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#13]
When I run move-1 (Black) on the main board, HawkEye looks like the data is being added to the white side. Since then, it looks like black and white are reversed. Is this something I'm misunderstanding? 
![無題](https://user-images.githubusercontent.com/63999713/140592336-34d845ae-a9a6-4846-8dcf-d2c686e79118.png)

**Comment by yzyray** [comment]
Seems calculate move number wrong,and consider move 2 as move 1,I will fix it in next releaase.

**Comment by hope366** [comment]
Thank you.
