### ISSUE TITLE
解死活題：動態擴增計算區域

### ISSUE THREAD

**Issue by dinohsu1019** [yzyray/lizzieyzy#132]
以這一題(死亡線追殺)為例：
https://www.101weiqi.com/chessbook/notation/36145/

如果我們設定計算區域為黃色方框的話：
![image](https://user-images.githubusercontent.com/30600848/156854301-1ab50ac8-766d-422a-b6b3-b7c4d27ae027.png)

黑9已經跑出計算區域的範圍：
![image](https://user-images.githubusercontent.com/30600848/156854502-0bcdc373-97db-4126-b392-e868fd0dcbe5.png)

所以隨著棋盤上的棋子增加，應該動態增計算區域，即紅色的部分：
![image](https://user-images.githubusercontent.com/30600848/156854691-ac324cc7-4283-4b53-93dc-f805497d7c0a.png)

注意：原題左上角有白棋二子的「接應」，但不論「有接應」或「無接應」的題目，如果有這樣「動熊擴增計算範圍」，似乎都可以解決。以這題為例，似乎只要能擴增已落棋子的垂直、水平各二格就行了。

感謝先。

**Comment by yzyray** [comment]
计算区域功能设计出来主要是复盘的时候可以屏蔽一些AI总想去下的无意义先手交换,以及让AI先计算一个某个局部的招法用的.
这个功能其实并不适合解死活提,解死活题合适的方法是制造一个必须杀死这个局部的局面,如果打劫还需要外部有劫财.
暂时没有打算专门做解死活题的功能(很可能以后也不会,因为从我自己使用的角度出发觉得没什么必要死活就是锻炼计算自己算就好了),如果一定需要AI来解题,推荐使用lizgoban解死活题的功能,详见:
https://github.com/kaorahi/lizgoban/issues/68

**Comment by dinohsu1019** [comment]
感謝回答，打劫確實是個問題，但看來圍棋AI還在不斷地發展出新的功能。

**Comment by wsjgyjgy** [comment]
能否设置劫财数量。因为如果死活题本身有劫财的话，可能不会算出正解打劫
