### ISSUE TITLE
您好，我想问一下超级鹰眼的问题

### ISSUE THREAD

**Issue by 1067511899** [yzyray/lizzieyzy#133]
![image](https://user-images.githubusercontent.com/21253207/157645401-6c3b858a-be71-4f39-9614-f8baac0b9a01.png)
这是我拿超级鹰眼分析的一个图，请问吻合度和吻合率是什么意思？它们之间的区别是什么？
谢谢。

**Comment by yzyray** [comment]
吻合度基于实际落子点的计算量与计算量最高的选点的比值,每一手都是这样计算得到一个0-1.0的数值,然后把每一手的这个数值加起来除以手数*100%
吻合率的条件在页面底部
![image](https://user-images.githubusercontent.com/49384584/157786550-814bec5a-ab8b-4f5c-b3ff-0c6cb2852418.png)

**Comment by 1067511899** [comment]
谢谢您的回答。
