### ISSUE TITLE
希望在思考模式下信息面板能显示不确定度

### ISSUE THREAD

**Issue by forjoke2013** [yzyray/lizzieyzy#135]
另：自定义工具栏能一次性取消，如“可视化面板设置" 那样。现在要进去一次点一个勾

**Comment by yzyray** [comment]
自定义工具栏应该不会经常去改动吧,虽然目前是有点繁琐不过改一次就好了.暂时不打算增加这个功能了.
![image](https://user-images.githubusercontent.com/49384584/158091701-499fcd44-3034-40af-91cb-f90574ce621f.png)
 思考模式的不确定度显示在这里了
