### ISSUE TITLE
Please tell me the meaning of "CA" 

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#136]
`allow remote ssh engine contributing, prepare for next release`
In the process of Japaneseizing this commit, I found the following line missing in DisplayStrings_ja_JP.properties.
`Contribute.tips.no CAcerts = Could not find CA certs.` 
I think "certs" is "certificate". What is "CA"?

**Comment by yzyray** [comment]
I just use the error output katago gives,if `cacert.pem` is not in the same folder with katago engine:
>Uncaught exception: Could not find CA certs (cacert.pem or ca-bundle.crt) at default location (dir containing katago.exe) or >other default locations, please specify where this file is via '-cacerts' command  line argument and/or download them from >https://curl.haxx.se/docs/caextract.html

But I think it is: https://en.wikipedia.org/wiki/CAcert.org

**Comment by hope366** [comment]
Thank you for letting me know.
I made a PR for Japanese, but I'm not familiar with the GitHub system yet, and the previous "add tool tip for accuracy and match" stuck to it ... 
I made hope366 / lizzieyzy on GitHub the same as the main branch of yzyray / lizzieyzy and then pulled it to the local folder, so I knew that "add tool tip for accuracy and match" was reflected in the local folder. However, it seems that it was not actually the case.
The next time I make a pull request, I'll do my best to make it work.

**Comment by yzyray** [comment]
Oh,I've not noticed it.Feel free to make any pull request.

**Comment by hope366** [comment]
Thank you.
I can only make pull requests for Japanese localization, but I would like to check quickly when there is a new commit and make frequent pull requests.

**Comment by yzyray** [comment]
I've merged it,Thanks for continuously translation.
