### ISSUE TITLE
遠程引擎無法使用~/.ssh/id_ed25519密鑰自動登入

### ISSUE THREAD

**Issue by jim9292bb** [yzyray/lizzieyzy#139]
如果在設置引擎中的命令行寫 ssh -p <端口> <用戶名>@<ip> <運行katago的指令>可以正常啟動katago，但如果勾選遠程引擎，密鑰選擇~/.ssh/id_ed25519，它就會報錯: "Publickey authentication failed."

**Comment by yzyray** [comment]
我尝试过RSA的密钥是可以的 不知道你的密钥类型是什么呢

**Comment by jim9292bb** [comment]
是 ed25519

**Comment by yzyray** [comment]
这种加密类型估计还支持不了...就通过命令行写ssh调用openssh登录吧...

**Comment by jim9292bb** [comment]
ok，感謝！
