### ISSUE TITLE
Please tell me about the edit button in the lower right corner 

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#142]
Please tell us about the new features added from 2.4.8.
I heard that you added an edit button at the bottom right of the board when you used the sync function. Can you tell me how to use it?
The screenshot below is shown from 2.4.7, is it different? 
![無題](https://user-images.githubusercontent.com/63999713/160567179-7cfa5fe6-d149-4f01-bf79-3624a1a5ed1d.png)

**Comment by yzyray** [comment]
![image](https://user-images.githubusercontent.com/49384584/160736946-c5681888-2b8f-4ca2-a91b-26192a4adf60.png)
It only appears if `BothSync` is unchecked.

**Comment by hope366** [comment]
Thank you for teaching me.
I was able to confirm the editing function in my environment as well. 😄
