### ISSUE TITLE
GPU clock count seems to drop 

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#143]
I tried the newly released 2.4.8, but it seems that the number of GPU clocks drops within a few seconds to a few seconds after booting.
It's the same as when I told you before.
TensorRT
Tensor RT-PDA
OpenCL
I tried these three versions, but the number of GPU clocks dropped from 1800MHz to 1200MHz in about 10 seconds after booting.
2.4.7 does not have this phenomenon.

**Comment by yzyray** [comment]
Maybe it is due to I added a opengl param,I have removed it,can you pull the newest code and try again?

**Comment by hope366** [comment]
I pulled in the latest main branch and verified it.
It looks good 😄 
Thanks a lot!

**Comment by yzyray** [comment]
Thanks for report.I’ve forgot remove these
 test codes.
