### ISSUE TITLE
Initial load failure (Lizzieyzy-2.4.8 pre1)

### ISSUE THREAD

**Issue by robinhold** [yzyray/lizzieyzy#144]
Can't open the program on initial load.
![1](https://user-images.githubusercontent.com/54459327/160737466-7a6788e8-e393-4d44-af24-209c35a4f5d7.jpg)

**Comment by yzyray** [comment]
How about use the opencl version katago engine.

**Comment by robinhold** [comment]
Running on Lizzieyzy-2.4.8-win64.exe fails, but lizzie-yzy2.4.8-shaded.jar succeed.

**Comment by robinhold** [comment]
fixed in version 2.5.0
