### ISSUE TITLE
在 http://lizzieyzy.cn/ 棋谱中显示批注

### ISSUE THREAD

**Issue by lizhihome** [yzyray/lizzieyzy#149]
随着上传棋谱越来越多，http://lizzieyzy.cn/ 是非常好的棋谱显示和学习地方，最好能够在右下方显示批注，而不是winrate，英文winrate在棋盘中已经显示了。
另外，最好能够有分支显示。

**Comment by yzyray** [comment]
暂时不考虑改这块了,服务器也快过期了...
