### ISSUE TITLE
"Black lead" above graph always includes komi, regardless of the setting

### ISSUE THREAD

**Issue by croosn** [yzyray/lizzieyzy#15]
![github issue 1](https://user-images.githubusercontent.com/38720539/140820639-7ee32d9e-24f6-4abd-bb59-b4b0ce38a8de.PNG)

**Comment by yzyray** [comment]
It is by design,The 'Black lead' acturely means raw lead without consider komi,in chinese it is a term '盘面',but I dont know how to translate in english propearly.

**Comment by yzyray** [comment]
How about call it 'Raw lead' does it properly?

**Comment by croosn** [comment]
I am not a native english speaker myself, but as far as I know, there is no english word for that.
Lead with komi => Lead
Lead without komi => Lead without komi

**Comment by yzyray** [comment]
I translate both situation to Lead....and follow with/without komi settings.
