### ISSUE TITLE
分支播放

### ISSUE THREAD

**Issue by lizhihome** [yzyray/lizzieyzy#153]
现在分支播放很不方便，显示的也不好。
能不能一个选择，显示推荐的，还是分支的，鼠标悬停等一致。

![image](https://user-images.githubusercontent.com/30011921/166157204-2899c8e8-c3d7-4b2f-a3b5-4660efeb585f.png)

**Comment by yzyray** [comment]
没看懂你的问题...

**Comment by lizhihome** [comment]
就是分支可以和推荐一样播放吗？现在分支要用左右键跳来跳去，不方便。分支多了很难控制看哪个等。

**Comment by yzyray** [comment]
没法播放,自动播放只会播放主分支
