### ISSUE TITLE
當自動分析 搭配 kataogo評估 以方塊大小表示占有率 會出現以下bug 每一步都會出現一次

### ISSUE THREAD

**Issue by some2112** [yzyray/lizzieyzy#155]
![image](https://user-images.githubusercontent.com/105207554/167611656-9e885e36-ab34-436a-ad7a-b629537c2e28.png)

**Comment by yzyray** [comment]
是格子变灰色了么 不自动分析就是黑色吗

**Comment by kaorahi** [comment]
my case: kaorahi/lizzie@2ce1d7f4
