### ISSUE TITLE
Increase board lines thickness

### ISSUE THREAD

**Issue by croosn** [yzyray/lizzieyzy#156]
Is there an option to increase board lines thickness?

**Comment by yzyray** [comment]
Current too thin?
what's your screen resolution,and can you give a screenshot

**Comment by yzyray** [comment]
The board lines thickness is calculated by boardsize,currently seems too thin for a large board,I'll make it a little wider.

**Comment by croosn** [comment]
Thank you!

**Comment by heslazarm** [comment]
The new release has fixed this issue.

**Comment by croosn** [comment]
The new release has fixed this issue.
