### ISSUE TITLE
絕藝：三個小棋盤

### ISSUE THREAD

**Issue by dinohsu1019** [yzyray/lizzieyzy#157]
最近發現絕藝覆盤的界面是顯示(最多)三個小棋盤，分別是第一(右上)、第二(右下)、第三(左上)選點，中間大棋盤則顯示實戰選點，不知這樣的設計是否更為實用？這只是討論，不是功能需求。感謝先。

**Comment by yzyray** [comment]
绝艺是为了展示变化图吧,Lizzie的鼠标放在选点上能显示变化图,应该不需要搞那么多棋盘...

**Comment by dinohsu1019** [comment]
> 绝艺是为了展示变化图吧,Lizzie的鼠标放在选点上能显示变化图,应该不需要搞那么多棋盘...

你太客氣了，我發現「四方圖模式」可以顯示前四個選點的變化圖在四個小棋盤上面，太牛了。

**Comment by yzyray** [comment]
嗯 四方图模式确实有点像,不过我自己是看不过来这么多图...都忘记这个模式了..哈哈
