### ISSUE TITLE
你好，请问死活对局引擎，能上传到github吗，没找到

### ISSUE THREAD

**Issue by awsjgyjgy** [yzyray/lizzieyzy#158]

**Comment by yzyray** [comment]
什么死活对局引擎?

**Comment by awsjgyjgy** [comment]
黑摆任意子，杀光白赢。
________________________________
发件人: yzyray ***@***.***>
发送时间: 2022年5月16日 10:31
收件人: yzyray/lizzieyzy ***@***.***>
抄送: awsjgyjgy ***@***.***>; Author ***@***.***>
主题: Re: [yzyray/lizzieyzy] 你好，请问死活对局引擎，能上传到github吗，没找到 (Issue #158)


什么死活对局引擎?

―
