### ISSUE TITLE
Request for multilingualization

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#159]
First of all, we would like to express our deep gratitude for your efforts in developing this wonderful software.

Now, take a look at the screenshot below.
The red frame was not multilingualized, so I would be grateful if you could support this.
![無題](https://user-images.githubusercontent.com/63999713/168426901-7f113733-d04e-4369-9dd2-47a20bf8bd1e.png)

**Comment by hope366** [comment]
I found another part that is not multilingual.
![無題](https://user-images.githubusercontent.com/63999713/168465076-89f0e8bf-95bc-4b29-ae39-66f30c82eca6.png)

**Comment by yzyray** [comment]
Thanks for finding these missing.

**Comment by hope366** [comment]
Thank you for your prompt response😄
Please check the PR(#162) created.
