### ISSUE TITLE
Engine stops after the new game was started

### ISSUE THREAD

**Issue by croosn** [yzyray/lizzieyzy#16]
New game worked out of the box, but after changing a few settings in the config, I wasn't able to start a new game anymore.
![github issue 2](https://user-images.githubusercontent.com/38720539/140820996-abefb5e6-43f6-4c7c-be14-c622d29c278e.PNG)

**Comment by yzyray** [comment]
Can you upload your config.txt,so I can try to reproduce the issue.

**Comment by yzyray** [comment]
The `stop` command does not means stop engine at all.Just stop ponder at your turn,see this option:
![image](https://user-images.githubusercontent.com/49384584/140847514-dec05005-bd7a-4ed4-b62e-3c103801957a.png)
But you screenshot seems strange,there is a line `play Q16`,so a black stone should be placed at Q16.Do you stop/start new game frequantly? or just after the screenshot,a stone is placed at Q16.

**Comment by croosn** [comment]
I found what the bug is.
This works. And I can start new game:

![1](https://user-images.githubusercontent.com/38720539/140911364-4df4cbb9-1d22-46d1-82ce-e9029a7f61d5.PNG)

This doesn't work. I can't start new game:

![2](https://user-images.githubusercontent.com/38720539/140911414-7f707ea9-1578-4bec-aff8-e5e00799f69f.PNG)

**Comment by croosn** [comment]
@yzyray Also, settings from above in combination with "Stop ponder on empty board"

**Comment by yzyray** [comment]
Your test is very helpful,I will fix it in the next release.
