### ISSUE TITLE
There is a problem with the toolbar display under certain conditions.

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#160]
Please see the first screenshot. This is in simple mode with the bottom toolbar hidden. If you maximize Lizzieyzy from this state, the red frame will disappear.
![無題](https://user-images.githubusercontent.com/63999713/168427378-ff9868e7-acc0-43fa-90be-a252fb3e586e.png)
See the second screenshot below. The part of the red frame is not displayed.
![無題1](https://user-images.githubusercontent.com/63999713/168427458-c9091ed5-4d45-4b4d-86dc-7d906ac3df8f.png)
This is a very trivial issue, not asking for improvement, but I'd like to inform you.

**Comment by yzyray** [comment]
Thanks for report.Probably I have fixed it.

**Comment by hope366** [comment]
I was able to confirm that it was fixed.
thank you!
