### ISSUE TITLE
Correction of Japanese localization file related to synchronization

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#161]
The Japanese in the sync function window was a little too long, and it seemed to be a problem, so I fixed it.
The description in language_jp.txt in the readboard folder was partially corrected.
Before modification → MainForm_lblBoardSize = 碁盤サイズ:
After modification → MainForm_lblBoardSize = 碁盤:
![無題](https://user-images.githubusercontent.com/63999713/168428193-d8952e38-b08d-4b7d-9c5e-facced166c26.png)
I uploaded the modified file.
https://drive.google.com/file/d/1kt6QneF49Fa7vbTxBbPyhD8yM7NROWVm/view?usp=sharing

By the way, I have a question about the rightmost part of the red frame in the screenshot above. It is possible to enter a number for the size of the board, but there is no response when I click the check circle. Is this a bug?

**Comment by yzyray** [comment]
Thanks for the fix.

>By the way, I have a question about the rightmost part of the red frame in the screenshot above. It is possible to enter a number for the size of the board, but there is no response when I click the check circle. Is this a bug?

If you choose '新浪','野狐' or 'tygem' on top,the board size can only be 19 , 13 or 9,because these platform does not have other board size,you can try to choose the other two options.

**Comment by hope366** [comment]
After selecting foreground or background, I was able to check any board size part.
Thank you for your guidance😄
