### ISSUE TITLE
閃電分析設置的「單步計算量」

### ISSUE THREAD

**Issue by dinohsu1019** [yzyray/lizzieyzy#165]
![image](https://user-images.githubusercontent.com/30600848/168982085-aa4bdb16-b05d-43c6-a592-cd3c7ead8559.png)

閃電分析中的 katago 使用 analysis 模式而不是 gtp 模式，這對全局分析比較有效率，但「單步計算量」只有會不會太低了？但畫出的勝率圖似乎還好。但我一般用AI的計算量都讓它跑到30k以上的。請代為解惑，感謝先。

**Comment by yzyray** [comment]
这个默认值的本意是快速获得胜率曲线图,所以设置为1,可以根据自己的电脑配置更改,计算速度快的设置的高一些肯定是有好处的,选点计算量高了胜率图也会更准确
