### ISSUE TITLE
unlimited increase in java memory usage

### ISSUE THREAD

**Issue by nambung** [yzyray/lizzieyzy#166]
when starting a match of two katago engines, memory usage javaw.exe is constantly increasing starting from ~300mb to ~4gb. can I disable something to reduce it?

**Comment by yzyray** [comment]
I'm sorry,I already know this issue,but can not find a appropriate way to resolve it currently.The only way I have found is use 32-bit Java Runtime Environment to run the lizzieyzy jar file,it seems 32-bit jre will limit the memory usage.

**Comment by nambung** [comment]
I'll try it, thanks!
