### ISSUE TITLE
About rootPolicyTemperature

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#168]
Line 1859 in the source code DisplayStrings.properties has the following line:
``` SetKataEngines.lblRPT=rootPolicyTemperature  (default 1.0,range 0.01 to 100.0)\:```
But I couldn't see this notation on the GUI. Is this display currently in use?

**Comment by yzyray** [comment]
It is no longer used,because katago config file also does not include the parameter..

**Comment by hope366** [comment]
Thank you for teaching me.
