### ISSUE TITLE
Play and pause icons

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#169]
8053b97
Regarding this, what about reversing the display of the icon?
This is because youtube and general video playback software display a pause icon during playback and a triangle icon during pause.

**Comment by yzyray** [comment]
Yes,it should be revered.
I just use the play/pause icon for menu-engine,so it displayed current pondering status.

**Comment by hope366** [comment]
Thank you for incorporating my proposal.
I was able to confirm that the icons have been replaced.
