### ISSUE TITLE
When I replace chinese .wav files with english sounds in the sound directory, the countdown doesn't work

### ISSUE THREAD

**Issue by croosn** [yzyray/lizzieyzy#17]
Do .wav files have to be in special encoding/codec?
Which english sounds can I use for countdown?

**Comment by yzyray** [comment]
I'm not sure you can try any .wav and if not works upload it...

**Comment by yzyray** [comment]
PCM encoding should works

**Comment by croosn** [comment]
I found out what the bug was. 
Chinese audio uses codec named S16L (signed 16-bit little-endian)
![chinese](https://user-images.githubusercontent.com/38720539/140914518-f6e0d5ae-3843-49c4-8773-c192a07031ab.PNG)
So I used [this online tool](https://audio.online-convert.com/convert-to-wav) to convert the english audio numbers I found online to your codec, now it works. Here are the converted english numbers: 

[english audio numbers.zip](https://github.com/yzyray/lizzieyzy/files/7504341/english.audio.numbers.zip)

**Comment by croosn** [comment]
By the way, I noticed that, currently, the countdown number pronounciation starts at the end of the given second. Countdown pronounciation should start at the beginning of a second.

**Comment by hope366** [comment]
I tried "english audio numbers.zip". It seems to be working fine. Thank you. 
> By the way, I noticed that, currently, the countdown number pronounciation starts at the end of the given second. Countdown pronounciation should start at the beginning of a second.

It seems natural to start from 1, but in Tygem it is 9,8,7 ...
Also, in addition to reading out the numbers, I think it would be better if there were "2 times left" and "The last overtime".
I don't know exactly how it is pronounced in Tygem, but it would be great if it could be reproduced in the same way.

**Comment by croosn** [comment]
> It seems natural to start from 1, but in Tygem it is 9,8,7
Oh I meant something else, sorry I didn't explain well. I actually like 9, 8, 7... :)
But when I hear the last second "one" and I want to click, I already lost the game by time. Because it pronounces the number at the end of period, instead of beginning of period. 
![Untitled](https://user-images.githubusercontent.com/38720539/140924956-5490f607-a065-4c7c-a7ea-f9272299d796.png)
did I explain well now?

**Comment by croosn** [comment]
This is expected, right?

![140924956-5490f607-a065-4c7c-a7ea-f9272299d796](https://user-images.githubusercontent.com/38720539/140925579-c966842d-a15f-452d-b454-2e5f06ce4cf8.png)

**Comment by hope366** [comment]
Thank you for taking the time to prepare the diagram and explain it. 
Your explanation was very easy to understand and I was able to understand it well.
It's a very delicate matter, but I think your claim makes sense.

**Comment by yzyray** [comment]
> By the way, I noticed that, currently, the countdown number pronounciation starts at the end of the given second. Countdown pronounciation should start at the beginning of a second.

I set the sound at end,because after the zero was played player still have one second,If set the sound at start,the time gap after zero will be two seconds...a little strange

**Comment by hope366** [comment]
In my environment, the time will be up about 0.5 seconds after "1" is played.
"0" will not be played. The sound folder has a file for playing "0". When is this played?

**Comment by yzyray** [comment]
> In my environment, the time will be up about 0.5 seconds after "1" is played. "0" will not be played. The sound folder has a file for playing "0". When is this played?

Oh, my mistake...it is one not zero,I will edit previous comment

**Comment by heslazarm** [comment]
> In my environment, the time will be up about 0.5 seconds after "1" is played. "0" will not be played. The sound folder has a file for playing "0". When is this played?

The same here.

**Comment by croosn** [comment]
> In my environment, the time will be up about 0.5 seconds after "1" is played. "0" will not be played. The sound folder has a file for playing "0". When is this played?

The same here.
