### ISSUE TITLE
The progress of the number of visits on the candidate hand is slow

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#170]
I have a question I feel when analyzing a handicap game. That is, the number of visits displayed in the candidate's hands will increase much slower than expected.

See the screenshot below. This is a 4-stone handicap game. I used "pass" for the 2nd, 4th, and 6th moves of white.
Looking at the total number of visits in the red frame, it is "3.5k", but the total number of visits displayed on the candidate hands on the board is "1565".
It seems that there is almost no problem in normal cases, but it seems that this problem occurs when using a path.
Which display is the true number of visits? Is it possible to match both displays?

![無題](https://user-images.githubusercontent.com/63999713/169447453-20ff88f9-10f0-4098-ad93-a6b9b2650bf4.png)

**Comment by yzyray** [comment]
In handicap games candidates is always evenly distributed in first few moves.
There is many candidates not showing on the board,try to set `limit max candidates` to 0(means show all candidates).

**Comment by hope366** [comment]
When I set the number of candidate moves to 0, many hidden candidates were displayed. The total number of those visits seems to match the numbers displayed together.
It seems that many candidate moves are often displayed even in a situation that has advanced to some extent. Searching for places that aren't very important may seem inefficient, but is this the most efficient in total? (Sorry for the question about KataGo)
![無題](https://user-images.githubusercontent.com/63999713/169473759-ca9b9aaf-3fe7-48d2-a682-09d906440fb1.png)

**Comment by yzyray** [comment]
Seaching for many unimportant place maybe caused by the paramater *WRN*(wideRootNoise),which is set to 0.04 by default now.
You can try to uncheck *WRN* in toolbar,see if the search will be limited in reasonable area.
But the default value of WRN is not meaningless,first the WRN only works in analyze command,will not do any side effects during play games,second it can help finding hidden good moves in analysis.

**Comment by hope366** [comment]
After setting the WRN to 0.0001, KataGo almost stopped searching except for the top candidates.
However, using such extreme settings, as you say, will make it difficult for KataGo to find good hidden moves. After all, it seems better to use the default settings for normal use.
