### ISSUE TITLE
Confirmation message when erasing on the board

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#173]
I think there are three ways to erase all the stones and analysis information on the board.
1. "File"-> "New File"
2. "Edit"-> "Clear Board (Ctrl + Home)"
3. The leftmost of the icon list in the top menu. "New empty Board"

Are these three all the same function?
How about displaying a dialog window to confirm "Save", "Do not save", and "Cancel" when executing these functions?
For Windows Notepad, clicking File → New will bring up a window asking if you want to save the information you are working on. If you execute Lizzieyzy's "File-> New File" in the same way, you may accidentally delete it.
In fact, I recently made this mistake myself ...

**Comment by yzyray** [comment]
Very resonable advise,I will add it.

**Comment by hope366** [comment]
Thank you for adopting my proposal.
We have created a PR (#175) for Japanese localization, so please check it.
