### ISSUE TITLE
AI ponders at my turn, while it is disabled

### ISSUE THREAD

**Issue by croosn** [yzyray/lizzieyzy#174]
To reproduce the issue:
1. In "New game (analyze mode)" configure to limit AI to 2000 visits, and disable ponder on my turn
2. Stop the game
3. Click on "Sync"
4. Board synchronization tool (simplified)
5. Select board
6. Enable "Two-Way sync"
7. Click on "Continuous Sync (200ms)"
8. Press [alt+enter] to start the game against AI.
9. AI will ponder on both black turn and white turn. Black ponder would be limited to 2000 visits, but White would ponder infinitely, instead of only pondering for black. Without step 8, AI will not ponder on both turns, but only on one.

**Comment by yzyray** [comment]
Ponder during sync is controlled alone in sync tool:
![image](https://user-images.githubusercontent.com/49384584/170152184-e7e85387-5d3b-482b-b50b-7338c02566f0.png)
