### ISSUE TITLE
Proposal for coordinate display

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#176]
For coordinate display, I usually use "Fox style".
However, the coordinates displayed in the Hawkeye, the candidate move list, or the blunder list in the comment section are based on "normal mode", so it is little inconvenient because they are different from the coordinates on the main board.

I think that it will be easier to use if the coordinate display of various lists is automatically changed due to the change of the coordinate display format of the main board, but what about?

**Comment by yzyray** [comment]
I have corrected the display for `fox style` and `Use I In coords`,but not for any pure number coords.

**Comment by hope366** [comment]
We were able to confirm the coordinate matching between the board and various data in both the Fox style and the style using "I".
Thank you very much for accepting my request and changing the code😄
