### ISSUE TITLE
Linux环境下抓取死活题无法正常工作

### ISSUE THREAD

**Issue by startnoob** [yzyray/lizzieyzy#178]
OS:Manjaro Linux
WM:i3wm和xfce经测试均无法正常工作
问题描述:
在开始抓取后画面随鼠标移动逐渐变黑，导致识别成一片黑棋
图片：https://i.ibb.co/5GrjRd4/Peek-2022-06-06-18-00.gif

**Comment by yzyray** [comment]
我修复好了..你可以试试编译现在的代码,或者等我发下一个版本吧

**Comment by startnoob** [comment]
Fixed, Closing.
