### ISSUE TITLE
About dynamic komi

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#179]
I tried to let KataGo solve the high difficulty problem of Yose No. 367 in FoxGo's problem collection. With the Japanese rule, Komi 6.5 points setting, KataGo could not find the correct movement even after searching 30,000 times.(The correct move is D-5)
![無題](https://user-images.githubusercontent.com/63999713/172194161-f61934ba-e6a8-4b18-9e03-58ce95b10b25.png)

After changing the Komi value to a value that makes the situation as close to the same as possible, KataGo was able to find the correct movement in about 4000 searches.
![無題1](https://user-images.githubusercontent.com/63999713/172195573-4bc9e102-3bb3-4d75-897d-cd2e3c3d5671.png)

It seems that there was a function called dynamic komi in Leela Zero before, but by implementing this in KataGo or Lizzieyzy, will it be possible to get better movement with a smaller number of searches?

**Comment by yzyray** [comment]
It seems very complicated and related to the board status,I dont think I can managed to ajust komi based on it.

**Comment by hope366** [comment]
It doesn't really matter when KataGo is in the lead, but on the contrary, when KataGo is significantly behind, it may be possible to obtain better analysis results by adjusting the Komi to make it almost even. I'm guessing it isn't.
Even if you don't have the dynamic comic function, you can change the comic manually, so I would like to continue to verify this method.
