### ISSUE TITLE
About Candidates list 

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#18]
See the screenshot below. Please tell me some unclear points about each numerical value of "3 (actual)" in the top line. 
- "Lcb (%)", "Policy (%)", "Score Stdev". All of these are 0, but I don't understand why they are different from the numbers on the 4th line. 
- "WinRate (%) " ... There is a slight difference (37.3 and 39.3). I think that the value of "37.3%" is calculated back from the value of the next movement. Is this idea correct? If so, why do we refer to the numbers for the next move? I think it is easier to understand if you refer to the numerical values related to the current movement. The same is true for ScoreLead (%). 
- "Visits = 491", "Percents = 41.6" ... I didn't understand the meaning. What kind of calculation method is used? 
- "Concentration: 92.36%" in the table below. What does this mean and how is it calculated? 
![無題](https://user-images.githubusercontent.com/63999713/140863405-cb06f958-2f4e-4c61-84ce-74a0f8f8d2db.png)

**Comment by yzyray** [comment]
The first line's data is from the next move,the visits=491 is the next move's total visits,and the winrate scorelead is from best candidate of next move.It is designed for observing how much winrate/score is lost in the move.
Maybe Policy can use current candidate no.3's data `4.08`
ScoreStdev can also use next move best candidate's data
Lcb can displayed as "--"

**Comment by hope366** [comment]
In other words, if the actual movement is quite bad, the amount of analysis at that point may not be enough to be accurate. Therefore, it is more reasonable to collect data from the next move.
Is this a correct interpretation?
