### ISSUE TITLE
Problems when flipping the board during a game

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#180]
When playing a three-stone handicap game in genmove mode in a game between KataGo and humans, if you flip the board horizontally or vertically, KataGo will behave strangely.
This issue does not seem to occur in analytic mode.
![無題](https://user-images.githubusercontent.com/63999713/172342943-c102b0a4-c678-4d19-a00b-4169d64407e0.png)

**Comment by yzyray** [comment]
flipping the board will resend all moves to engine,but the command genmove has sended before flipped,so engine will give a move based on the board before flipped.
I guess this issue will not occured  If you flipping the board on your turn.

**Comment by hope366** [comment]
This problem occurred when KataGo was white and I was black and flipped on the black turn.

**Comment by yzyray** [comment]
I have tried flipping board during my turn,and turns out the resend all moves will mess up something..So I will forbid flipping board during games.

**Comment by hope366** [comment]
In most cases, you don't need to flip the board during the game, but only in a three-stone handicap game, the problem arises.
In the case of a 3-stone handicap game, the lower right corner is empty when viewed from the white side. On the contrary, when viewed from the black side, the upper left corner is empty.
Fox Go has a vacant lower right corner in a three-stone handicap game. Lizzieyzy is the same. However, it can be the opposite on other Internet Go platforms. Therefore, when trying to play in cooperation with Lizzieyzy, it will be difficult to handle unless the Go board is reversed.
This is not a serious issue, as analysis mode does not cause similar issues.

**Comment by yzyray** [comment]
I think it is better to disable flipping during genmove game,cause if flipping during computer's turn will lead more issues.
You can place three handicaps by hand and check `continue play`
![image](https://user-images.githubusercontent.com/49384584/173838098-5548dff5-c85d-4ff7-b856-fb03d6cca251.png)

**Comment by hope366** [comment]
Thank you for explaining with an image.
As you say, using `continue play` seems to work😄
