### ISSUE TITLE
About Yike Live

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#181]
When I try to run Yike Live on the Megapack Lizzieyzy, I get the following error and nothing seems to happen after a while.When I closed it once and checked the Lizzieyzy folder, the jcef-bundle folder contained only build_meta.json. When I started Lizzieyzy again and ran Yike Live, it seemed like I was downloading something for a while, and then Yike Live started. When I checked the jcef-bundle folder here, it seemed that many of the missing files had been restored.
I have released the Japanese version of Lizzieyzy from my repository, and there are reports that the same phenomenon occurred with this Lizzieyzy.
I tried it with the official Lizzieyzy at about the same time and it didn't cause any problems here.
![無題](https://user-images.githubusercontent.com/63999713/173001863-a6286c48-81ad-49ec-92ba-1bc0d9e08428.png)

**Comment by yzyray** [comment]
Maybe the `jcef-bundle` folder in Megapack is the older version and mismatch with lizzieyzy,I have added a version check for `jcef-bundle` folder,if mismatched lizzieyzy will delete it and download again.

**Comment by hope366** [comment]
Thank you for teaching me.
So you don't have to worry too much about this problem.
