### ISSUE TITLE
Suggestions for winning percentage graphs

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#182]
The screenshot below shows a handicap game with 5 stones.
The blunder bar on the win rate graph is only displayed where the win rate fluctuates significantly. There are a lot of bad moves besides this part, but there is no indication of the blunder bar there. It's probably programmed to react only to fluctuations in winning percentage.A blunder means a failure, so I think it's desirable to see it not only when you lose your winning percentage, but also when you lose your score.
So why not add an option to show the blunder bar based on the difference from the best AI move?
![無題](https://user-images.githubusercontent.com/63999713/174310140-5847896a-7b24-4573-a564-742dd65bef03.png)

As a second suggestion, why not set up an option to hide the winning percentage line? As you can see from this screenshot, the winning percentage line seems to be of little importance, especially in handicap games.

**Comment by yzyray** [comment]
I have changed blunder bar  algorithm,consider both win rate change and score lead change.
For the second suggestion,I have recived similar suggestion before, but I assume winrate line is indispensable,but your handicap case convinced me.

**Comment by hope366** [comment]
Thank you for always responding quickly to my suggestions 😄
The blunder bar, which was previously hidden during score losses under many handicap game situations, is now visible with this change.
Also, I was worried that the proposal to hide the winning percentage line was a bit radical, but I would like to thank you for adding it as an option.
Please see the PR (#183) created.

**Comment by yzyray** [comment]
The algorithm is actually simple and pretty artificial,just consider score change as a percentile change,such as you made a bad move and loss 5points equals lose 10% score(score loss *2/100%),and take the max loss between winrate and score as current blunder bar.

**Comment by hope366** [comment]
Thank you for letting me know.
I feel that 10% is too little for a score loss of 5 points.
Depending on the situation, it seems that the winning percentage fluctuates by at least 5% for a score loss of 1 point.
By the way, is the height scale of the blunder bar 0 at the bottom and 100 at the middle point?
I have additional suggestions. How about displaying the color of the blunder bar separately for black and white? If they are all the same color, it is difficult to tell which one made the mistake.

**Comment by yzyray** [comment]
>Depending on the situation, it seems that the winning percentage fluctuates by at least 5% for a score loss of 1 point.

I want winrate loss take the dominance  in close game,so I set the percent for score loss a bit small.
>By the way, is the height scale of the blunder bar 0 at the bottom and 100 at the middle point?

yes.
>I have additional suggestions. How about displaying the color of the blunder bar separately for black and white? If they are all the same color, it is difficult to tell which one made the mistake.

I'm worried if set two color for blunder bar,there will be much too color in winrate graph and make it not clearly.

**Comment by hope366** [comment]
>I want winrate loss take the dominance in close game,so I set the percent for score loss a bit small.

Certainly, the idea seems to make sense.
>I'm worried if set two color for blunder bar,there will be much too color in winrate graph and make it not clearly.

Yes, I feel that concern too. It looks beautiful when there is only one color.
