### ISSUE TITLE
The assumed color of the candidate hand is different

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#185]
See the screenshot below. This is a 5 stone handicap game.
Currently, it is the movement of Black 254 (K-18). Multiple candidate moves are displayed on the board. Now place the mouse cursor on A-8.

![無題](https://user-images.githubusercontent.com/63999713/174899691-8120f0cf-6f6c-4417-924c-fb6193849fc7.png)

Then, as you can see, a black stone is displayed at the place where the mouse cursor is placed.
The A-8 candidate is supposed to have a white turn, so a white stone must be displayed. If you hover your mouse cursor over a candidate hand other than A-8, all white stones will be displayed there. Only A-8 is a black stone for some reason.

![1無題](https://user-images.githubusercontent.com/63999713/174900865-8bc566e0-1910-4b89-b385-4f443bcbb929.png)

You can get the SGF of this game record from the link below.
https://drive.google.com/file/d/1G-fuVh5Gkvo6a4adRJLzIiGsSSgBvrFY/view?usp=sharing

**Comment by yzyray** [comment]
Actually,there is a move 8 in the variation at same position with move 1 and leads to the issue.
I've changed to show the variation like this,hide the winrate/po/score and show the last move number instead:
![image](https://user-images.githubusercontent.com/49384584/174967307-d80d6c03-0bc6-4471-89dd-5141c6a523a6.png)

**Comment by yzyray** [comment]
In this case,it's quite easy to figure out due to you can use mouse wheel to watch variation move by move.

**Comment by hope366** [comment]
Hmmm, maybe my observing ability was a little lacking.
