### ISSUE TITLE
The color of the stone is reversed in the change diagram of the sub board

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#188]
First of all, I will upload the game record that is the problem this time.
[qe.zip](https://github.com/yzyray/lizzieyzy/files/9020429/qe.zip)
This game record has only a single aspect because all the stones are fixed. I will present the result of analyzing this game record with the latest Lizzieyzy(KataGo trt 40b s118).
White 6 on the main board is displayed normally, but there is a black stone in the same place on the sub board, and there is no notation of "6".
![無題](https://user-images.githubusercontent.com/63999713/176699170-d6be8e30-c08c-439b-9852-7d9076caf3ec.png)

Next, I analyzed the same game record with Leela Zero.The position of White 6 is different from that of KataGo, but as with KataGo, the display of the sub board is incorrect.
![1無題](https://user-images.githubusercontent.com/63999713/176699881-2a7ce52a-5012-4368-8281-baebfbcee3a4.png)

It seems that this problem is occurring in the case of putting the stone again on the site where the stone was taken.

This problem doesn't seem to occur with normal Lizzie.
![3無題](https://user-images.githubusercontent.com/63999713/176704676-f961694a-da60-4d15-b993-0cf36fcff449.png)

**Comment by hope366** [comment]
Black 3 in the screenshot below is a stone of the same color as the stone that originally existed. This problem does not seem to occur in such cases.
![無題](https://user-images.githubusercontent.com/63999713/176987265-c359adb8-4444-49cb-879b-07762143e5c0.png)

**Comment by yzyray** [comment]
It should be fixed.

**Comment by hope366** [comment]
Thanks a lot.
