### ISSUE TITLE
[Suggest] Switch candidate show with capital Z

### ISSUE THREAD

**Issue by wonsiks** [yzyray/lizzieyzy#19]
In original Lizzie small z and capital Z have different function.
Capital Z switches candidate show on board while small z just switch only while pressing button.
Actually it was very useful for me but lizzieyzy doesn't work like that.
Maybe small z and capital Z have same function I think.

Could you change it work like original lizzie?

Thanks...

**Comment by yzyray** [comment]
Small and capital may be a little confusing....in lizzieyzy key F can be used to hide candidatas,but small board will still show variations,original Lizzie hide small board at the same time with candiates seems reasonable.I'll make key F same as original lizzie Capital Z

**Comment by wonsiks** [comment]
@yzyray Oh, thanks.
