### ISSUE TITLE
无法同步野狐围棋的棋谱

### ISSUE THREAD

**Issue by thuwangming** [yzyray/lizzieyzy#192]
今天尝试同步野狐围棋的棋谱报错，提示“获取棋谱失败”，报HTTP 502错误。上周末（7月23日）还是正常的，请问是野狐关闭了接口还是更改了接口，谢谢！
接口地址应该是这个：
http://h5.foxwq.com/getFechInfo/wxnseed/txwq_fetch_personal_info?srcuid=0&dstuid=0&dstuin=0&username={USERNAME_URL}&accounttype=0&clienttype=0

**Comment by jia707409741** [comment]
请问你这边有解决方法吗？

**Comment by startnoob** [comment]
New Port:
USER:
https://cgi.huanle.qq.com/happyapp/cgi-bin/CommonMobileCGI/TXWQSearchChess?srcuid=0&searchkey={USERNAME_HERE}
GAMES:
https://cgi.huanle.qq.com/happyapp/cgi-bin/CommonMobileCGI/TXWQFetchChess?chessid={CHESSID_HERE}

**Comment by jia707409741** [comment]
楼上的亲测可用！

**Comment by yzyray** [comment]
感谢提供链接,更新了.

**Comment by thuwangming** [comment]
@startnoob 感谢提供链接！

**Comment by seed1Tseng** [comment]
請問如何更新链接接口?謝謝

**Comment by starlife672** [comment]
@startnoob 謝謝分享, 已更新.

將foxRequestQ.jar中的foxgetQ.java重新compile覆蓋回jar中即可

程式碼參考如下
`
package getFoxKifu;

import java.io.BufferedReader;
import java.io.IOException;
import java.net.URLEncoder;
import java.io.BufferedWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.net.URL;
import java.net.URLConnection;

public class foxgetQ extends Thread {
    
	private BufferedReader foxget = null;
	public foxgetQ(BufferedReader var1) {
        this.foxget = var1;
    }

	private static String foxget(String var0) {
        PrintWriter var1 = null;
        BufferedReader var2 = null;
        String var3 = "";
        boolean var9 = false;

        label119: {
            try {
                var9 = true;
                URLConnection var15;
                (var15 = (new URL(var0)).openConnection()).setRequestProperty("accept", "*/*");
                var15.setRequestProperty("connection", "Keep-Alive");
                var15.setRequestProperty("user-agent", "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1;SV1)");
                var15.setDoOutput(true);
                var15.setDoInput(true);
                (var1 = new PrintWriter(new BufferedWriter(new OutputStreamWriter(var15.getOutputStream(), "UTF-8")))).flush();

                for(var2 = new BufferedReader(new InputStreamReader(var15.getInputStream(), "UTF-8")); (var0 = var2.readLine()) != null; var3 = var3 + var0) {
                }

                var9 = false;
                break label119;
            } catch (Exception var13) {
                System.out.println(var13);
                var13.printStackTrace();
                var9 = false;
            } finally {
                if (var9) {
                    try {
                        if (var1 != null) {
                            var1.close();
                        }

                        if (var2 != null) {
                            var2.close();
                        }
                    } catch (IOException var10) {
                        var10.printStackTrace();
                    }

                }
            }

            try {
                if (var1 != null) {
                    var1.close();
                }

                if (var2 != null) {
                    var2.close();
                    return var3;
                }
            } catch (IOException var12) {
                var12.printStackTrace();
            }

            return var3;
        }

        try {
            var1.close();
            var2.close();
        } catch (IOException var11) {
            var11.printStackTrace();
        }

        return var3;
    }
	
    public void run() {
        try {
			
            String var1;
            while((var1 = this.foxget.readLine()) != null) {
                String[] var5;
                if ((var5 = var1.trim().split(" ")).length >= 2) {
                    String var2;
                    String var3;
                    if (var5[0].equals("user_name")) {
                        var2 = var5[1];
                        //var3 = foxgetQ.foxget("http://h5.foxwq.com/getFechInfo/wxnseed/txwq_fetch_personal_info?srcuid=0&dstuid=0&dstuin=0&username=" + URLEncoder.encode(URLEncoder.encode(var2, "UTF-8"), "UTF-8") + "&accounttype=0&clienttype=0&starlife=123");
						
						var3 = foxgetQ.foxget("https://happyapp.huanle.qq.com/cgi-bin/CommonMobileCGI/TXWQFetchChessList?type=4&username=" + URLEncoder.encode(URLEncoder.encode(var2, "UTF-8"), "UTF-8") +"&accounttype=0&clienttype=0");
						
						
                        System.out.println(var3);
                    }

                    if (var5[0].equals("uid")) {
                        if (var5.length == 3) {
                            var2 = var5[1];
                            var3 = var5[2];
                            var2 = foxgetQ.foxget("http://happyapp.huanle.qq.com/cgi-bin/CommonMobileCGI/TXWQFetchChessList?type=4&lastCode=" + URLEncoder.encode(URLEncoder.encode(var3, "UTF-8"), "UTF-8") + "&uid=" + URLEncoder.encode(URLEncoder.encode(var2, "UTF-8"), "UTF-8") + "&RelationTag=0");
                            System.out.println(var2);
                        } else {
                            var2 = var5[1];
                            var3 = foxgetQ.foxget("http://happyapp.huanle.qq.com/cgi-bin/CommonMobileCGI/TXWQFetchChessList?type=4&lastCode=0&uid=" + URLEncoder.encode(URLEncoder.encode(var2, "UTF-8"), "UTF-8") + "&RelationTag=0");
                            System.out.println(var3);
                        }
                    }

                    if (var5[0].equals("chessid")) {
                        var2 = var5[1];
                        var3 = foxgetQ.foxget("http://happyapp.huanle.qq.com/cgi-bin/CommonMobileCGI/TXWQFetchChess?chessid=" + URLEncoder.encode(URLEncoder.encode(var2, "UTF-8"), "UTF-8"));
                        System.out.println(var3);
                    }
                }
            }
			

        } catch (Exception var4) {
            var4.printStackTrace();
        }
    }
}
`
