### ISSUE TITLE
out of moves and komi 7

### ISSUE THREAD

**Issue by nambung** [yzyray/lizzieyzy#195]
when playing two katago engines on a 37x37 board after 723 moves, the message "game finished, out of moves, game record saved..." appears. this has happened many times, every time after 723 moves. how to remove this restriction?
and is it possible to somehow fix komi 7.5? the new game is 7.0 again, and you need to install 7.5 again

**Comment by yzyray** [comment]
>and is it possible to somehow fix komi 7.5? the new game is 7.0 again, and you need to install 7.5 again

![image](https://user-images.githubusercontent.com/49384584/183320444-9b93551f-02d8-40e4-b005-9486199fe5fc.png)
I tesed this field and  can not reproduce your issue, can you make some screenshot?

**Comment by nambung** [comment]
after installing any komi in the "engine game" window, when the game starts, the komi value is reset to an integer!
![1](https://user-images.githubusercontent.com/105792434/183382175-81171b47-b4bb-4c2d-9977-f1477b20d5c9.jpg)
![2](https://user-images.githubusercontent.com/105792434/183382407-e841fe96-41ea-4b09-8010-45ca119720c6.jpg)
![11](https://user-images.githubusercontent.com/105792434/183382543-e6f0dbf1-a240-4b86-a619-71cd4b94348a.jpg)
![12](https://user-images.githubusercontent.com/105792434/183382777-563f7a9e-5f53-4816-b33e-e8d6b1ba773a.jpg)

**Comment by yzyray** [comment]
I still can not reproduce your issue, can you upload your 'config.txt' file in the lizzieyzy folder?

**Comment by nambung** [comment]
[config.txt](https://github.com/yzyray/lizzieyzy/files/9285727/config.txt)

**Comment by yzyray** [comment]
emmm,still fine in my environment with your setttings...
Maybe the issue is related to computer environment like system language or something.
I added komi trace in this exe file https://drive.google.com/file/d/1QFskajzglEHZLTtIVEZuEROeNxWQvAGv/view?usp=sharing
Can you run with this settings(need restart lizzieyzy after save settings):
![image](https://user-images.githubusercontent.com/49384584/183537571-1ef73e7e-2fe3-4d04-b22b-8bc00b5f5d0c.png)
and you will see this two files in the lizzieyzy folder,upload them:
![image](https://user-images.githubusercontent.com/49384584/183537597-795cad79-a9d1-4e60-836d-ad69bcea3e48.png)

**Comment by nambung** [comment]
already doing

**Comment by nambung** [comment]
with this file so far, ok. I'll try again. in any case, thank you very much!
and do I need to download the config now?
I don't have these files...

**Comment by yzyray** [comment]
Dont need log files without issues.
If the issue is fine with the new file,does new game between human and ai have the same issue? or it is fine too

**Comment by nambung** [comment]
the problem remained when playing between human in "analyze mode"

**Comment by nambung** [comment]
[LastGtpLogs_yzy2.5.1.txt](https://github.com/yzyray/lizzieyzy/files/9285939/LastGtpLogs_yzy2.5.1.txt)
[LastConsoleLogs_yzy2.5.1.txt](https://github.com/yzyray/lizzieyzy/files/9285940/LastConsoleLogs_yzy2.5.1.txt)

**Comment by yzyray** [comment]
How about this new one https://drive.google.com/file/d/1b_BFuEGOVtovp1q8Pi4XetjLoK5he0_T/view?usp=sharing
And if all kinds of games is fine now, I still want this infomation,it will help me figure out what's wrong with the issue.
![image](https://user-images.githubusercontent.com/49384584/183541944-ec42bb19-7ddc-42af-b84f-29c692189570.png)

**Comment by nambung** [comment]
ok, already doing

**Comment by nambung** [comment]
[LastConsoleLogs_yzy2.5.1.txt](https://github.com/yzyray/lizzieyzy/files/9286020/LastConsoleLogs_yzy2.5.1.txt)

**Comment by yzyray** [comment]
Great! I think the real issue here is the number formatting in different system language behave different.
After setting language to English,these issues are fine.
