### ISSUE TITLE
komi error message doesn't work in AI vs AI games

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#199]
90f6c0165f1d263908b46bda9ee6f9224071739f
After applying this change, I verified whether it works normally.
For human vs. AI games it works fine, but for AI vs. AI there is a problem.
-150.0~150.0 Setting komi to a value outside this range and trying to start the game will freeze.
A blank message window will appear and Lizzieyzy will not accept any actions.
![無題](https://user-images.githubusercontent.com/63999713/184329224-3dd74cda-19a7-445a-b7c9-1ec4d927e0bc.png)

**Comment by yzyray** [comment]
Thanks for reporting the issue.

**Comment by hope366** [comment]
Thank you for your quick response.
12d8230c626b6e1fceae54d9bb4c7341d13f79a5
I have applied and verified this change.The problem of freezing has been resolved and the error message is displayed normally, but for some reason the error message window could not be deleted with a single click.
It seems that you always need to click 3 times to clear the error message window.

**Comment by yzyray** [comment]
Two times will be normal. Because of there is two engines.Can you try to click slower,click once and wait for a seconds and click the second time,if it still need 3 times there maybe other issues.

**Comment by hope366** [comment]
I've tried various things, but it seems that I always have to click 3 times to get rid of the error message window.
I don't know if it helps, but I'm attaching the following:
[LastConsoleLogs_yzy2.5.1.txt](https://github.com/yzyray/lizzieyzy/files/9333240/LastConsoleLogs_yzy2.5.1.txt)
[LastErrorLogs_yzy2.5.1.txt](https://github.com/yzyray/lizzieyzy/files/9333241/LastErrorLogs_yzy2.5.1.txt)
[LastGtpLogs_yzy2.5.1.txt](https://github.com/yzyray/lizzieyzy/files/9333242/LastGtpLogs_yzy2.5.1.txt)

**Comment by yzyray** [comment]
>I've tried various things, but it seems that I always have to click 3 times to get rid of the error message window.

Yes,I always test it without load any engine,after loaded engine,it's 3 times,and I've found and removed the redundant komi infomation.

**Comment by hope366** [comment]
34a580be8591cdec12a0a48b319dc5cb937bd340
I tried this. It takes two clicks to dismiss the error message window.
It used to be necessary 3 times, but now it seems to be 2 times due to the above change.
Still can't be deleted with one click.

**Comment by yzyray** [comment]
2 times is right,there is two engines,maybe one accept the komi and another dose not.
I will out put engine name in the tips,maybe will be more clearly.

**Comment by yzyray** [comment]
https://github.com/yzyray/lizzieyzy/commit/6fe041b9bd6ffb3e6667d9b535f8de0a5e9561b3 is for this issue,I have copied the wrong links...

**Comment by hope366** [comment]
Each engine checks whether the set komi is correct and outputs the result for each engine.
It is very easy to understand because the engine name is displayed in the error message.
Thank you very much.
