### ISSUE TITLE
如何在google colab中使用PDA模式?

### ISSUE THREAD

**Issue by david0978555097** [yzyray/lizzieyzy#2]
- 當前使用的 lizzieyzy 版本: 20210702-windows64

@yzyray 大佬您好，由於小弟的電腦配置不高，只好使用google colab提供的雲端運算。我使用的是kinfkong大佬的 ikatago，詳細如下:
https://github.com/kinfkong/ikatago-client
其執行頁面為: 
https://colab.research.google.com/drive/1BT4GAlHC1p0gEtujp3EtAYgFSPIjLzxs?usp=sharing#scrollTo=nPaa2KJt8Kyn

小弟都下讓子棋，因此我想要讓katago具有PDA(動態激進度)的功能。在說明文檔有提到，只需在引擎指令後頭加上如下圖代碼即可:
![image](https://user-images.githubusercontent.com/61644640/129470501-eb441cfe-dbd8-4724-9fd6-6d9040a366f1.png)

但嘗試過後，它卻無法加載引擎:
![image](https://user-images.githubusercontent.com/61644640/129470723-c1ed075c-58c3-40d5-90b9-97277de98272.png)
![image](https://user-images.githubusercontent.com/61644640/129470786-c64dd6e6-acab-4736-bddc-70909e706e5c.png)

似乎是無法識別-overide的指令
想請教大佬們，還有什麼方法可以在katago連上google colab的情境下啟用PDA模式?

**Comment by yzyray** [comment]
enableDynamicPdaInAnalyze这个在官方katago引擎中是没有的,所以你需要从我修改过的katago引擎中编译使用:https://github.com/yzyray/KataGo
其实不用也没什么关系,这个选项只是让动态pda在kata-analyze命令下生效
你用官方引擎,只要使用genmove命令pda依然是有效的(引擎对局人机对局都使用genmove模式)
