### ISSUE TITLE
About the last part of the game with AI 

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#20]
I played a game with KataGo with the following settings. 
![無題](https://user-images.githubusercontent.com/63999713/141077567-1cfc65a0-1c19-4b20-876e-6d2087c78773.png)

Finally, I passed because I didn't have a place to hit anymore. I'm expecting KataGo to pass or go through the final process, but contrary to expectations, KataGo will put stones in his position (meaningless).

I have no choice but to pass many times. One problem arises here. If I pass at the countdown "7", I expect to start at "10" next time, but in reality it will start at "6". As a result, the time runs out after passing several times.

If you keep hitting the pass so that the time does not run out, KataGo will become unresponsive after a while. At this time, it would be nice to receive a notice to encourage you to count the score.

**Comment by yzyray** [comment]
I haven't consider pass,pass should also refresh byoyomi time,and yes add a tip at first time pass will be nice.
