### ISSUE TITLE
information about leelazttlse+sailadder

### ISSUE THREAD

**Issue by nambung** [yzyray/lizzieyzy#202]
couldn't find anything about "leelazttlse+sailadder". who knows, please give a link or some information. I am interested in what settings (how many playouts, which network, example of a ladder) the "heuristics for deeper ladders exploration" works under

**Comment by yzyray** [comment]
The ladder part is dilivered from[sai](https://github.com/sai-dev/sai). It's been a long time, I can't remember the detail now...

**Comment by nambung** [comment]
thank you!
