### ISSUE TITLE
About the move number when using "Set as main"

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#204]
First of all, make sure that it is "View → Move number → From 1 in branch".

First, place 4 stones on the board as shown in the screenshot below.
![無題](https://user-images.githubusercontent.com/63999713/200113950-68261626-90bc-472a-b8e5-203f4ac07691.png)

Then go back to White 2 and create a new branch with Black 3, White 4, and so on. 
And make this newly created branch the main branch with "Set as main".
![1無題](https://user-images.githubusercontent.com/63999713/200114037-a8dbec41-ac09-45fe-be4b-f9ad0f69652e.png)

After White 4, Black 5 and White 6 are placed. Then, it is displayed as "black 3, white 4", which is different from what I expected.
![2無題](https://user-images.githubusercontent.com/63999713/200114240-67ab2891-8d45-498d-85f4-f104eae62bca.png)

"View → Move number → Continue in branch" This setting solves the above problem, but this time another problem occurs in the sub branch.
Where it should be "Black 3", it is "Black 1".
![3無題](https://user-images.githubusercontent.com/63999713/200114570-8bc00583-6224-4b73-b0ad-506ae57f4e89.png)

**Comment by yzyray** [comment]
It seems a little chaos after "set as main",I have fixed it by reset all move number after "set as main".

**Comment by hope366** [comment]
Thanks for the fix.
I just verified the main branch, and things look good.
I was able to confirm that the kata estimate issue has also been fixed.
Thank you very much for your positive efforts.
