### ISSUE TITLE
鼠标悬停在选点上时，能否逐步显示下一步

### ISSUE THREAD

**Issue by JerryRTF** [yzyray/lizzieyzy#213]
当前，鼠标悬停在主棋盘的某一个 AI 选点上时，会**一下子**把整个变化图都显示出来，能否有个选项可以选择是否**逐步**显示下一步，这样感觉看着能轻松点。（而且因为如果想**一下子**看到整个变化图，其实在小棋盘上就能看）

就像 Sabaki 这样：
![StepByStep_Sabaki](https://user-images.githubusercontent.com/44433264/213196729-7824e66b-e86e-45d1-a66a-49b97f1ec4f3.gif)

**Comment by yzyray** [comment]
这个功能其实有,在底部的[自动播放]功能里面

**Comment by JerryRTF** [comment]
哦，发现了。之前一直在“综合设置”里找，没找到相关选项，原来是在“自动播放”里勾上“变化图”就会有这个效果了，多谢多谢！
