### ISSUE TITLE
About the heat map display of the sub board

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#220]
In 2.5.2, it seems necessary to turn on the following setting in order to display the heatpap of the sub board.
「View」→「KataGo settings」→「Show kata estimate」→「On sub board」or「On both board」
Show kata estimate setting is unnecessary in 2.5.1 and earlier versions, did you change it intentionally in 2.5.2?

**Comment by yzyray** [comment]
I cant recall any change in 2.5.2.
Are you talking about the heatmap like black or white square image for kataEstimate in sub board?
![image](https://user-images.githubusercontent.com/49384584/218382059-012a49f4-5941-4852-b96a-0a36c100568f.png)
It is the screenshot in my environment, after clicking the 'kataEstimate' button.

**Comment by hope366** [comment]
I'm talking about the red display on the sub-board.
The top screenshot is 2.5.1 and the bottom screenshot is 2.5.2.
In 2.5.1, the red heatmap is displayed on the sub-go board even if the kata estimate is hidden, but in 2.5.2, the heatmap is not displayed if the kata estimate is hidden.
![無題](https://user-images.githubusercontent.com/63999713/218406614-fe736182-8717-4638-af36-cca574cc8958.png)
![1無題](https://user-images.githubusercontent.com/63999713/218406638-1eb323e2-b498-425c-9672-265268524d58.png)

**Comment by yzyray** [comment]
Oh,I almost foget this function,it is not intended,maybe it is broken when I fixing this:https://github.com/yzyray/lizzieyzy/issues/205
It is not hard to fix.Thanks for reporting and explaining.

**Comment by hope366** [comment]
I'm not sure when this issue was fixed, but it seems to have been fixed in 2.5.3.
thank you very much.
