### ISSUE TITLE
About analyze function 

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#23]
In #12, I made an inquiry about Flash Analyze, but there are some new things I noticed about the analysis function. 
1.  Auto analyze
If you accidentally click "Stop" instead of "Start" on the board where the game record data exists,
An empty SGF with no game record data recorded is saved.
Or if you click "Start" or "Stop" on an empty board, the SGF without game record data will be saved as well. 
2. Batch analyze
Select only one game record and click “Stop” to save the empty SGF.
If you select multiple game records and click "Stop", only the first file will be analyzed and saved in the "Analyzed Games" folder.
At the same time, the SGF that does not contain the analysis result is saved in the folder where the original game record exists. 
3. Batch analyze (Flash)
There is no response even if you select only one game record and click "Start".
If you select only one game record and click "Stop", the SGF that does not contain the analysis result will be saved in the folder where the original game record exists.
There is no response even if you select multiple game records and click "Start".
If you select multiple game records and click "Stop", only the first file will be analyzed and saved in the "Analyzed Games" folder.
At the same time, the SGF that does not contain the analysis result is saved in the folder where the original game record exists. 
4. Flash analyze (All game, Part game)
When executed on an empty board, there is no response, but the memory usage increases by about 1700MB and it will maintain that state.

Other than "3", there is no problem unless you use it in a special way, but since batch analyze (flash) itself does not work for "3", I would be grateful if you could correct it.

**Comment by yzyray** [comment]
Fixed,seems broken long ago...and will not saving empty sgfby click `stop` without any analyze.

**Comment by hope366** [comment]
It's working fine now. Thank you.
