### ISSUE TITLE
control panel font size

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#231]
I translated the newly installed "control panel" into Japanese.
Look at the bottom row. The letters on the right are large, but the letters on the left are a little smaller. It's a small thing, but it's easier to see if the letters are a little larger.

One more thing, I translated "Back" at the bottom left as "return to the main branch", is this correct?

![無題](https://github.com/yzyray/lizzieyzy/assets/63999713/691b181a-28c7-4428-abda-52120b2ffbea)

**Comment by yzyray** [comment]
The font size is scaled according to the number of words.But it seems too small for six words.

>One more thing, I translated "Back" at the bottom left as "return to the main branch", is this correct?

Yes,Its same.

**Comment by hope366** [comment]
Thank you.
Thanks to you, the letters are just the right size.
![無題](https://github.com/yzyray/lizzieyzy/assets/63999713/dfbc4010-8ed7-43a8-a3fa-6b790df2e2d7)
