### ISSUE TITLE
katago使用TensorRT后端启动过慢会被lizziryzy认为引擎崩溃

### ISSUE THREAD

**Issue by WuTianyi321** [yzyray/lizzieyzy#236]
TensorRT后端可以在命令行正确启动但启动很慢。如果不在lizzieyzy的设置文件中设置首次加载katago，则lizzieyzy发现在启动后引擎无反应，就认为引擎崩溃了，请问除了每次手动设置首次加载katago外还有什么办法可以解决这个问题？

**Comment by yzyray** [comment]
不会因为trt启动慢就认为引擎崩溃的,请详细给出lizzieyzy认为引擎崩溃的具体信息

**Comment by WuTianyi321** [comment]
> 不会因为trt启动慢就认为引擎崩溃的,请详细给出lizzieyzy认为引擎崩溃的具体信息

![image](https://github.com/yzyray/lizzieyzy/assets/48122470/1601c57f-00e6-43af-964c-ce456739635e)
![image](https://github.com/yzyray/lizzieyzy/assets/48122470/00db6c83-af1e-46b1-ae23-d56ec296aeb3)
没有具体信息，只有引擎异常关闭，我测试在命令行直接用同样命令启动katago不会报错

**Comment by WuTianyi321** [comment]
> > 不会因为trt启动慢就认为引擎崩溃的,请详细给出lizzieyzy认为引擎崩溃的具体信息
> 
> ![image](https://private-user-images.githubusercontent.com/48122470/336136767-1601c57f-00e6-43af-964c-ce456739635e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MzY0MDgsIm5iZiI6MTcxNzQzNjEwOCwicGF0aCI6Ii80ODEyMjQ3MC8zMzYxMzY3NjctMTYwMWM1N2YtMDBlNi00M2FmLTk2NGMtY2U0NTY3Mzk2MzVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDE3MzUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViYzc5MGI5NDA0MTQ5MGUxZDI4ZGUxZjMxOGJmY2I4MTQyNTBkMmUzMTNmYTBmMDMxOGQ1NGQxZjAyMTcwNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w2Pp-fpXuwbHrlgqCqVKMIWW71pN2HDfPszf7mrsysY) ![image](https://private-user-images.githubusercontent.com/48122470/336136967-00db6c83-af1e-46b1-ae23-d56ec296aeb3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MzY0MDgsIm5iZiI6MTcxNzQzNjEwOCwicGF0aCI6Ii80ODEyMjQ3MC8zMzYxMzY5NjctMDBkYjZjODMtYWYxZS00NmIxLWFlMjMtZDU2ZWMyOTZhZWIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDE3MzUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlYmZiMzVhY2JlZmFlYzczYWMxNWMxNmMwZjk3YWVkNGNlMjgwYTY0ZGFlZWNjMTRlYjBjOTk1ODk5MjJmZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1gw0lgZny_bIIbsT-NG3bolm4y8_64xvK0FIHUHntqc) 没有具体信息，只有引擎异常关闭，我测试在命令行直接用同样命令启动katago不会报错
> 
> 在cmd中，结果如下： `Active code page: 65001
> 
> E:\Program Files\lizzieyzy2.5.3>"E:\katago-model\katago-v1.14.0-trt8.6.1-cuda12.1-windows-x64\katago.exe" gtp -model "E:\katago-model\kata1-b28c512nbt-s7168446720-d4316919285.bin.gz" -config "E:\katago-model\config\b28.cfg" 0<test_commands.txt KataGo v1.14.0 Using TrompTaylor rules initially, unless GTP/GUI overrides this TensorRT backend: 1: [myelinCache.h::nvinfer1::builder::MyelinCache::deserializeFromBuffer::52] Error Code 1: Myelin (Myelin error from unknown graph) TensorRT backend: 4: The timing cache will not be used! Initializing board with boardXSize 19 boardYSize 19 Loaded config E:\katago-model\config\b28.cfg Loaded model E:\katago-model\kata1-b28c512nbt-s7168446720-d4316919285.bin.gz Model name: kata1-b28c512nbt-s7168446720-d4316919285 GTP ready, beginning main protocol loop = KataGo
> 
> = 1.14.0
> 
> =
> 
> = Q15
> 
> = info move D16 visits 119 winrate 6297 prior 2758 lcb 6264 order 0 pv D16 Q17 Q3 D4 R6 F17 C14 D17 info move Q4 visits 95 winrate 6277 prior 3179 lcb 6248 order 1 pv Q4 Q17 D16 D3 C5 E4 info move D4 visits 67 winrate 6224 prior 1052 lcb 6177 order 2 pv D4 Q4 D17 Q17 R3 R4 Q3 info move R17 visits 27 winrate 6248 prior 440 lcb 6180 order 3 pv R17 P17 Q16 P16 R15 R14 S14 Q14 S13 Q4 D16 info move D17 visits 20 winrate 6202 prior 229 lcb 6106 order 4 pv D17 Q4 D4 Q17 R3 R4 Q3 info move R4 visits 17 winrate 6188 prior 244 lcb 6071 order 5 pv R4 D16 D4 Q17 O3 C3 D3 C4 info move C16 visits 17 winrate 6183 prior 287 lcb 6049 order 6 pv C16 Q4 D4 Q17 R3 Q3 info move D3 visits 14 winrate 6192 prior 232 lcb 6046 order 7 pv D3 D16 Q4 Q17 C6 R3 info move C4 visits 17 winrate 6181 prior 251 lcb 6060 order 8 pv C4 Q4 D16 Q17 R3 R4 info move Q3 visits 13 winrate 6169 prior 224 lcb 6012 order 9 pv Q3 D16 D4 Q17 Q5 C6 info move Q17 visits 11 winrate 6197 prior 160 lcb 5984 order 10 pv Q17 Q4 D4 D16 R15 info move R3 visits 1 winrate 6003 prior 70 lcb -6497 order 11 pv R3 info move C17 visits 1 winrate 5934 prior 66 lcb -6566 order 12 pv C17 info move D16 visits 125 winrate 6303 prior 2758 lcb 6270 order 0 pv D16 Q17 Q3 D4 R6 C17 C16 D17 F17 info move Q4 visits 101 winrate 6278 prior 3179 lcb 6251 order 1 pv Q4 Q17 D16 D3 C5 E4 R6 info move D4 visits 69 winrate 6221 prior 1052 lcb 6176 order 2 pv D4 Q4 D17 Q17 R3 R4 Q3 info move R17 visits 28 winrate 6248 prior 440 lcb 6182 order 3 pv R17 P17 Q16 P16 R15 R14 S14 Q14 S13 D16 Q4 D4 info move C16 visits 18 winrate 6184 prior 287 lcb 6060 order 4 pv C16 Q4 D4 Q17 E16 C3 C4 info move R4 visits 18 winrate 6180 prior 244 lcb 6070 order 5 pv R4 D16 D4 Q17 O3 C3 D3 C4 info move D17 visits 21 winrate 6197 prior 229 lcb 6116 order 6 pv D17 Q4 D4 Q17 R3 R4 Q3 info move C4 visits 17 winrate 6181 prior 251 lcb 6060 order 7 pv C4 Q4 D16 Q17 R3 R4 info move D3 visits 14 winrate 6192 prior 232 lcb 6046 order 8 pv D3 D16 Q4 Q17 C6 R3 info move Q3 visits 13 winrate 6169 prior 224 lcb 6012 order 9 pv Q3 D16 D4 Q17 Q5 C6 info move Q17 visits 11 winrate 6197 prior 160 lcb 5984 order 10 pv Q17 Q4 D4 D16 R15 info move R3 visits 1 winrate 6003 prior 70 lcb -6497 order 11 pv R3 info move C17 visits 1 winrate 5934 prior 66 lcb -6566 order 12 pv C17 play D16
> 
> = MoveNum: 2 HASH: 78427BEA8BE1B5EE33166A60832B9FE0 A B C D E F G H J K L M N O P Q R S T 19 . . . . . . . . . . . . . . . . . . . 18 . . . . . . . . . . . . . . . . . . . 17 . . . . . . . . . . . . . . . . . . . 16 . . . O2. . . . . . . . . . . . . . . 15 . . . . . . . . . . . . . . . X1. . . 14 . . . . . . . . . . . . . . . . . . . 13 . . . . . . . . . . . . . . . . . . . 12 . . . . . . . . . . . . . . . . . . . 11 . . . . . . . . . . . . . . . . . . . 10 . . . . . . . . . . . . . . . . . . . 9 . . . . . . . . . . . . . . . . . . . 8 . . . . . . . . . . . . . . . . . . . 7 . . . . . . . . . . . . . . . . . . . 6 . . . . . . . . . . . . . . . . . . . 5 . . . . . . . . . . . . . . . . . . . 4 . . . . . . . . . . . . . . . . . . . 3 . . . . . . . . . . . . . . . . . . . 2 . . . . . . . . . . . . . . . . . . . 1 . . . . . . . . . . . . . . . . . . . Next player: Black Rules: {"friendlyPassOk":false,"hasButton":false,"ko":"POSITIONAL","komi":7.5,"scoring":"AREA","suicide":true,"tax":"NONE","whiteHandicapBonus":"0"} B stones captured: 0 W stones captured: 0`

TRT版本问题，正确处理好环境变量切换版本后问题解决。
