### ISSUE TITLE
Source code of InVisibleFrame.jar etc.

### ISSUE THREAD

**Issue by kaorahi** [yzyray/lizzieyzy#24]
There are some *.jar files in the repository. Could you show the sources of them and how to build them?

I am trying to build LizzieYzy on Linux. Though `mvn package` says "BUILD SUCCESS" with the following modification, I hesitate to run `java -jar target/lizzie-yzy2.4.6-shaded.jar` because of *.jar without sources.

~~~
--- a/pom.xml
+++ b/pom.xml
@@ -13,6 +13,13 @@
         <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
     </properties>
     
+    <repositories>
+        <repository>
+	    <id>com.teamdev</id>
+	    <url>https://europe-maven.pkg.dev/jxbrowser/releases</url>
+        </repository>
+    </repositories>
+
 	<build>
 		<plugins>
 			<plugin>
@@ -123,11 +130,11 @@
 			<version>20180130</version>
 		</dependency>
 	
-	 	<dependency>
-  			<groupId>com.teamdev.jxbrowser</groupId>
-  			<artifactId>license</artifactId>
-  			<version>6.21</version>
-		</dependency>
+	 	<!-- <dependency> -->
+  		<!-- 	<groupId>com.teamdev.jxbrowser</groupId> -->
+  		<!-- 	<artifactId>license</artifactId> -->
+  		<!-- 	<version>6.21</version> -->
+		<!-- </dependency> -->
 		
 		<dependency>
 	  		<groupId>com.teamdev.jxbrowser</groupId>
@@ -148,9 +155,9 @@
 		</dependency>
 
 		<dependency>
-			<groupId>com.swingxdate</groupId>
-			<artifactId>swingxcore</artifactId>
-			<version>1.6.2</version>
+			<groupId>org.swinglabs.swingx</groupId>
+			<artifactId>swingx-core</artifactId>
+			<version>1.6.4</version>
 		</dependency>
 		<!-- https://mvnrepository.com/artifact/junit/junit -->
 		<dependency>
~~~

**Comment by yzyray** [comment]
I uploaded jars here,copyto maven local repository should works.
https://aistudio.baidu.com/aistudio/datasetdetail/116851

**Comment by kaorahi** [comment]
Was my previous post misleading? I can build lizzie-yzy2.4.6-shaded.jar but I do not like to run a program without its source code. So I asked about *.java files that correspond to the following jar files.

* foxReq/foxRequestQ.jar
* src/main/resources/assets/clockHelper/InVisibleFrame.jar
* src/main/resources/assets/foxReq/foxRequestQ.jar
* src/main/resources/assets/readboard_java/readboard-1.5.5-shaded.jar

As a trial, I deleted these jar files. I also removed jxbrowser parts and clockHelper parts from pom.xml and *.java. The main function of LizzieYzy seems to work successfully without them.

**Comment by yzyray** [comment]
Oh, I understand now,the `readboard-1.5.5-shaded.jar` is from here:https://github.com/yzyray/readboard_Boofcv
InVisibleFrame.jar is just a empty frame for this issue,I can upload the source tomrrow https://github.com/yzyray/lizzieyzy/issues/8#issuecomment-962392966
foxRequestQ.jar contains a link can be used to download sgf game records from fox game server,hide it because I'm afraid share the link to public will lead fox official forbade to download sgf in this way any more.

**Comment by kaorahi** [comment]
Thanks for the answer!

**Comment by yzyray** [comment]
Upload souce code here:
[foxRequestQ.jar](https://github.com/yzyray/FoxRequest) [InVisibleFrame.jar](https://github.com/yzyray/testbuffer)
