### ISSUE TITLE
Suggestion for bottom left list

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#241]
See screenshot below.
The comment field in the lower left is used as a list. And they are lined up from the top in order from the oldest movement.
The newest move on the main board is White 30, but it's not shown in the bottom left list. It is hidden outside the frame because the amount of movement has exceeded the table area.

Therefore, if you want to know the latest movement information, you need to manually move down the list.
To avoid this manual work, how about automatically pushing out the old movements to the margin and always showing the latest movements?
If the list is managed in the order of moves rather than win rate or score, it would be easier to see if the latest moves are automatically displayed.

![無題](https://github.com/yzyray/lizzieyzy/assets/63999713/015c596f-b061-49c6-869c-9654297a1a0c)

**Comment by hope366** [comment]
Related to the above problem, what is the function of "Next" in the comment field at the bottom left?
If you check here, the list will disappear. Uncheck it to restore it.
![無題](https://github.com/yzyray/lizzieyzy/assets/63999713/a6c69d34-710e-4dd1-aede-c753327b29e4)

**Comment by yzyray** [comment]
The order of table is rememberd.you can click here to reverse the order
![image](https://github.com/yzyray/lizzieyzy/assets/49384584/d2823e31-f71b-40df-a87d-a9a0edb5edf7)
and by default the order is by winrate diffrence.

The 'next' checkbox means only show moves after current move,so if you are not reviewing game the list will be empty.
I'm not sure if the 'next' is correct translation.

**Comment by hope366** [comment]
I knew that clicking "Black" or "White" would reverse the order, but I didn't care that reversing the order would always show the latest movement.
Your good advice seems to have cleared up a minor question. Thank you very much.
I also understood the meaning of "Next". In the Japanese translation, it has the same meaning as Next, so I will change it later.
