### ISSUE TITLE
Failure of synchronization function

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#25]
In v2.4.6, "Sync-> Board synchronization tool(Fox, Tygem, etc. )" does not work. At the first startup, there was a warning　About OpenJDK  from Windows Defender (firewall), and I allowed access, but it did not start. There is no reaction after the second time. 
I tried putting the 2.4.5 dm.dll in the 2.4.6's read board folder, but it didn't work. Regarding the synchronization function, the following four items are working. 
* Yike lve
* Yike room
* Fox kifu
* Board synchronization tool (Simplified)

In the same PC environment , v2.4.5 works fine.

**Comment by yzyray** [comment]
Thanks for reporting,will upload agagin and rename to 2021-11-16 for the windows64 package.

**Comment by hope366** [comment]
"2021-11-17-windows64" can be synchronized with Fox. Thank you.
By the way, I've been using Lizzieyzy since 2.4.4, but it's not syncing with Tygem. Do you feel like you and your surroundings are doing well? 
In my environment, when I launch Tygem, I get the following error. I don't know the details, but does this have anything to do with the inability to sync? 
![無題](https://user-images.githubusercontent.com/63999713/142129613-738b9272-a877-48e7-9988-4c4a04f02388.png)

**Comment by yzyray** [comment]
In my machine sync with Tygem is fine,but Tygem require administrator privilege.
If the windows user is just user privilege,the tygem will ask to input an administrator  account  password.In this situation,sync may failed due to lack of privilege.
There maybe another reason,the Tygem I use is called [弈城围棋](http://www.eweiqi.com) in chinese,I'm not sure if it is same as the Tygem you used,can you share the home page of your Tygem

**Comment by hope366** [comment]
I tried the Chinese version. After installing, two icons were displayed on the desktop.
An error occurred when I executed the icon below. 
![無題](https://user-images.githubusercontent.com/63999713/142136837-c735797b-db5d-421a-93b9-85364e7f481c.png)
Next is this icon ... 
![無題](https://user-images.githubusercontent.com/63999713/142137067-5f9d7632-c39d-4b04-9714-86581110d355.png)
It looks like it can be started as shown in the figure below ... 
When I entered the ID and password and clicked the execute button, nothing happened and the window closed. 
<img src="https://user-images.githubusercontent.com/63999713/142137288-ef024208-7523-4b51-a19d-b446fc9144b4.png" width="50%">

**Comment by hope366** [comment]
I tried running Tygem with "Run as administrator", but I couldn't sync ... 
<img src="https://user-images.githubusercontent.com/63999713/142138154-7b20b4d8-916d-44b7-8d79-3f63b2a083fe.png" width="50%">

**Comment by hope366** [comment]
The Tygem homepage I'm using is probably http://www.tygemgo.com/.

**Comment by yzyray** [comment]
I tried international version tygem,fastSync not works.
But this way should work,click 1 and click inside the board and finally  click 3
![image](https://user-images.githubusercontent.com/49384584/142159934-eff1cbd9-4bce-44c4-9207-0edc3ac87394.png)

**Comment by hope366** [comment]
I've tried that method and it looks good.😄
I was afraid that the display might be strange when I moved the window like "Board synckronization tool (Simplified)", but the state is stable like the wild fox.
It would be great if the history of the game record could be synchronized like Yike Live, but is this difficult?

**Comment by yzyray** [comment]
>It would be great if the history of the game record could be synchronized like Yike Live, but is this difficult?

Yike Live can get the sgf format game records from http request.
Currently the Board synckronization tool just get a screenshot form fox,tygem etc...So it is impossible to get move history.

**Comment by hope366** [comment]
It's a bit disappointing, but it's a great feature to be able to sync professional official matches with Yike Lize. I think it's very convenient for live streaming on youtube. Thank you for your polite guidance.
