### ISSUE TITLE
How to count the score and "double pass" 

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#28]
In the game between engines, there was a result of "double pass" as shown in the figure below. The result of the match is that White wins 1.5 points, so I think it is desirable to include this in the result of the win or loss. By the way, what do the three lines in the red frame below mean? 

<img src="https://user-images.githubusercontent.com/63999713/141868956-1b0c34cc-2c16-4f5d-bee0-d435d4d97859.png" width="40%">

The image below is the "double pass" game mentioned above. Looking at the calculation result at the bottom left, it is calculated in Chinese style. Japanese people usually use the calculation method shown in the red frame on the right, so in the case of Japanese rules, it would be helpful if you could display it as such or add a Japanese-style calculation method as an option. 
By the way, KataGo seems to judge that white has an advantage of 0.5 points ... 
![keisanhouhou](https://user-images.githubusercontent.com/63999713/141870978-a5c2d8f8-e9c2-4922-a0f1-e16d67b1eb2b.png)

**Comment by yzyray** [comment]
Judge the winner in double pass game is a little hard for me,currently just ignore double pass games.
Some double pass game may not at end,and another problem is how to select deadstone automatically.
The japanese score style seems resonable and easy to implement.

**Comment by hope366** [comment]
"Game → Final score" is calculated by Chinese rules, but it seems that "whiteHandicapBonus = N" in the case of handicap game is not reflected. Therefore, there is a difference from the calculation result of KataGo displayed on the board and the winning percentage graph.
Since the attached figure is a handicap game with 4 stones, adding 4 points to the white side will make it almost the same as the calculation result of KataGo.

In addition to the white bonus points for handicap games, it would be great if we could display the calculation method when there is a special seki. 
![無題](https://user-images.githubusercontent.com/63999713/143196512-68dadf44-b3b6-4c54-9d8f-c1a0eb6afe19.png)

**Comment by hope366** [comment]
I tested #59 https://aistudio.baidu.com/aistudio/datasetdetail/120771. There seems to be a problem with the score count. I tested it with the following sgf. 
https://drive.google.com/file/d/1-Od9CRmtLh7fLt9z5x_VtMo7ryL4-d_T/view?usp=sharing

![無題](https://user-images.githubusercontent.com/63999713/145391785-ca0ff722-2a96-4a9d-8ca2-452d1622b37d.png)
I think the correct calculation is as follows.
(Black territory = 76)- (dead stone = 10)=66
(White territory = 66)- (dead stone = 13)+ (komi = 6.5)=59.5
66-59.5=6.5 Black win 6.5 points

Next is the case of Chinese rules. 
![無題3](https://user-images.githubusercontent.com/63999713/145392900-481ab006-08f2-4661-8799-1160afecd020.png)
I think the correct calculation is as follows. 
(Black stones = 111)+ (Black territory = 76)=187
(White stones = 108)+ (White territory = 66)+(komi = 7.5)=181.5
187-181.5=5.5 Black win 5.5 points

**Comment by yzyray** [comment]
@hope366 I have not tested the changes before,there is a big bug...but should be fixed now
