### ISSUE TITLE
Hawk eye (problems with automatic analysis) 

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#30]
Regarding # 13, it seems to be good when doing a normal analysis, but when doing an automatic analysis, it seems that the first movement is not reflected in the graph. 
![無題](https://user-images.githubusercontent.com/63999713/141883882-47a9f5a7-869e-4ab6-8ccf-37175d511955.png)

**Comment by yzyray** [comment]
I know this issue,the graph is same with winrate graph in main frame,the winrategraph will not draw anything untill there is two moves.So here is empty too..But I think its fine,because the empty board does not have a winrate sounds reasonable,and a line can not be draw unless there is two nodes.

**Comment by hope366** [comment]
The figure below is a normal analysis, not an automatic analysis, but in this case the data is filled in the Hawk eye. I was aware that this was normal, so I suspected that there was something wrong with the automatic analysis. 
![無題](https://user-images.githubusercontent.com/63999713/141888427-5a275345-8345-42de-83f0-cafbce2482f5.png)

**Comment by hope366** [comment]
Compare the two figures below. The layout is exactly the same, but the top is from normal analysis and the bottom is from automatic analysis.
The first move of black is pretty bad and the third move is very good, so I think the figure above, which shows 50% of the average, is desirable, and the figure below, which shows 100%, is not good. 
<img src="https://user-images.githubusercontent.com/63999713/141890080-478b739b-7914-4f50-93eb-b2e259a33f97.png" width="60%">
<img src="https://user-images.githubusercontent.com/63999713/141890091-ed438ddd-c2ec-4ff5-b9b2-9e853f4c82e3.png" width="60%">

**Comment by yzyray** [comment]
I understand the issue now,when you start the automatic analysis.
You can set start move to zero,the first move's candidates is actually in empty board....the zero move.
![image](https://user-images.githubusercontent.com/49384584/141890971-0cc0b037-322f-4f45-90b1-56585c8d96ce.png)

**Comment by hope366** [comment]
Well, I specified "0" and it worked fine. However, since the actual movement starts from "1", I think it is a little unnatural to use "0" when specifying it in the automatic analysis.

**Comment by hope366** [comment]
The latest version works in the format I want. Thank you.
