### ISSUE TITLE
About human vs. engine games 

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#31]
I found two issues with human vs engine games. 

During the game, the following display will appear on the upper toolbar. Click Pause on your turn, then click Continue to resume. At this time, pondering of engine is turned on even though it is your turn. This is a problem only if the engine is in "Analyze mode". 
<img src="https://user-images.githubusercontent.com/63999713/141905031-d65ccf27-5e77-47a1-9384-701f7bbf5831.png" width="35%">

Then click Pause during the game to pause. Stop the game in that state. When I start a new game again, the indication that it should be "Pause" remains "Continue".

**Comment by yzyray** [comment]
>At this time, pondering of engine is turned on even though it is your turn. 
Does this happen just the first move or every move after click `Continue` to  resume?

**Comment by hope366** [comment]
This problem occurs with every move.

**Comment by yzyray** [comment]
If I click Pause and Continue at move one and play move 2 3 4 5 6 7....then every move at my turn the engine always ponder even without this option?
![image](https://user-images.githubusercontent.com/49384584/141932462-571e81f9-e9f6-4635-95e4-516af1155585.png)

**Comment by hope366** [comment]
Yes, of course I haven't checked it. 
In other words, every time you repeat "Pause" and "Continue" on your turn, the engine repeats analysis on / off.

**Comment by yzyray** [comment]
Should be fixed in formal release today.

**Comment by hope366** [comment]
End the game with "Pause" paused. When you start a new game again, the part that should be "Pause" is displayed as "Continue". If you click this, it will be paused and it will function as "Pause", but the display and the actual function are inconsistent.
This happens only the first time, and from the second time onward, it is displayed alternately as Pause → Continue → Pause ....
