### ISSUE TITLE
About RawNet 

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#32]
There is "RawNet" in the lower toolbar. This looks a lot like a regular Lizzie "policy network", but is it exactly the same?
In my shallow knowledge, I recognize it as "the first feeling of AI." The image below is RawNet on an empty board, but the best move is "7.0". How was this number specifically calculated? If you know it, I would be grateful if you could let me know. 
<img src="https://user-images.githubusercontent.com/63999713/141986968-e79b0ef6-8bae-49a5-97d5-8efc453443fd.png" width="70%">

**Comment by yzyray** [comment]
The rawNet get infos from katago command `kata-raw-nn SYMMETRY` see [here](https://github.com/lightvector/KataGo/blob/master/docs/GTP_Extensions.md)
The official lizzie's showPolicy function shows `prior` value in `kata-analyze` command
The value shows on board is almost same,it means the network will choose the position by 7 percent probability base on raw network without any MCTS calculation.

**Comment by hope366** [comment]
Thank you, that is, the total of all the numbers on the board is about 100 points.
By the way, I'm trying the `kata-analyze` command but it doesn't work. When I simply run `kata-analyze`, I hear the GPU running in the background, but nothing is output.
The official description says `kata-analyze [player (optional)] [interval (optional)] KEYVALUEPAIR KEYVALUEPAIR` ..., but please give me a concrete example. How can I output the numerical values of `prior` and `lcb`?

**Comment by yzyray** [comment]
`kata-analyze 100` will works,but if you runing in command,the output is pretty long and hard to read,if running in lizzie the GTPconsole will hide these outputs.

**Comment by hope366** [comment]
It doesn't work, but is there something fundamentally wrong? 
![無題](https://user-images.githubusercontent.com/63999713/142127507-bb51b0d8-1f2d-4526-8799-e996c4b7a5f6.png)

**Comment by yzyray** [comment]
You need load engine first use the same command here
![image](https://user-images.githubusercontent.com/49384584/142130504-673cb18d-4589-4f01-bff7-1c83b29a13cc.png)
The command folder should be same as lizzie's folder
![image](https://user-images.githubusercontent.com/49384584/142130961-ef2fb3eb-6fbb-43a2-b2fa-382765bf1521.png)

After engine is loaded,you will see
![image](https://user-images.githubusercontent.com/49384584/142130719-06876afb-e4c7-4b0e-a962-fb3ca0d6f18d.png)
Then input: `kata-analyze 100`

**Comment by hope366** [comment]
Thank you for your polite teaching. Thanks to you, it went well. When I run `kata-analyze 100`, a lot of data comes out automatically. Do I need to close cmd to stop it? It seems that it stopped when I executed `stop` quickly ...

**Comment by yzyray** [comment]
Any new command will interrupt `kata-analyze 100`,It is by design I think,and `stop` command can make sure the katago stop pondering.

**Comment by hope366** [comment]
Thank you. I would like to understand the meaning of each item and numerical value more deeply by comparing the numerical value displayed on the board of lizzieyzy with the numerical value output on the command line.
