### ISSUE TITLE
Version 211116 doesn't work on my Windows10

### ISSUE THREAD

**Issue by wonsiks** [yzyray/lizzieyzy#34]
I don't know why, version 211112 and prior versions work fine but the newest version 211116 doesn't.
It seems to hang in background but there's no app window comes up on screen.
Maybe there's some difference between the recent two versions which makes this problem.

Please tell me how to solve this situation, thanks.

**Comment by yzyray** [comment]
Which package do you use,windows64?

**Comment by yzyray** [comment]
Dose both exe bad bat file not working?

**Comment by yzyray** [comment]
I get what is wrong there.How about the formal release today?

**Comment by wonsiks** [comment]
@yzyray Oh, it works fine now.
Thank you so much.
