### ISSUE TITLE
About "View → Move number" 

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#35]
Select "View-> Move number" to display the menu as shown below. It is divided into upper and lower parts, but always set "ALL" for the upper part and think about the function of the lower part. 
<img src="https://user-images.githubusercontent.com/63999713/142302407-bb9b957f-6046-41d3-9160-e59660fb831e.png" width="30%">
Let's start with this pattern first. In this case, the move number will only be displayed on the current branch. In other words, when you create a new branch, the move number of the previous branch disappears. And the newly created branch is numbered in order from 1. There is no particular problem. 
<img src="https://user-images.githubusercontent.com/63999713/142303504-1e6ad0d5-d1b8-416c-8a2c-4df2fe91a64f.png" width="30%">
Next is the case when "continue in branch" is selected. In this mode, when you create a new branch, it doesn't start at 1 but continues from the number of the previous node. This is a reasonable effect for this item, but it also includes the effect that move numbers are actually displayed on all branches. I suspect this is an unintended behavior. 
<img src="https://user-images.githubusercontent.com/63999713/142312795-8557891f-0d3c-4d1b-8f9b-c86e8edea5ed.png" width="30%">
Next, I think "Always from 1" and "Continue in branch" are in conflict with each other for this pattern. I think it is strange that you can specify them at the same time.  And the actual effect is "Continue in branch".Also, it seems that "Always from 1" and "From 1 in branch" can coexist, but I don't know what is different from specifying only one. 
<img src="https://user-images.githubusercontent.com/63999713/142322398-adb22343-247a-4db1-8ee1-d07a264e8c82.png" width="30%">
Finally, "Show all move number in branch", but the effect is unknown. It looks like it has no effect. In other words, if it coexists with "From 1 in branch", the number will be displayed only in the current branch, and if it coexists with "Continue in branch", the number will be displayed in all branches. 

<img src="https://user-images.githubusercontent.com/63999713/142326506-21b77398-f8c8-4181-900d-11d20ad757cd.png" width="30%">

**Comment by yzyray** [comment]
These options looks chaos....I''ve made it a little clearer,you can try this.By the way the jar should fix https://github.com/yzyray/lizzieyzy/issues/31#issuecomment-971146822 
[lizzie-yzy2.4.7-test-shaded.zip](https://github.com/yzyray/lizzieyzy/files/7559611/lizzie-yzy2.4.7-test-shaded.zip)

**Comment by hope366** [comment]
I tried lizzie-yzy2.4.7-test-shaded.zip. The "Continue" and "Pause" issues have been resolved.
For move numbers, "Always from 1" can no longer be used when "All" is enabled.
Also, when "Continue in branch" is enabled, "Show all move number in branch" can no longer be used.

In my opinion, I don't understand the significance of "Always from 1", so I feel it is unnecessary. Also, "Show all move number in branch" still doesn't seem to work.

**Comment by yzyray** [comment]
![image](https://user-images.githubusercontent.com/49384584/142353182-3c7112ee-63db-4013-a5e0-719fdad6cbd5.png)
If checked `last five` and `always from 1`(will change the translation to always start from 1),the image is:
![image](https://user-images.githubusercontent.com/49384584/142353129-5ed12dc6-351e-4c63-b2c6-6a4e8b0ff665.png)
If uncheked `always from 1`,it shows:
![image](https://user-images.githubusercontent.com/49384584/142353210-f0cc3fb3-6a14-4777-a17f-4bf67d1f11ac.png)

**Comment by yzyray** [comment]
Continue with `Last five` option,currently in a branch and not check `Show all move number in branch`,shows:
![image](https://user-images.githubusercontent.com/49384584/142353597-ceea3931-f4c2-46ab-9632-6847883a3bb1.png)
After checked `Show all move number in branch`,shows:
![image](https://user-images.githubusercontent.com/49384584/142353645-528162bd-ebf8-406c-89d4-589e3ec8f942.png)

**Comment by hope366** [comment]
Oh, I didn't notice how to use it. I apologize for the inadequate verification ...
And I'm glad to know the new usage.

**Comment by yzyray** [comment]
Find a bug....use both `always from 1` and `show all move numer in branch` will lead negetive move numbers

**Comment by hope366** [comment]
Yes, it can be seen both in the existing one and in the previous test.
By the way, if you specify any item from the pull-down menu, the menu will disappear once. It is inconvenient if you use it over and over again.
As long as the mouse pointer stays in the same field in the pull-down menu, it would be nice to be able to specify it permanently and repeatedly.

**Comment by yzyray** [comment]
Emm....I dont know how to make menu holding after click an item.
