### ISSUE TITLE
Japanese version of "how to use LizzieYzy"

### ISSUE THREAD

**Issue by hebaeba** [yzyray/lizzieyzy#38]
LizzieYzy is great.
I have made a Japanese version of how to use it called "LizzieYzyの使い方".
You can find it at https://www.h-eba.com/Lizzie/LizzieYzy/manual.html
It would be great if LizzieYzy's menus and other features were available in different languages, and I hope they are.
By the way, I found the following errors in the "说明文档" folder and would like to inform you of them.

快捷键2021-10-18Folder
* 操作
Ctrl+X 

集成引擎和权重说明Folder
setmaxpolicy 坐标 比例
例 setpolicy c10 1.1

**Comment by yzyray** [comment]
It is Great! Thanks.
Is it appropriate to use the link directly?Or download to local in case of the link may be invalid some day or other reason...

**Comment by hebaeba** [comment]
Since the contents of this "How to use LizzieYzy" document are subject to change in the future, it is preferable to use the links directly, but there is no problem downloading and using them.

**Comment by hope366** [comment]
>快捷键2021-10-18Folder
   操作
   Ctrl+X
集成引擎和权重说明Folder
setmaxpolicy 坐标 比例
例 setpolicy c10 1.1

I will report the results of trying these in my environment.
First of all, the effect of "Ctrl + X" is "Display the explanation of the shortcut key". It's just about the same as "X". The difference is the duration. For example, if you press and hold "Ctrl + X" for 5 seconds and then release it, it will continue to be displayed for about 10 seconds. The "X" simply disappears as soon as you release it. 

Next, regarding `set policy`, it didn't work in my environment (my method may be wrong). Similarly, the `setmaxpolicy` didn't work either. 
![policy-fail](https://user-images.githubusercontent.com/63999713/142592378-d1179a9b-9b82-4dad-a6ad-c262511939a8.png)

**Comment by yzyray** [comment]
"Ctrl + X" should be "Alt + X"
`setmaxpolicy `and `setpolicy ` can only be used on pondering
You can keep pondering and use menu-analyze-show policy to see the candidate prior.

**Comment by hope366** [comment]
>"Ctrl + X" should be "Alt + X"

I got it. 

I added 10 points to K4 while pondering, but there is no such indication on k4 on the board.
Is it impossible to check the added value on the actual board?Is it more likely that K4 will be selected on the next move? I don't know how to generate the next move ... `genmove`? It seems different ... 
![無題](https://user-images.githubusercontent.com/63999713/142602503-f114319b-f5ff-4192-a972-9c0c6887a392.png)

**Comment by hope366** [comment]
It feels better with your great advice. 
<img src="https://user-images.githubusercontent.com/63999713/142627903-81f31012-b8a3-4970-8e19-abf55f215429.png" width="80%">
I created an asymmetrical board with an unlimited number of candidate moves. 
<img src="https://user-images.githubusercontent.com/63999713/142627914-55a5eb98-11a6-4237-b902-a7355875a0f9.png" width="80%">
Next, I added a policy value of 0.1 points to the point of d4. 
<img src="https://user-images.githubusercontent.com/63999713/142627924-fc54182c-a455-430f-93f7-29bb4b924f1d.png" width="80%">
Next I tried `setmaxpolicy d4 1.1`. The policy value at point D4 shows "24.2".
x + (1.1x) = 24.2
x = 2.1 / 24.2
x = 11.5238 ...
So in this case, is the maximum policy value for D4 11.5238 ....?
Even with a large D4 policy value, KataGo doesn't seem to be very interested in D4. Does MCTS downplay policy values?

**Comment by yzyray** [comment]
Maximum policy value means the biggest policy piror on current candidates,in your case is E4=22 so maxpolicy*1.1=24.2
These  two commands just ajust policy piror,MCTS will order candidates by all of visits,winrate,scorelead etc...I'm not sure the details,but policy piror is no doubt just a small part.

**Comment by yzyray** [comment]
Maximum policy value means the biggest policy piror on current candidates,in your case is E4=22 so maxpolicy*1.1=24.2
These  two commands just ajust policy piror,MCTS will order candidates by all of visits,winrate,scorelead etc...I'm not sure the details,but policy piror is no doubt just a small part.

**Comment by hope366** [comment]
I understand the meaning of the formula. Thank you.
These functions may be effective materials for studying and enhancing the behavior of Go AI, but are there any effective uses for improving human Go?

**Comment by yzyray** [comment]
Its actruelly for this item of rightclick menu
![image](https://user-images.githubusercontent.com/49384584/142638681-6855b617-44e3-48bb-81e4-e04cd667a376.png)

**Comment by hope366** [comment]
I think the "Allow" at the top and the "Increase priority" you showed are very interesting features.
I think it helps Go AI find good moves that it doesn't notice. 
Thank you for telling me many things.
