### ISSUE TITLE
About display of coordinates 

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#39]
How about adding a combination of numbers and Chinese numerals for the notation of coordinates?

The left is the CCTV Cup in China, and the right is the NHK Cup in Japan. Chinese numerals are displayed on the vertical axis, and arithmetic numerals are displayed on the horizontal axis. Even in the commentary and comments during the live broadcast of the title battle, it seems that a format like "17-六" is used. 
<img src="https://user-images.githubusercontent.com/63999713/142563954-7aaec766-bf43-4593-9e37-156861e0dc0e.png" width="50%">              <img src="https://user-images.githubusercontent.com/63999713/142563966-c5019323-ebec-48bc-a93d-a45175d974d2.png" width="40%">

**Comment by yzyray** [comment]
It is not easy to draw something like 
![image](https://user-images.githubusercontent.com/49384584/142594951-76d71509-8551-4c99-92d6-2a6a3190f24e.png)
Maybe need prepare some transparent png image  to make it works....a little tricky,and  dont have enough motivation to do it recently.

**Comment by hope366** [comment]
I had little knowledge of computer programming, so I misunderstood that it wouldn't be too difficult. If you think about it, there was no display of Chinese numerals in the GUI so far.
It was nice to know that it was difficult.
thank you very much.

**Comment by yzyray** [comment]
The layout is a little tricky....two word usually not that close like "十七".

**Comment by hope366** [comment]
I was obsessed with stereotypes. The important thing was to "use numbers instead of alphabets", not whether they were Chinese numerals or not.
How about adding an option to display numbers on both the vertical and horizontal axes?

**Comment by yzyray** [comment]
> I was obsessed with stereotypes. The important thing was to "use numbers instead of alphabets", not whether they were Chinese numerals or not. How about adding an option to display numbers on both the vertical and horizontal axes?

This is more easy,and seems useful.
