### ISSUE TITLE
Large Goban support

### ISSUE THREAD

**Issue by kris-computer-go** [yzyray/lizzieyzy#4]
Friday9i — Yesterday at 6:03 PM
For those interested, I compiled Windows versions of KataGo1.9.1 for Large Boards, up to sizes 37x37 and 52x52. There are OpenCL and Eigen AVX2 versions, here they are: https://github.com/lightvector/KataGo/issues/454#issuecomment-913116646

There is some problem in  lizzieyzy with this engines. White passes after few moves and always resigns.

**Comment by yzyray** [comment]
Can you send your gtp log? Its in the config(shift-x)->other settings->log GTP to file
And the file will be produced at lizzie's folder.
Maybe its not GUI's issue current katago model is trainging at max 19 boardsize,if using at 29 boardsize(which is released in official),it can play well,but i dont think it can also handle as large as 52.

**Comment by yzyray** [comment]
oh,I've found a bug on 52 boardsize,when parseing coords like 'BA4','BA' should be '25*2+1=51' but misparsed to 25+1...it lead to place wrong stone when receving engine's response like 'play BA4',but it only effect on the last two colum's move and has nothing to do with pass...

**Comment by kris-computer-go** [comment]
I've managed to configure some 52x52 games. It only works with 20x256 model and preferably 1-3 sec/move.
There is a problem to save sgf, probably is too many moves in the game but parseing coords seems to be OK.

![07 52x52 end](https://user-images.githubusercontent.com/32100449/132767061-e38bb3a3-ff14-43fb-99b2-4eb94235e81a.JPG)

**Comment by kris-computer-go** [comment]
Oh, yes you're right: the last two columns are empty

**Comment by yzyray** [comment]
If you comes up saving sgf issue again,can you try to upload your logs,by select this option.(need lasted release)
Or if ctrl-c can work,you can just use ctrl-c and paste result here.
![image](https://user-images.githubusercontent.com/49384584/132799850-79509548-7840-42ec-863b-ab65196a380a.png)

**Comment by kris-computer-go** [comment]
[LastConsoleLogs.txt](https://github.com/yzyray/lizzieyzy/files/7142850/LastConsoleLogs.txt)
[LastGtpLogs.txt](https://github.com/yzyray/lizzieyzy/files/7142843/LastGtpLogs.txt)

**Comment by yzyray** [comment]
Is there 'lastErrorLogs.txt'?

**Comment by kris-computer-go** [comment]
Yes. An empty one. I will try another game then.

**Comment by kris-computer-go** [comment]
[LastConsoleLogs.txt](https://github.com/yzyray/lizzieyzy/files/7145079/LastConsoleLogs.txt)
[LastErrorLogs.txt](https://github.com/yzyray/lizzieyzy/files/7145080/LastErrorLogs.txt)
[LastGtpLogs.txt](https://github.com/yzyray/lizzieyzy/files/7145081/LastGtpLogs.txt)

**Comment by yzyray** [comment]
I think i catch what's wrong here,a recursion algorithm caused lack of memory.
[fix52.zip](https://github.com/yzyray/lizzieyzy/files/7147216/fix52.zip)

**Comment by kris-computer-go** [comment]
Thanks a lot. I will try tomorrow. 
In my opinion Large Board games are interesting because almost every move is far from the corners and a clear fighting strategy can be observed.

**Comment by kris-computer-go** [comment]
Coords are OK now but after some 600-800 game is freezing
[LastGtpLogs_yzy2.4.3.txt](https://github.com/yzyray/lizzieyzy/files/7150231/LastGtpLogs_yzy2.4.3.txt)
[LastErrorLogs_yzy2.4.3.txt](https://github.com/yzyray/lizzieyzy/files/7150232/LastErrorLogs_yzy2.4.3.txt)

**Comment by kris-computer-go** [comment]
The problem seems to be with displaying board in java when the move time is very short.
Can you compile an exe version please? Also on my 4K display the graphic is better in exe version.

**Comment by yzyray** [comment]
The exe has bundled java environment to the 'jre' folder in the same path with exe,and version should be JRE15,and jar will use your installed java environment ,and your installed java environment is a bit older,so it does not support windows scale and lead to display fuzzyment.
Maybe the short move issue relative to your java environment too,error log shows 'OutOfMemoryError'.I guess older jre can use smaller memory than jre15.
Here is the exe file:
[Lizzieyzy-win64-fix52.zip](https://github.com/yzyray/lizzieyzy/files/7150941/Lizzieyzy-win64-fix52.zip)

**Comment by kris-computer-go** [comment]
Exe file works properly. Thanks for your efford.

**Comment by kris-computer-go** [comment]
There is still some minor bugs: option save raw branch (Ctrl + Alt + S) not working and no move number above winrate graph.
I think after some improvements LizzieYzy coult be a favourite gui for many.

**Comment by cryptsport** [comment]
I ran lizzieyzy on a 63x63 board, KataGo 15b - KataGo 15b!

**Comment by yzyray** [comment]
> There is still some minor bugs: option save raw branch (Ctrl + Alt + S) not working and no move number above winrate graph.
> I think after some improvements LizzieYzy coult be a favourite gui for many.

Yes,there is some minor issue,will be fixed in next release.
And I also create two pr about bigboard to official Lizzie,hope it can work well.
https://github.com/featurecat/lizzie/pull/900
https://github.com/featurecat/lizzie/pull/899

**Comment by cryptsport** [comment]
@yzyray 
Thank you very much for this wonderful program! it works with KataGo 100x100! can you add save for big boards? any option.

**Comment by yzyray** [comment]
It can be saved at here:
![image](https://user-images.githubusercontent.com/49384584/133720826-c1789a3b-8df5-43b2-8c0c-44fae0b7b62b.png)
After loaded this engine,board will be turned to 52x52

**Comment by cryptsport** [comment]
@yzyray
if I use boards larger than 52x52 (https://github.com/lightvector/KataGo/issues/454#issuecomment-810368706), is there any way to save the game? Could you, for example, make a record of coordinates in sgf for such dimensions? ; W [aa27]
; B [ab26].  saving on boards more than 52x52 does not work for me

**Comment by cryptsport** [comment]
Katago works on 63x63 and 100x100 https://lifein19x19.com/viewtopic.php?p=267394#p267394
saving does not work

**Comment by cryptsport** [comment]
@kris-computer-go
you can try q5go https://github.com/bernds/q5Go, there is also a pass on the first move and a quick resign. nets didn't train on such big boards.

**Comment by yzyray** [comment]
oh,you mean save the game,i think i can make it work some time later.

**Comment by yzyray** [comment]
I've update a pre-release,it support save games for largre board,but only itself can read this kind sgf.


> There is still some minor bugs: option save raw branch (Ctrl + Alt + S) not working and no move number above winrate graph.
> I think after some improvements LizzieYzy coult be a favourite gui for many.

These issues should also be fixed.

**Comment by cryptsport** [comment]
@yzyray 
incredible !!! thanks a lot!!!
