### ISSUE TITLE
Problem of suddenly warping to a past node (ando repeated hits) 

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#41]
Here are the steps that will most likely cause this bug in my environment. 

Engine command: "katago_tensorRT\katago_2021102_trt64.exe" gtp -model "weights\kata1-b40c256-s10382453504-d2531003754.bin.gz" -config "katago_configs\default_gtp.cfg" -override-config "enableDynamicPdaInAnalyze = true"

1. Start in default mode (not full screen) Stop pondering immediately.
2. Load the next SGF 
3. https://drive.google.com/file/d/15GfMPckXZ9McCDKESo9SgZdCvFQ2bfDg/view?usp=sharing
4. Press "End" to display the final phase 
5. Grab the right edge of the window with your mouse and move it to the left to make the width of the window look like the screenshot below. 
<img src="https://user-images.githubusercontent.com/63999713/142763131-9843a3d8-deca-4be0-8c02-274045a1ef2d.png" width="30%"> 

6. Click "□" on the upper right to display in full screen 
7. Please return to the original size immediately. 
8. Press the "E" key to display the GTP console. I think it looks like the screenshot below. Please click on the red frame. 
<img src="https://user-images.githubusercontent.com/63999713/142763484-94982852-3e46-4e22-9a09-380f102798d6.png" width="50%">

9. "Undo" is hit many times, and the board is warping to the past nodes. 
<img src="https://user-images.githubusercontent.com/63999713/142763632-8760c145-c132-4cb3-8aea-69f9d26d6d99.png" width="50%">
10. If you press "End" to make it the final phase and then click on the red frame in the same way, it will warp to the past node in the same way. The same thing is repeated over and over again. 

I had a similar problem with Lizzie before. 
https://github.com/featurecat/lizzie/issues/858

**Comment by yzyray** [comment]
I can't reproduce it and I'm not sure if I understand every step right.
About `red frame`  do you mean click the black stone maybe double click? or click beside the stone?
![image](https://user-images.githubusercontent.com/49384584/142958015-d9690a43-8a44-4c78-8670-983af2c167d7.png)
In my test if just click the stone,nothing happend. If double click,return to the clicked stone(double click will return to that move..so in my environment it it right).

**Comment by hope366** [comment]
>About `red frame` do you mean click the black stone maybe double click? or click beside the stone?

It's a single click. The click position is the same around the center and edges of black stone. In short, it means single-clicking on the point (intersection) where black stone is. 
Similar phenomena occur at many points other than the points indicated by the red frame (not all points). The same thing happens not only in black stone but also in places where white stone is. As I now know, this phenomenon also happened in the absence of stones.
And, at the point where this phenomenon occurs, this phenomenon always occurs no matter how many times you try.
In my environment, if you follow the steps above, there is a 100% chance that this is happening so far.

**Comment by hope366** [comment]
I was able to reproduce this bug without using the SGF above. 
1. Start in default mode. 
2. Grab the right edge of the window and resize it as shown above. 
3. Display in full screen. I'll put it back soon. 
4. If you arrange the stones properly, it will suddenly warp to the past node at some point. (It occurs both on and off of contemplation)

**Comment by yzyray** [comment]
I reproduced it,the reason is when you maximumed lizzieyzy,winrate graph will be drawn,and after restored the size winrate graph will be hidden but the position of winrate graph is not cleared.At this point,if you click somewhere on board such as `red frame` is considered as click on winrate graph and lead to jump to some previous move.
