### ISSUE TITLE
About countdown in handicap games 

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#44]
In the case of a handicap game with two or more stones of human vs. AI, the first move is white, but before the white moves, the voice "9" is entered.(If the AI consideration time is extremely short, you may not care)  Then, immediately after the white moves, the black turn starts from "8".
If the AI is black and the human is white, there is no problem.
If the AI is white and the human is black, it's a little inconvenient. 

As an additional suggestion, how about adding a countdown voice when the AI is pondering? Noisy can be annoying, so why not add it as an option?

**Comment by yzyray** [comment]
Thanks,the empty board is considered as black's turn and lead to the issue.
About count down sound for AI,I have not implement all kinds of time controll command for katago or other AIs,I'm not sure AI will absolutely observed time limit,and there is also lags in communication between GUI and engine, If count down sound is played possibly heard zero but AI still not played...

**Comment by hope366** [comment]
OK. It seems that there are almost no people around who care about the presence or absence of countdown on the AI side. So this was my personal little hope.
Thank you.
