### ISSUE TITLE
About TensorRT cache files 

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#46]
The content was messy and difficult to understand, so I will rewrite it.
In my environment, for some time I was able to do both normal and flash analysis with just one cache file:
Most recently, I changed the neural network for flash analysis from 40 blocks to 60 blocks and back to 40 blocks again, and a cache file for flash analysis was generated. 
The bottom row is the recently created cache file for flash analysis. 

kata1-b40c256-s10382453504-d2531003754_gpu_75_19x19-exact_batch16_fp16
kata1-b40c256-s10382453504-d2531003754_gpu_75_19x19_batch64_fp16

I don't understand why this change happened. Do you feel that the part related to the number of threads in the configuration file is related? I don't know anything so far.
If you know anything, please let me know.

**Comment by yzyray** [comment]
The trt engine's cache file will be different If one or more of the following condition is different:
1.model
2.boardsize
3.nnMaxBatchSize value in config file
4.requireMaxBoardSize value in config file
5.trtUseFP16 value in config file
In gtp mode with default config file,nnMaxBatchSize will be roughly equal to numSearchThreads and  requireMaxBoardSize will be true.
In analysis mode with default config file,nnMaxBatchSize will be 60 and requireMaxBoardSize will be false.
For example,the cache file name is `kata1-b40c256-s10382453504-d2531003754_gpu_75_19x19-exact_batch16_fp16`
`kata1-b40c256-s10382453504-d2531003754` is model name
`19x19` is boardsize
`exact` means requireMaxBoardSize is true
`batch16` means nnMaxBatchSize is 16
`fp16` means trtUseFP16 is true (auto maybe equals as true).

**Comment by hope366** [comment]
Thank you for your advice. 
Of the filenames of the two cache files I presented, the different parts were `exact_batch16` and` batch64`.
So I changed the config file for the analysis engine as follows:
`nnMaxBatchSize = 64` → `nnMaxBatchSize = 16`
`# requireMaxBoardSize = true` → `requireMaxBoardSize = true`
With this change, a new cache file is no longer generated when performing a flash analysis. 
Perhaps I was confused because of these parameters changing over the course of my trials. 

By the way, rewriting the configuration file for the analysis engine saves you the trouble of generating a cache file when you start a flash analysis, but is it desirable not to change the default configuration of the analysis engine?

**Comment by yzyray** [comment]
For `requireMaxBoardSize`,if uncheck this option and analyze a 19x19 game first then a 9x9 game,an error will be output and analysis can not be proceed.
![image](https://user-images.githubusercontent.com/49384584/143730402-763f056f-ee98-4c62-bf87-2b126e30d778.png)
![image](https://user-images.githubusercontent.com/49384584/143730373-bc6fee48-8742-4a77-a43f-4cda8cb40dd5.png)
For `nnMaxBatchSize`,I'm not sure the effect of changing it to 16.But theoretically, nnMaxBatchSize should be numAnalysisThreads multipy by numSearchThreadsPerAnalysisThread

**Comment by hope366** [comment]
When `requireMaxBoardSize` is set to" true ", an error occurred in 9x9 analysis regardless of whether the image below was checked. 
![無題](https://user-images.githubusercontent.com/63999713/143731790-45690bf9-04a2-4fdb-bd27-0ab2e01285e4.png)

Next, in the analysis engine configuration file ...
`numAnalysisThreads = 2`
`numSearchThreadsPerAnalysisThread = 16`
`nnMaxBatchSize = 64`
This is the default. 16 * 2 = 32, but why is the third line 64?

**Comment by yzyray** [comment]
Oh I was wrong,default boardsize is 19x19 according to these settings in config:
`maxBoardXSizeForNNBuffer = 19`
`maxBoardYSizeForNNBuffer = 19`
So even first time use flash analyze,but the boardsize is not 19x19 the engine still output an errer.

I also dont know why default nnMaxBatchSize is 64,but I think numAnalysisThreads multipy by numSearchThreadsPerAnalysisThread works like numSearchThreads,so nnMaxBatchSizeshould not less than it.

**Comment by hope366** [comment]
Added `requireMaxBoardSize = false` to the end of default_gtp.cfg. It means to align with `# requireMaxBoardSize = true` (false) in analysis.cfg.
Next, in my environment, default_gtp.cfg has `numSearchThreads = 16`,` # nnMaxBatchSize = <integer> `, so I set analysis.cfg to` nnMaxBatchSize = 16`.
With this setting, it is possible to perform both normal analysis and flash analysis with a single cache file.
And flash analysis on a 9x9 board is also working. 

`numAnalysisThreads = 2`
`numSearchThreadsPerAnalysisThread = 16`
`nnMaxBatchSize = 16`
Flash analysis works with this setting, but is it desirable to have a `nnMaxBatchSize` of 32 or higher?

**Comment by yzyray** [comment]
In the analysis_example.cfg nnMaxBatchSize describtion is:
> nnMaxBatchSize is the max number of positions to send to a single GPU at once. Generally, it should be the case that:
 (number of GPUs you will use * nnMaxBatchSize) >= (numSearchThreads * num-analysis-threads)
 That way, when each threads tries to request a GPU eval, your batch size summed across GPUs is large enough to handle them
 all at once. However, it can be sensible to set this a little smaller if you are limited on GPU memory,
 too large a number may fail if the GPU doesn't have enough memory.
nnMaxBatchSize = 64

So I think if numAnalysisThreads = 2 and numSearchThreadsPerAnalysisThread = 16 nnMaxBatchSize should not less than 32.
And if you set requireMaxBoardSize = false ,trt engine's porformance will decrease a little.

**Comment by hope366** [comment]
It seems that it is not good to play with various settings too much.
We will use the analysis engine with the default settings.
Thank you for your guidance.

**Comment by yzyray** [comment]
Yes,default settings is good enough.
But if you are recommanded more than 32 numSearchThreads In benchmark,set numSearchThreadsPerAnalysisThread*numAnalysisThreads not less than numSearchThreads  will help analysis engine get better performance.

**Comment by hope366** [comment]
As a result of benchmark test in my environment, numSearchThreads is recommended to be 16, so I set it to this value.
In this case, is it desirable to change each parameter of the analysis engine accordingly? For example:
numAnalysisThreads = 2
numSearchThreadsPerAnalysisThread = 8(defaul=16)
nnMaxBatchSize = 16 (default=64)

**Comment by hope366** [comment]
By the way, the CPU information of my personal computer is as follows. 
>Processor Intel (R) Core (TM) i7-9700 CPU @ 3.00GHz, 3000 Mhz, 8 cores, 8 logical processors 

"8 logical processors" seems to mean that the number of threads is eight. In this case, does it make sense to make the value of numSearchThreads greater than 8 in the KataGo settings?

**Comment by yzyray** [comment]
numSearchThreads does not related to CPU processors,it is related to GPU calculation power.
numSearchThreadsPerAnalysisThread affect strength like numSearchThreads,increate numSearchThreadsPerAnalysisThread or numSearchThreads will make MCTS search worse,It is described in benchmark.So I think numAnalysisThreads = 2 and numSearchThreadsPerAnalysisThread = 8 is better in your case.

**Comment by hope366** [comment]
`numAnalysisThreads = 2`
`numSearchThreadsPerAnalysisThread = 8`
Is it desirable to change `nnMaxBatchSize = 64` (default) to 16 when set as above?

**Comment by yzyray** [comment]
I just know nnMaxBatchSize should not smaller than numAnalysisThreads * numSearchThreadsPerAnalysisThread
Not sure the influence of bigger nnMaxBatchSize.
