### ISSUE TITLE
About the color of the blunder node 

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#47]
Suppose you have this setting. 
<img src="https://user-images.githubusercontent.com/63999713/144294801-35695ea2-d0cd-443e-8777-88c4f72738f3.png" width="40%">

The movement of Black 5 is "S18", which is a pretty bad movement. There is a difference of -32.9 points in winning percentage compared to the best candidate. 
By "Consider scoreDiff, threshold as 50% of winDiff", it will be 32.9% * 50% = 16.45%, and "Red" should be selected as the node color. However, as you can see, it is actually "purple" of "winDiff 24% or more".
Am I misunderstanding "Consider scoreDiff, threshold as 50% of winDiff"? 
<img src="https://user-images.githubusercontent.com/63999713/144296980-e46d33f6-48fa-4e8f-9095-1dcf4a2c9ebf.png" width="80%"> <img src="https://user-images.githubusercontent.com/63999713/144296988-4523996c-2c11-468a-90ab-c47f47dffaa4.png" width="80%">

**Comment by yzyray** [comment]
The move S18 is purple color because of the winrate difference is -32.9% ,bigger than your settings -24.
"Consider scoreDiff, threshold as 50% of winDiff" means in your settings `-24 and above winrate difference is purple` equals `-12 and above score difference is purple`

**Comment by hope366** [comment]
thank you for teaching me. I didn't understand the meaning of the English text correctly. 
This feature seems to be quite useful, especially during handicap games.
In handicap games, it can often happen that the value of the winning percentage barely changes regardless of whether the move is good or bad, but even in such a case, the color changes according to the score difference, allowing you to check whether the move is good or bad.
