### ISSUE TITLE
It seems that Jump to End After Load Kifu doesn't work.

### ISSUE THREAD

**Issue by wonsiks** [yzyray/lizzieyzy#48]
Maybe it is a bug.
Check it please and hopefully be fixed in the next version.
Thanks...
<img width="665" alt="20211204_125836" src="https://user-images.githubusercontent.com/37356450/144696083-7b3615c5-5dee-434e-8619-3f286e60f705.png">

**Comment by yzyray** [comment]
Yes, this option is broken.Will be fixed soon.

**Comment by wonsiks** [comment]
@yzyray Thanks...
