### ISSUE TITLE
About handicap games 

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#49]
When analyzing a handicap game from an empty board state without loading a game record, I usually alternate between "putting a black stone" and "pressing the P key". 
Two or three stones aren't too much of a hassle, but arranging more stones can be quite annoying. Is it possible to add a feature that allows you to quickly place a handicap stone?
At that time, it is even more convenient if the Komi automatically becomes 0.5.

**Comment by yzyray** [comment]
![image](https://user-images.githubusercontent.com/49384584/144945044-9a758bec-36b6-47b2-bf1b-00216ddc88d0.png)
The `add black` button allow you to add black stones continuously.But you need click it again to resume normal black and white mode.

**Comment by hope366** [comment]
I forgot to have that feature 😅
That feature makes it much easier to place handicap stones.
Thank you.
