### ISSUE TITLE
Korean language is broken in captures panel.

### ISSUE THREAD

**Issue by wonsiks** [yzyray/lizzieyzy#50]
I'm trying to translate language into Korean and met a problem.
The screenshot shows that Korean language is broken in captures status panel.
Please check this and hope to be fixed.

Thanks.
<img width="922" alt="20211206_223554" src="https://user-images.githubusercontent.com/37356450/144855801-ebe827d7-3a82-4610-a36a-7063d4b7915f.png">

**Comment by yzyray** [comment]
![image](https://user-images.githubusercontent.com/49384584/144944434-75c6df71-1a07-4d98-8127-dd58bdff581a.png)
Can you try to change UI font to "system defualt" in theme,and see if this phenomenon disappeared?

**Comment by wonsiks** [comment]
@yzyray Information panel shows correct characters and works fine by changing UI Font, but candidate list panel is still showing broken characters.
<img width="665" alt="01" src="https://user-images.githubusercontent.com/37356450/144947631-697667ed-2d03-4073-95be-ee19b677580f.png">
<img width="922" alt="02" src="https://user-images.githubusercontent.com/37356450/144947645-5a342642-fede-4442-aedc-f74b56da8e43.png">
<img width="477" alt="03" src="https://user-images.githubusercontent.com/37356450/144947660-885ac48f-34fb-4acb-ad11-8822c373113f.png">

**Comment by yzyray** [comment]
Oh,I have used some Chinese font,seems change to system default font will solve the issue.

**Comment by wonsiks** [comment]
@yzyray Thanks. It does work now!!
<img width="922" alt="01" src="https://user-images.githubusercontent.com/37356450/144959597-3282fd21-a69f-477a-9618-25977155107c.png">
