### ISSUE TITLE
Freezes when changing komi 

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#51]
1. Set KataGo in the engine and start it. 
2. Click "Settings" in the top menu to open the "Engine Management" window. 
3. From the list below, select the one whose engine is KataGo and click it. 
4. When it turns blue, change the value of komi and click "Save". 
5. Click the "x" in the upper right corner to close the window and lizzieyzy freezes. 

This problem only happens when I change KataGo's komi while KataGo is running, and it doesn't seem to freeze in other situations.

**Comment by yzyray** [comment]
Does it happens ever times?

**Comment by hope366** [comment]
I tried it about 10 times, but it all froze.

**Comment by yzyray** [comment]
![image](https://user-images.githubusercontent.com/49384584/144955736-cf9feaa4-1c74-471c-8738-725e03b282d9.png)
![image](https://user-images.githubusercontent.com/49384584/144955780-abfb6942-d657-4289-a813-8d3fa85fd1d2.png)
I have run the opencl katago engine,and change komi-save-click right corner "X",and freeze does not happen...Do I miss something?

**Comment by hope366** [comment]
With more verification, we made new discoveries. 
It seems that any engine with `-override-config" enableDynamicPdaInAnalyze = true "` at the end of the engine command will always freeze. The screenshot below shows what it looks like when it freezes. 
![無題](https://user-images.githubusercontent.com/63999713/144958661-ed0edef2-614e-4e4f-8aa3-781b9d1d035b.png)

A normal engine without a PDA will almost never freeze, but rarely (about once in 10 times). When verifying several times with an engine without a PDA, changing the value of komi sometimes resulted in a strange display like the screenshot below. This was quickly resolved by switching pondering. 
![無題1](https://user-images.githubusercontent.com/63999713/144958973-51f2c8bd-5626-4df8-8d97-823df442ccd3.png)

The screenshot below shows a rare freeze on a normal engine. 
![無題2](https://user-images.githubusercontent.com/63999713/144959085-315e6b2a-cbfe-4566-869e-c94aed5adde7.png)

**Comment by yzyray** [comment]
I can reproduce it by added `-override-config "enableDynamicPdaInAnalyze = true"`
Fortunately,I find the issue is already solved by restart exsited engine after changed any engine's parameter in https://github.com/yzyray/lizzieyzy/issues/40

**Comment by hope366** [comment]
Does that mean that the next release will resolve this issue and the # 40 issue at the same time?
That's wonderful!

**Comment by yzyray** [comment]
Yes,If there is not other issues I have not ware of.

**Comment by hope366** [comment]
I'm looking forward to the next release.
Thank you.
