### ISSUE TITLE
Problems when analyzing handicap games 

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#56]
![無題2](https://user-images.githubusercontent.com/63999713/145064814-ee1948d2-d816-4f06-b068-fdb7baf225ec.png)
This is a game record downloaded from FoxGo. Move numbers are displayed correctly on both the mainboard and the winning percentage graph.  As you can see, if you can download the SGF, it's okay, but if not, you'll have to manually line up the stones. 
![無題3](https://user-images.githubusercontent.com/63999713/145066333-4e18a337-da2f-4ea7-8e46-aa494f28dbd9.png)
If you arrange the stones normally, it will look like this. However, if this is the case, it will be different from the actual move number of the game record. In the actual game record, the handicap stone placed from the beginning does not have a move number, and White 5 in this screenshot is White 1. 
![無題4](https://user-images.githubusercontent.com/63999713/145067692-04dc7ddc-cda8-48e4-9a09-3eb1fe5d0c79.png)
I created a branch so that the first movement of white is "1". The mainboard looks good in this case, but the move numbers on the win percentage graph aren't right. 
Is there a good way to manually create a game record for a handicap game?

**Comment by yzyray** [comment]
![image](https://user-images.githubusercontent.com/49384584/145127535-1f2f21bd-54f8-4dc9-8cb4-1bfe57e9fa9a.png)
I have added a menu item `Flatten all moves`,will set current move to move one,maybe will works for this situation.
[lizzie-yzy2.4.7-test1208-shaded.zip](https://github.com/yzyray/lizzieyzy/files/7672474/lizzie-yzy2.4.7-test1208-shaded.zip)

**Comment by hope366** [comment]
It's working fine 😄
Thank you.

**Comment by hope366** [comment]
I noticed when creating a game record by hand, is there a way to display the player's name and rank under the board?
I think it is possible if you edit sgf with an editor, but it is a little annoying. Is there a way to edit on the GUI?

**Comment by yzyray** [comment]
You can try edit-edit game info(short key I).
But It only allow you to add player name,rank is not included.

**Comment by hope366** [comment]
Oh, I forgot to have that feature 😅
There is no problem if the rank is described together with the player name. 
For example, like this ... "toda 9d"

**Comment by yzyray** [comment]
> I found a trivial problem when using "lizzie-yzy2.4.7-test1208-shaded.zip".
> 
> 1. Turn off pondering after launching lizzie-yzy2.4.7-test1208-shaded.jar
> 2. Click "Add black (Right Click add white)" in the top menu to place some black stones on the board.
> 3. Click "Add black (Right Click add white)" again to restore the original state.
> 4. Turn on pondering (you may come here with pondering on from the beginning)
> 5. Place a white stone anywhere. Then pondering will be turned off automatically.
> 6. When you place the next blackstone, pondering will resume automatically.

Yes,I have also noticed this issue,it should only happens with `-override-config "enableDynamicPdaInAnalyze=true"`
I will correct it later.

**Comment by hope366** [comment]
Yes, as you say, this issue only seems to occur with ` -override-config"enableDynamicPdaInAnalyze = true"`.
