### ISSUE TITLE
The winning percentage graph may not respond 

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#57]
The screenshot below is a phase diagram of Black 218 in a 4-stone handicap game. "Black 222" is displayed on the main board because the pre-arranged black handicap stones are counted. (Related to #56) 
Observing the main board and the winning percentage graph, the analysis results are displayed correctly without any discrepancies. Next, take a look at the screenshot below. 
![無題6](https://user-images.githubusercontent.com/63999713/145071651-6f7a9d76-9619-481d-96fd-24569e5f9cfc.png)
The screenshot below is exactly the same aspect of the game record as the screenshot above, but the numbers displayed on the winning percentage graph are different from the numbers on the main board. 
Each numerical value of the winning percentage graph is the numerical value in the phase of white 221 and even if black 222 is used on the main board, the winning percentage graph is not responding. 
This phenomenon is not very frequent and can be easily seen, but it may or may not occur in exactly the same situation, and it seems to be random. 
![無題5](https://user-images.githubusercontent.com/63999713/145071637-2ef05e9a-e640-479f-87bb-ea61691ddc23.png)

**Comment by yzyray** [comment]
Can you upload the analyzed sgf?

**Comment by hope366** [comment]
I uploaded the analyzed sgf. 
https://drive.google.com/file/d/14fMKaLTZTN1DMJ-R3AK_JoMvrX0z6TRH/view?usp=sharing

**Comment by yzyray** [comment]
I can not easily reproduce it,maybe as you say this phenomenon is not very frequent and can be easily seen.
But I do find some buggy codes about winrate graph,so I correct it and upload here,hope it will works.
[lizzie-yzy2.4.7-test1208-2-shaded.zip](https://github.com/yzyray/lizzieyzy/files/7672674/lizzie-yzy2.4.7-test1208-2-shaded.zip)

**Comment by hope366** [comment]
I have tested "lizzie-yzy2.4.7-test1208-2-shaded.zip" with several different sgf, but so far no bugs have been confirmed.
Although not related to this issue, the move numbers on the winning percentage graph can be difficult to see due to the winning percentage line or score line. 
![無題](https://user-images.githubusercontent.com/63999713/145134222-0599fa48-9be0-41c5-85d3-839ac22f8a23.png)

**Comment by yzyray** [comment]
It is not easy to avoid overflap,I dont want move number beyond the winrate/score line due to the winrate/score line is more important.
The move number is on top because current winrate is below 10%,but the previous winrate is high and leads to overflap,I will ajust the value to 3%,maybe helps with this situation.

**Comment by hope366** [comment]
I see, that is, this problem is likely to occur when the winning percentage fluctuates extremely.
By changing from 10% to 3%, will the move number be displayed at the bottom under more circumstances?

**Comment by yzyray** [comment]
Even changed to 3%,if winrate fluctuates from below 3% to such as 99%.Overlap will still happens,but will be less frequently than 10%.

**Comment by hope366** [comment]
Changing from 10% to 3% will make it less likely that overlap will occur if Black has a very high win rate and then plummets.
On the other hand, if Black's win rate jumps from a very low position, a fluctuation of only 3% will lead to overlap. 
In order to solve this problem, instead of fixing the threshold to 3% or 10%, I thought about reversing the display position of the move number if it fluctuates by 80% or more from the current winning percentage. However, in this case, if the winning percentage fluctuates little by little, it will not be possible to respond ... 
After all, no matter what method you use, if the winning percentage is intense and the fluctuations are repeated up and down, you cannot completely prevent the overlap, so it may be better not to be too nervous.
