### ISSUE TITLE
Yike live window doesn't pop-up.

### ISSUE THREAD

**Issue by wonsiks** [yzyray/lizzieyzy#59]
I've compiled the latest 2.4.7 branch source code and Yike live(room) window doesn't show-up.
I'm not sure if this is a bug or my compiling way was wrong.
Please check if this is a bug or not.

Thanks.

**Comment by yzyray** [comment]
You need put extra jars into local maven repository here is the link: https://aistudio.baidu.com/aistudio/datasetdetail/116851
If last release Yike live is ok in your environment,I think 2.4.7 will be fine too.

**Comment by wonsiks** [comment]
@yzyray I've put all extra jars already and here's my compile log.
However Yike live window still doesn't work.
<img width="734" alt="compile_success" src="https://user-images.githubusercontent.com/37356450/145327768-896236f9-cd7a-4c59-a3c3-2ae7d017155c.png">

**Comment by yzyray** [comment]
The compile log seems fine,I uploaded my newest 2.4.7 branch compiled jar here,can you try it:https://aistudio.baidu.com/aistudio/datasetdetail/120771

**Comment by wonsiks** [comment]
@yzyray Your .jar file works fine.
I don't know why mine doesn't work.

**Comment by wonsiks** [comment]
@yzyray Introduction(Chinese version) window doesn't open too.
Japanese version introduction window opens well.
Is there any concerns between them?

**Comment by wonsiks** [comment]
@yzyray Could you let me know your jdk and maven version?

**Comment by yzyray** [comment]
The chinese version introduction is a pdf file opened by jxbrowser(a chromunium based browser).The yike live is also opened by it.
I have changed both maven and java version but never comes up with jxbrowser issues,currently is
```
C:\Users\Administrator>java -version
java version "1.8.0_311"
Java(TM) SE Runtime Environment (build 1.8.0_311-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.311-b11, mixed mode)

C:\Users\Administrator>mvn --version
Apache Maven 3.8.3 (ff8e977a158738155dc465c6a97ffaf31982d739)
Maven home: D:\apache-maven-3.8.3
Java version: 1.8.0_311, vendor: Oracle Corporation, runtime: D:\Java\jdk1.8.0_311\jre
Default locale: zh_CN, platform encoding: GBK
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```
Have you put these three files into the three folder's 6.21 folder?
![image](https://user-images.githubusercontent.com/49384584/145392383-3b253e01-830c-4667-bf6e-e9cba0d8a868.png)

![image](https://user-images.githubusercontent.com/49384584/145392269-c67c1780-4968-44e7-aee8-5aebe466db2b.png)

**Comment by wonsiks** [comment]
@yzyray Sure, I've put files correctly I think.
I will change jdk and mvn version same as yours and test compile.
But I'm afraid the locale and platform encoding are still different.
<img width="386" alt="20211209_210044" src="https://user-images.githubusercontent.com/37356450/145393123-ff62bbea-bf77-485b-aad5-5dbc319c3ada.png">

**Comment by wonsiks** [comment]
@yzyray I've redownloaded all extra jar files again and now it works fine.
Maybe there was some problem with an extra jar file I guess.
Thank you for your help.
