### ISSUE TITLE
Open kifu from online shows broken character.

### ISSUE THREAD

**Issue by wonsiks** [yzyray/lizzieyzy#60]
There's no problem when open a .sgf file from local PC but Korean characters' broken when open the same file from online.
It seems maybe there's a encoding or characterset bug.
Here are screenshots.

open from online
<img width="922" alt="online_broken" src="https://user-images.githubusercontent.com/37356450/145332876-9ecb2829-102e-47ca-88aa-bd824a7b275a.png">

open from local PC
<img width="922" alt="work_fine" src="https://user-images.githubusercontent.com/37356450/145332885-a6a0ca56-3929-4914-afb0-38b789460756.png">

**Comment by yzyray** [comment]
Can you share the sgf's link?

**Comment by wonsiks** [comment]
@yzyray Here it is.
https://github.com/wonsiks/mygibo/releases/download/0.1/Seventeen_Vs_Zen9D_20211209.sgf

**Comment by yzyray** [comment]
I have made some changed,but not sure it will work.

**Comment by wonsiks** [comment]
@yzyray Yes, it works fine now. Thanks.
