### ISSUE TITLE
How to compile 

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#61]
I'm not a computer programmer, but I was lucky enough to find a way to compile lizzie on the web and succeed. 
The specific procedure is to put all the lizzie source code in the bin folder of "apache-maven-3.6.3-bin", open the PowerShell window from "Shift + right click", and `.\mvn package -DskipTests=true`. 

I tried to compile lizzieyzy this way. 
1. I put the master source code of lizzieyzy in the bin folder. 
2. I also put the following four files. 
license-6.21.jar
jxbrowser-win64-6.21.jar
swingxcore-1.6.2.jar
jxbrowser-6.21.jar

This method didn't work.  Please tell me what is wrong or missing.

**Comment by yzyray** [comment]
You need put the four files into local maven repository.
Local maven repository position can be set here:
![image](https://user-images.githubusercontent.com/49384584/145394075-27213440-b9ab-4716-a25d-b83ed1aaf070.png)
These folder will be auto created after `mvn package` command(eg. use the command compile first and ignore the error,just for create folder)
![image](https://user-images.githubusercontent.com/49384584/145394607-2f59395b-1618-4dbb-8ea0-5b958a301ae8.png)
![image](https://user-images.githubusercontent.com/49384584/145394160-2c5ee567-c926-4c3b-b5d7-7e21150e0db8.png)

**Comment by hope366** [comment]
Is it okay to look like this? 
![無題](https://user-images.githubusercontent.com/63999713/145398505-c956a892-5b3c-43c3-a7fe-f3044e9deaed.png)

![無題1](https://user-images.githubusercontent.com/63999713/145398518-dca44960-4842-47f0-b45e-c9eaed82110b.png)

**Comment by hope366** [comment]
I also placed each jar file in a folder with the same name. Is this ok? 
![無題2](https://user-images.githubusercontent.com/63999713/145399474-9dd2ec9c-1088-4868-9697-fcb34fc6dd8d.png)
![無題3](https://user-images.githubusercontent.com/63999713/145399487-36c0268f-cda0-42c3-b43f-4b1e7237c1b9.png)
![無題4](https://user-images.githubusercontent.com/63999713/145399495-b42b35f4-3626-43c1-9e16-20b1b4e769cb.png)

**Comment by hope366** [comment]
Thanks to your advice I was able to compile. 
By the way, I downloaded two folders, "FoxRequest-master" and "testbuffer-master". Where should I place them?

**Comment by yzyray** [comment]
These two is not needed,already concluded in lizzieyzy's source code files.

**Comment by hope366** [comment]
Thank you for your teaching. 
I'm trying to display the main parts of lizzieyzy in Japanese.
In the case of normal lizzie, it worked just by adding the necessary code to the file for Japanese as shown in the screenshot below, but in the case of lizzieyzy, this did not work. I tried changing "Sync" in the upper menu to "同期" in Japanese, but when I started it, it was still in English. Do you need any other special operations? 
![無題](https://user-images.githubusercontent.com/63999713/145407286-f645ba2f-dc8f-443c-9ada-bee6ae8b8c65.png)
![無題1](https://user-images.githubusercontent.com/63999713/145407295-c071eda9-0656-4d9a-91c6-494e396cf0fa.png)

**Comment by hope366** [comment]
Since it was "English", I changed it to "Default". 
![無題](https://user-images.githubusercontent.com/63999713/145409745-63e3fe33-b283-4d5c-9215-dc9f47f483be.png)
Seems to have worked 😄
I added only "Sync" in the top menu, but some other displays were preset in the Japanese file.
Since the number of missing items is huge, displaying in Japanese is a painstaking task 😅

**Comment by yzyray** [comment]
Yes,It is a lot of works,and some english translation tag is not very appropriately maybe make it harder.

**Comment by yzyray** [comment]
Yes,It is a lot of works,and some english translation tag is not very appropriately maybe make it harder.

**Comment by hope366** [comment]
I'm sure it was a tremendous amount of work.
I pay tribute to your enthusiasm for making this software.

**Comment by yzyray** [comment]
Mistyped previous commit,should be fix https://github.com/yzyray/lizzieyzy/issues/68

**Comment by hope366** [comment]
I was able to confirm that it works normally.
Thank you.
