### ISSUE TITLE
About the estimate function 

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#65]
Consider the screenshot below. 
![無題](https://user-images.githubusercontent.com/63999713/145676447-db5b6c1a-4fad-463b-969e-7adeeb43e55e.png)
Organize the situation. In Japanese rules, it is usually calculated like this. 
                                       
Black territory : 76  　　　                                  
Black Dead stone on board : 8                                                
Captured Black stone : 2   
Difference : 66

White territory : 66
White dead stone on board : 3
Captured white stone : 10
Difference : 53    

I used the estimate feature. The result is as follows.I don't quite understand the meaning of these numbers and calculation methods. 
In the following image, if you make it look like the yellow letters, it will be easier to understand as a Japanese rule. 
<img src="https://user-images.githubusercontent.com/63999713/145676928-b390b407-21f8-4b38-abb1-fd3c654d4c50.png" width="50%">
If the calculation method is set to "Area", it will be the Chinese rule method, which is very easy to understand. 
![無題4](https://user-images.githubusercontent.com/63999713/145677534-433d9a7d-7f49-43c0-88e2-b43598b1e3d1.png)
Then see the screenshot below. This is the setting window for the estimate function, but what does the part shown in the red frame mean? 
![無題3](https://user-images.githubusercontent.com/63999713/145677599-2b9c324c-f108-43da-9848-b7f7417f9405.png)

**Comment by yzyray** [comment]
The threshold 0.5 means in katago command `kata-raw-nn`'s whiteOwnership field if a position is bigger than 0.5 then it belongs to white,if smaller than -0.5 belongs to black.

**Comment by hope366** [comment]
Thank you for letting me know.
