### ISSUE TITLE
About manual intervention 

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#68]
<img src="https://user-images.githubusercontent.com/63999713/146362033-06319d48-a32b-460c-b37d-0fef5f8fd4c8.png" width="50%">
During a game between engines, I tried using the manual intervention function after pausing. I'm not sure how to use "Play now". It looks like nothing is happening when I click it. If you repeat "Play now" and pause → resume, the engine will ignore the time control and place stones at super high speed. 

Then click "Enable Manual Place" to allow the stones to be placed freely, and the top menu will always display "Continue". ("Pause" will not be displayed) Clicking "Disable Manual Place" seems to fix this problem.

**Comment by yzyray** [comment]
I design and test `manual intervention` function on the condition of game is be playing,haven't consider  after pausing.The `play now` should only affect the current move,make engine play immediately.

**Comment by hope366** [comment]
"Play now" is only valid in analysis mode, not in Genmove mode. The range and extent of the effect appears to be valid for all moves from the next turn onwards, not just the current move. In other words, once you use "Play now", from the next time onwards, black or white will ignore the time control and start at super high speed. 
In addition, these effects continue not only for games that use "Play now", but also for games that have ended and started anew. 
Are these phenomena designed to be that way?

**Comment by yzyray** [comment]
Yes,these is a bug.Only designed to affect current one move.
