### ISSUE TITLE
About "Current" of Hawk Eye 

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#69]
![無題](https://user-images.githubusercontent.com/63999713/146443522-558dd1a1-c569-4bf0-be8f-37d5d6dd3a87.png)
This is an image of Hawk Eye. When doing the translation work, I couldn't differentiate this part. I don't really care about the English version, but it is convenient to distinguish them in order to express them in Japanese. So, I thought it would be nice to make the following changes, but what about? 

MoveListFrame.java　line422
`    new JCheckBox(Lizzie.resourceBundle.getString("Movelistframe.lblShowBranchItemCurrent"));`
↓
`new JCheckBox(Lizzie.resourceBundle.getString("Movelistframe.Current"));`

Then add `Movelistframe.Current=Current` to DisplayStrings.properties.

**Comment by yzyray** [comment]
The left current means show datas about current branch,the second one means show data form move 0 to current move.

**Comment by hope366** [comment]
Yes, I could guess that it was such an interpretation. However, because the two "current" were in the same group, it was not possible to distinguish them when translating into Japanese.

**Comment by yzyray** [comment]
Ok,I separated it into two items:
Movelistframe.lblShowBranchItemCurrent
Movelistframe.current

**Comment by hope366** [comment]
Thank you.
