### ISSUE TITLE
Error when start with set LeelaZero or SAI as default engine.

### ISSUE THREAD

**Issue by wonsiks** [yzyray/lizzieyzy#70]
Error logs here.

LeelaZero Human Trained 6blocks> name
LeelaZero Human Trained 6blocks> version
LeelaZero Human Trained 6blocks> list_commands
LeelaZero Human Trained 6blocks> komi 7.5
LeelaZero Human Trained 6blocks> boardsize 19
Using 8 thread(s).
RNG seed: 8136717454119429185
BLAS Core: built-in Eigen 3.3.90 library.
Detecting residual layers...v1...128 channels...6 blocks (Leela Zero).
Initializing CPU-only evaluation.
Setting max tree size to 13287 MiB and cache size to 1476 MiB.
 = Leela Zero
LeelaZero Human Trained 6blocks> kata-get-param playoutDoublingAdvantage
LeelaZero Human Trained 6blocks> kata-get-param analysisWideRootNoise
LeelaZero Human Trained 6blocks> kata-get-rules
 = 0.17
 = protocol_version
 name
 version
 quit
 known_command
 list_commands
 boardsize
 clear_board
 komi
 play
 genmove
 showboard
 undo
 final_score
 final_status_list
 time_settings
 time_left
 fixed_handicap
 last_move
 move_history
 place_free_handicap
 set_free_handicap
 loadsgf
 printsgf
 kgs-genmove_cleanup
 kgs-time_settings
 kgs-game_over
 heatmap
 lz-analyze
 lz-genmove_analyze
 lz-memory_report
 lz-setoption
 gomill-explain_last_move
 = 
 = 
 ? unknown command
 ? unknown command
 ? unknown command
LeelaZero Human Trained 6blocks> clear_board
LeelaZero Human Trained 6blocks> kata-time_settings byoyomi 600 5 3
 = 
LeelaZero Human Trained 6blocks> kata-analyze B 10
 ? unknown command
 ? unknown command

**Comment by yzyray** [comment]
It seems recgonized leela engine as katago engine.
I can not reproducd the issue,can you share your engine setting screenshot?
I set engine like this
![image](https://user-images.githubusercontent.com/49384584/147423892-dcf07451-02e9-4bda-b280-6033f02ca11d.png)but the log shows
![image](https://user-images.githubusercontent.com/49384584/147423905-6b00e7f0-dd3b-4a4a-83dd-6cc9bdb18ac0.png)

**Comment by wonsiks** [comment]
@yzyray My setting is same as yours.
And I've meant this error occurs in 2.4.7 branch.
It's okay in main branch. I guess there's some difference between two branches.
Thanks.

**Comment by hope366** [comment]
his problem also occurred in my environment. 
Just setting Leela Zero as the default did not cause an error, but when I closed Lizzieyzy and restarted it, it did not start normally. 
![無題](https://user-images.githubusercontent.com/63999713/147427665-08eb90e1-e5e2-44d8-ba75-a792dcc41694.png)
