### ISSUE TITLE
I can't search the game record of the sharing function 

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#71]
I have not been able to connect to the shared game search since a few days ago. Is there any good solution?
![share](https://user-images.githubusercontent.com/63999713/146667791-ee12e9ce-0b52-47a2-b4c7-eed8d611c2e8.png)

**Comment by hope366** [comment]
This issue only occurs in the Japanese translated version and is normal in the original English version.
I don't understand why the error occurs in the Japanese version. If you know how to solve the problem, please let me know.

**Comment by yzyray** [comment]
Does the issue happens in https://github.com/hope366/lizzieyzy/tree/jp-translate

**Comment by hope366** [comment]
Yes, that branch still gives an error because certain parts of the sharing feature are still in Japanese.
I've confirmed that switching back to English will fix the problem, but I'm hesitant to push until I ask you if there's a way to get rid of the error in Japanese.

**Comment by yzyray** [comment]
I have merged your code...but I can't reprodece the issue,can you try to reproduce it in branch 2.4.7?

**Comment by hope366** [comment]
![無題1](https://user-images.githubusercontent.com/63999713/147429586-72e5e689-3bda-482c-bec6-0bc7c0ffbfb2.png)

The problem occurs only in the part surrounded by the red frame. If this is Japanese, an error will occur, but "jp-translete" will not be an error because that part has been corrected to English.

**Comment by yzyray** [comment]
Should be fixe in 2.4.7 branch.
The item `PrivateKifuSearch.sql.blackScore` has symbol `(` in it,leads to sql search failed,I added `"` to cover the item and it is fine now.

**Comment by hope366** [comment]
2.4.7 I tested the branch. Even if the above red frame part was in Japanese, I was able to search without an error.
Thank you.
