### ISSUE TITLE
Graph drawing according to the length of the game record 

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#74]
This screenshot shows a game record with a total of 129 moves in Hawkeye. By default, 161 or later is set to the final stage, so you cannot visually check the final stage data. Of course, if you manually set the value of "the end of the middle stage" to 100 etc., the graph of the final stage will be displayed. 
How about building a system by default that displays the opening, early stage, middle stage, and final stage at a fixed rate according to the length of the game record, in order to save the trouble of setting the numerical values? 
![無題](https://user-images.githubusercontent.com/63999713/147040570-a5fdeaa7-5f4b-4ea7-9ad6-b5314738ae4f.png)

**Comment by yzyray** [comment]
If only a fixed rate according to the length of the game record,a game with 50 moves maybe will consider move 40-50 as end part,it is against common sense.
Katrain seems have a algorithm to decide which part is middle and which is end.But I dont know how to do it....

**Comment by hope366** [comment]
Yes, it's certainly against common sense. I think it's okay to have an empty game at the end of a short game. This topic is a story I heard from another person and is not my personal strong request, so I will close this issue.
