### ISSUE TITLE
set suggetion info Display Order

### ISSUE THREAD

**Issue by gokurou** [yzyray/lizzieyzy#76]
I want you to add set suggetion info display order to scorediff.

You will need to subtract and check the calculation or notification panel, so it would be helpful if you could add it.

![fureme](https://user-images.githubusercontent.com/96619325/147349118-73efa9bd-1cf2-4a17-bf7a-44e2d95f9abf.png)

**Comment by yzyray** [comment]
It is katrain style,I personal prefer current style show score directly.But I think I can add an option ScoreDiff in suggetion info display.

**Comment by gokurou** [comment]
Thank you very much. I appreciate it.
