### ISSUE TITLE
The display of winning percentage is reversed 

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#78]
The winning percentage numbers are reversed for the red and green frames. The information displayed in Lizzieyzy's comment panel seems to be due to the white information being displayed on the black turn and the black information being displayed on the white turn. Is it possible to change the display format of the comment panel to make it easier to see on the website? 
![無題](https://user-images.githubusercontent.com/63999713/147414323-377786d6-ad52-45d3-a970-118c35e91d46.png)

**Comment by yzyray** [comment]
It should be fixed now,the browser maybe need refresh the cache by ctrl+f5

**Comment by hope366** [comment]
Thank you. I just checked, "Ctrl + F5" solved the problem.
