### ISSUE TITLE
2.4.7 does not recognize the engine correctly at boot time 

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#79]
The 2.4.7 branch doesn't seem to recognize the engine correctly at boot time. The red frame indicates that. I suspect this is due to https://github.com/yzyray/lizzieyzy/commit/bad8d5d0e87c0869676755337c460eccd7edb389
Therefore, the "Parameter" button in the menu cannot be used. It seems that the engine is recognized correctly when switching to another engine. 
![無題1](https://user-images.githubusercontent.com/63999713/147430120-38b30e80-e788-4dfc-b0a1-aa41adfbe208.png)

**Comment by yzyray** [comment]
Does it fixed now?

**Comment by hope366** [comment]
Yes, the latest 2.4.7 did not have any issues.

**Comment by hope366** [comment]
Oh, my last remark was wrong.
The problem with #70 has been fixed, but the bug of not recognizing the engine correctly at startup has not been fixed yet.

**Comment by yzyray** [comment]
How can I reproduce this startup issue?

**Comment by hope366** [comment]
I tried the fix code.
The problem seems to be completely resolved.
Thank you.
