### ISSUE TITLE
Warning when using sync tool 

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#83]
When I start the sync tool, I get a warning that the version is old and should be updated.
It doesn't appear in 2.4.6.1, but it does occur in the latest master branch and the latest 2.4.7 branch.
Should I actually update it? If not, is it possible to avoid this warning?
Thank you. 
![無題](https://user-images.githubusercontent.com/63999713/147577067-6f660888-59f3-49ab-9585-6f7c2f23a4b9.png)

**Comment by yzyray** [comment]
I haven't upload the newest version `board sync tool` for 2.4.7 any where,just ignore it currently.
I will upload it along with 2.4.7 release.

**Comment by hope366** [comment]
thank you.
With that information, I think we can get rid of the confusion of some users who are wondering.

**Comment by wonsiks** [comment]
@hope366 You can edit the source file \src\main\java\featurecat\lizzie\analysis\ReadBoard.java line 36 to version 1108 if you don't want to see the warning message.

**Comment by hope366** [comment]
@wonsiks  Thank you for the information. I will try it immediately.

**Comment by hope366** [comment]
I changed the version number. No more warnings.
I thought you weren't a programmer, but you know a lot 😄
