### ISSUE TITLE
Some questions 

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#87]
Thank you for your vigorous efforts to improve this software. 
Here are some things that have been talked about as unclear points when creating the Lizzieyzy manual. 
* About "Play best candidate on end" of "View → Auto play". If you run it with the game record on the board (Analysis on), the movement of the game record will be played instead of the best move. 
* When Analyze → Estimate is executed, if there is a defect in the command, a window for notifying the error will be displayed. Even if I enter the correct command in this window and click "Apply", the window does not disappear. 
* In a human vs. AI game, if you specify Leela0110 as the engine and select genmove mode, Leela0110 will not try to play. 
* When I check "Gomoku" in Settings → Config, a Chinese dialog window appears and I'm not sure what that means. From my point of view, this is a setting for Gomoku or Renju, and if you enable this setting, it will not be excluded from the board even if you surround the stone. Is there any other effect? 

I'm sorry for all the details, but thank you.

**Comment by yzyray** [comment]
>About "Play best candidate on end" of "View → Auto play". If you run it with the game record on the board (Analysis on), the >movement of the game record will be played instead of the best move.
It is designed to play best move after movement of the game record is end,I will add an option to play best move directly.
>When Analyze → Estimate is executed, if there is a defect in the command, a window for notifying the error will be displayed. >Even if I enter the correct command in this window and click "Apply", the window does not disappear.
Yes the error dialog will not close automatically,but you can close it by hand.
>In a human vs. AI game, if you specify Leela0110 as the engine and select genmove mode, Leela0110 will not try to play.
This will be fixed soon
>When I check "Gomoku" in Settings → Config, a Chinese dialog window appears and I'm not sure what that means. From my >point of view, this is a setting for Gomoku or Renju, and if you enable this setting, it will not be excluded from the board even >if you surround the stone. Is there any other effect?
I forget to translate it,It means if you checked gomoku,game of go can not be analyzed

**Comment by hope366** [comment]
Thank you for your prompt response.
