### ISSUE TITLE
"Help" of synchronization tool does not work in Japanese version 

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#89]
With the language option set to default or Japanese using `ReadBoard.language = jp`, when I click" Help "in the sync tool, I get the error" readme_en.rtf not found ". This issue only occurs with the Board Synchronization Tool, not with the Board Synchronization Tool (simplified). 
![無題](https://user-images.githubusercontent.com/63999713/147785476-c13f66eb-ea85-419d-855d-3ff5a8089456.png)

**Comment by yzyray** [comment]
Does the file `readme_en.rtf` exsit in the folder `readboard`?

**Comment by hope366** [comment]
Yes, that's definitely it. This error does not occur except in default mode and Japanese mode. The contents of readme.trf are displayed in Chinese mode, and the contents of readme_en.rtf are displayed in English mode. This problem only occurs if the language is Japanese (also Korean ??).

**Comment by yzyray** [comment]
Can you upload your Japanese language file in `readboard` folder,it should be named as `language_jp.txt`

**Comment by hope366** [comment]
This is a download link for Japanese files. 
https://drive.google.com/file/d/1R3ERckFaXY-JXPkySQ1oMT8kqox8Ool5/view?usp=sharing

**Comment by yzyray** [comment]
helpFile=readme_en.rtfを参照してください。
This line right of `=` should be the same as the file name of help file in readboard folder like `readme_en.rtf` or `readme_cn.rtf` or create new file in Japanese language and named as `readme_jp.rtf`.`を参照してください。` this part need to be deleted.

**Comment by hope366** [comment]
Thanks to your proper advice, this problem could be solved easily.
Thank you very much 😄 
I'm trying to create a Japanese version of readme_jp.rtf using Libre Office, but I haven't used Office software so much and I'm having a hard time arranging images and characters neatly ...
