### ISSUE TITLE
About double engine mode 

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#9]
When I load a new engine on the new board on the right in DoubleEngine mode, it always looks like China Rules are being adopted. I usually use Japan Rules, so I was a little confused when different analysis results were displayed.
When I select Japan Rules from the toolbar, a few moments after turning on analysis, the values suitable for Japan Rules. Is it possible to change the non-Chinese rules to the easy-to-use specifications like the Chinese rules?
![無題](https://user-images.githubusercontent.com/63999713/139851699-85c5e94a-a5bf-4255-8ccd-542fdf296385.png)

**Comment by wonsiks** [comment]
Did you check the komi of subengine setting?
<img width="666" alt="20211102_224351" src="https://user-images.githubusercontent.com/37356450/139858981-ecf999d5-0403-46f4-9347-ee1f1e3b9824.png">

**Comment by hope366** [comment]
Yes, only a few KataGo engines are registered yet, but they all have komi set to 6.5.

**Comment by yzyray** [comment]
I've tested useing toolbar's button rules to change rule from chinese to japanese in double engine mode with 6.5 komi.
It works for both engines,but the second board with sub engine candidates does not show new candidates,need wait few seconds until new candidate's total visits bigger than previous.

**Comment by yzyray** [comment]
oh I misunderstand you means....you said can change sub engine rules.
How do your set the first engine to japanese rule?

**Comment by yzyray** [comment]
I can automaticly send first engine's rule to second.But if so,the two engins will always be the same rules,can not be used to compare difference bettwen rules

**Comment by hope366** [comment]
Thanks to your comments I realized my mistake. I usually change the rule to Japanese rule or change the number of threads to use in the config file when using katago, but it seems that I forgot to change to Japanese rule for lizzieyzy 2.4.5 is.
If you set "rules = japanese" in the configuration file, the second board will automatically become Japanese rules.
We apologize for the extra effort.
