### ISSUE TITLE
About the warning text when deleting stones 

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#90]
It seems that the warning text displayed when you press Delete or BackSpace in the middle of the game record does not support multilingual display. 
![無題](https://user-images.githubusercontent.com/63999713/147805744-0bdc30a2-a795-4f34-af85-f91d146791a2.png)

**Comment by wonsiks** [comment]
@yzyray You still need to change the code featurecat/lizzie/rules/Board.java line 2544 to fix this.
Thanks.
