### ISSUE TITLE
Please tell me how to contribute 

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#93]
We have compiled the latest Lizzieyzy 2.4.7 to contribute to distributed training.  https://katagotraining.org/
I created an account here. 
I started Lizzieyzy, went to the menu Contribute → KataGo training settings, and filled in the necessary items. Since there was no contribute_example, I borrowed it from the official KataGo release and filled in the username, password, etc. I get the error shown below. What's wrong? "contribute-config" This seems suspicious, but I don't know what to do. 
![1](https://user-images.githubusercontent.com/63999713/147824357-52c922ca-e423-4612-b11a-49b914cf990e.png)
![2](https://user-images.githubusercontent.com/63999713/147824368-ab921f5e-d2c1-45dc-8c6b-5bc50366de8b.png)
![3](https://user-images.githubusercontent.com/63999713/147824371-a53ead37-6245-45d8-8355-93462fd4fe80.png)

**Comment by yzyray** [comment]
I have not tested the contribute function completely,I always test it without config file path.
Obviously there is a bug,the command should be `contribute -config` instead of `contribute-config`,missed an blank.
It should be fixed now,but I haven't tested it too.  
By the way,the username,password and maxsimultaneousGames in config file will be override by interface.

**Comment by hope366** [comment]
I copied the command displayed as an error and replaced `contribute-config` with` contribute -config`. After using this command in a custom command, the model was downloaded and tuned. 
A 14x14 board was displayed on the main panel, and stones were placed on it, but I felt it was a little strange situation. 
The stones are placed in about 2 to 3 seconds, but KataGo did not try to place the stones after pondering when 5 to 6 stones were placed. .. Then all the stones disappeared from the board and started again from the beginning. This situation seemed to be looping.

**Comment by yzyray** [comment]
Does this happened every times and how many maxsimultaneousGames games
?

**Comment by hope366** [comment]
I haven't done a lot of experiments yet, but it doesn't seem to be the same every time.
The number of simultaneous games is set to "6". 
As one of the phenomena that occurs frequently, stones do not appear on the board for a while even though the contribution is started and the computer is heavily loaded.
Then, 10 to 20 seconds later, many stones suddenly appeared on the board. After a few steps, the stones were no longer placed (the computer is still under heavy load).
I often see things like the following error messages: 
![無題](https://user-images.githubusercontent.com/63999713/147848045-2c277dad-9008-46cb-ace7-d320d7952ea2.png)

**Comment by hope366** [comment]
In such a situation, the engine seems to be thinking for about 30 seconds. Then the situation returns to the previous state, where it seems to be thinking for a while.
I'm new to contributing, so I can't tell if this is in the normal range. However, there is no sign of moving forward forever, so I will give up and shut down Lizzieyzy ... 
![無題](https://user-images.githubusercontent.com/63999713/147848222-a613c314-1855-4433-9e2b-9c7c207ea328.png)

**Comment by yzyray** [comment]
If your GPU is not very fast,at the settings of 6 games,it it normal to wait a while to see next moves.I use 2 games to test or you can set only 1 game and see if next moves will appreared sooner.

**Comment by hope366** [comment]
The number of simultaneous games has been set to "1". I specified "1" in both the configuration file and the GUI.
The engine seems to be pondering a few seconds after starting the contribution, but no stones are placed on the board. After about 15 seconds, about 70 stones were placed at once. After that, it started to behave strangely again. After playing a bit normal around the 74th move, I suddenly warped to the 20th move. Then I immediately warped to the 74th move. After observing for a while, it seemed to repeat this all the time.

**Comment by yzyray** [comment]
![image](https://user-images.githubusercontent.com/49384584/147865225-5ee65080-45e4-432e-a6d6-90be18587032.png)
The `Auto Jump To Last` option will make the board jump to last move every time the GUI received a new move.Do you  selected it ?

**Comment by hope366** [comment]
No, I haven't checked it there. This strange phenomenon is not exactly the same every time, but it seems to have a similar tendency. After starting pondering and waiting for a while, suddenly many stones are placed. And after a little movement, it returns to the previous phase. Repeat this. This does not happen with KaTrain.

**Comment by yzyray** [comment]
Which code branch do you use,main or 2.4.7 or contribute?

**Comment by hope366** [comment]
I'm using "main". I downloaded and compiled the source code yesterday.

**Comment by yzyray** [comment]
I have seen this phenomenon,and I thought it have been solved.
Maybe I have messed up my code,you can test this first.
[lizzie-yzy2.4.7-shaded-0102test.zip](https://github.com/yzyray/lizzieyzy/files/7798752/lizzie-yzy2.4.7-shaded-0102test.zip)

**Comment by hope366** [comment]
lizzie-yzy2.4.7-shaded-0102test.zip
I tried this. There was no strange phenomenon that would bring us back to the previous phase. I set the number of simultaneous games to "1" and waited for a while with White passing at the end, but nothing seemed to happen. The GPU remained under heavy load. Is this a normal range of phenomena? 
![無題](https://user-images.githubusercontent.com/63999713/147870011-491c919c-f7f4-4067-830c-cf1836ee2f9d.png)

**Comment by hope366** [comment]
Next, I set the number of simultaneous games to "2" and verified. 
At the end of the first game, after Black passes, White keeps pondering and does nothing. After about 5 minutes, I gave up and stopped contributing. 
![無題2](https://user-images.githubusercontent.com/63999713/147871625-09c912ad-ce47-4674-90af-252fdf578619.png)

**Comment by hope366** [comment]
I specified the OpenCL version of KataGo in the settings screen, but it may actually be running the TensorRT version. After waiting about 3 minutes at the start, the trt cache was created in the KataGoData folder. 
After creating the cache file, a candidate appeared on the board, but after waiting for a while, the stone was not placed. The figure below shows the state when it is left for about 8 minutes. 
![無題](https://user-images.githubusercontent.com/63999713/147891728-22e6cdf2-be79-4537-910d-51820cb336b8.png)

**Comment by yzyray** [comment]
Sometimes it takes several minutes to finish a game after passed.I dont know the reason,but I'm pretty sure there is nothing you can do but wait the console shows the game is finished like the line `Finished game 1 (training), uploaded ....`

**Comment by yzyray** [comment]
I have fixed some bugs about contributing yesterday,can you try it with newest `main` branch code,the long waiting with candidates but no stone is placed phenomenon should be solved.

**Comment by hope366** [comment]
I tried it with the latest "main" that I downloaded 30 minutes ago. It seems that the phenomenon that stones are not placed on the board for a long time after the start of contemplation has been resolved. However, I am still wondering about the following two points. 
* The engine currently used in the GUI is used, ignoring the engine specified in the contribution settings. 
* When using the OpenCL version of the engine, the CPU usage will be around 50% and the fans will be noisy. It's unclear which engine KaTrain is using, but the CPU usage is around 25% and the fans aren't too noisy. 
* In the case of KaTrain, there is an interval of about 10 seconds after moving around 5 moves every second. There are few intervals longer than 10 seconds. In the case of Lizzieyzy, the interval length is often 30 seconds or longer.

**Comment by yzyray** [comment]
Can you give me your screenshot about contribut settings,like:
![image](https://user-images.githubusercontent.com/49384584/148016526-0acd4cc0-6533-43dd-b66c-01f16308e5df.png)

**Comment by yzyray** [comment]
When using KataGo engine  at contribute mode,engine does not allow any interactive through command.
All the difference between lizzieyzy and katrain,maybe due to different engine backend or simultaneous games or enable ownership or other settings before startup.
Another reason may be the lizzieyzy's GUI it self will use more cpu resources than katrain.

**Comment by hope366** [comment]
Since an error will occur if the executable file included with LIzzieyzy is used, the official executable file was specified. 
![無題](https://user-images.githubusercontent.com/63999713/148019246-7ce58819-6c3a-4551-99f8-024065643bf3.png)
The GTP console shows the name of the engine currently in use ... 
![無題1](https://user-images.githubusercontent.com/63999713/148019432-8decf8fc-77fd-4189-8531-43380b2c865e.png)

**Comment by yzyray** [comment]
Oh,I understand the misleading,GTP should show the contributing engine's name not the analyzeing engine..

**Comment by hope366** [comment]
I just downloaded and tried the latest main branch. About 20 seconds after I started contributing, only one stone was placed, but it disappeared in 10 seconds, and then nothing happened with a high load on the computer for more than 5 minutes ... 
![無題](https://user-images.githubusercontent.com/63999713/148022853-9a29e874-1c7f-49aa-9020-ca26dd8fc2cc.png)

**Comment by yzyray** [comment]
>only one stone was placed, but it disappeared in 10 seconds, and then nothing happened with a high load on the computer >for more than 5 minutes

Can you try the package I uploaded [here](https://aistudio.baidu.com/aistudio/datasetdetail/120771),If it will also happens.

**Comment by hope366** [comment]
[here](https://aistudio.baidu.com/aistudio/datasetdetail/120771) It takes a while to download this, so I compiled the main branch myself, but I'm downloading it now. The transfer speed is not constant, but it takes about 20-40 minutes to download. I will report the verification result later.

**Comment by yzyray** [comment]
If the package if fine,but compile from code have issues.Maybe I'm not familiar with merge different branch and messed up some codes....
By the way I saw a next move circle,in your previous screenshot.
![image](https://user-images.githubusercontent.com/49384584/148026451-e4d72fd8-d769-4ba3-bdbc-c553b750854c.png)
Does the move not exsit or can not goto next move?

**Comment by hope366** [comment]
It looks like a normal blue spot, not a next move circle.
About 20 seconds after starting the contribution, one black stone was added to the upper right, and after a while it disappeared, nothing was placed.

**Comment by yzyray** [comment]
How about changing games by click,will apprear any stones?
![image](https://user-images.githubusercontent.com/49384584/148028630-cd2abfc1-8490-4663-b776-54c83e0a2628.png)

**Comment by hope366** [comment]
[here](https://aistudio.baidu.com/aistudio/datasetdetail/120771) I'm currently verifying this, and it feels pretty good. Previous game ⇔ Next game, this is working fine.
In addition, the CPU usage rate has been around 25%, which is almost the same as the KaTrain value. It seems that the data completed on a regular basis is also uploaded.

**Comment by yzyray** [comment]
OK,then I have to do some test to verify if my local codes is the same as github main branch codes.

**Comment by yzyray** [comment]
I just download newest main branch code and complie,seems works fine on my environment,can you try it on your environment.
[lizzie-yzy-shaded-test0104.zip](https://github.com/yzyray/lizzieyzy/files/7806387/lizzie-yzy-shaded-test0104.zip)

**Comment by hope366** [comment]
katago-v1.10.0-opencl-windows-x64
It feels good to use it here. 
2021-11-17-windows64
Using the same jar file here seems to be a bit slower. 
Let's find out what's different.

**Comment by hope366** [comment]
This is the tuning file when I made a contribution in "2022-01-04-windows64 (test)". 
![無題](https://user-images.githubusercontent.com/63999713/148035923-41ca1fc1-e36d-458c-9283-03c7300cb4df.png)
And this is the tuning file when I made a contribution with the existing LIzzieyzy 2.4.6.1. 
![無題1](https://user-images.githubusercontent.com/63999713/148035939-37632ce9-c8e2-4bf0-83e8-fa8298404d0b.png)
I used the official KataGo-OpenCL-1.10.0, but is the KataGo-OpenCL included in "2022-01-04-windows64 (test)" different? 
Do these differences have anything to do with the difference in progress speed during contribution execution?

**Comment by hope366** [comment]
lizzie-yzy-shaded-test0104.zip
I put this in the Lizzieyzy-2.4.6.1 folder and verified it. KataGo
Is the officially distributed OpenCL version.
Within 10 seconds of starting the contribution, the mainboard should look like the screenshot below. After that, I left it for about an hour, but the main board hasn't changed at all since an hour ago. However, it seems that contribution work is being done internally and data uploads are also being performed. 
The console shows that 17 games have been completed in about an hour. 
![無題](https://user-images.githubusercontent.com/63999713/148052299-c2075f16-87bc-47de-ae22-97647d57ca12.png)

**Comment by hope366** [comment]
I finally figured out why the screen was stuck and stuck (probably) 
I think the reason why the screen was stuck was probably because the red frame in the screenshot below was not checked. By checking here, it will proceed smoothly. 
I'm sorry for making you feel annoyed because of my lack of attention. 
![無題](https://user-images.githubusercontent.com/63999713/148069868-7920714d-0e67-4697-8404-c219a7200192.png)

**Comment by yzyray** [comment]
Aha,that is the true reason,then the code on main branch is probably fine.
Thanks for patient testing~

**Comment by yzyray** [comment]
I'm plaining to release new version 2.4.7,do you have any plan to update Japenese translation for contribution?
By the way,can you make a pull request about Japenese translation of board sync tool,or you can just upload your language file and I can added it to repository.

**Comment by hope366** [comment]
I uploaded a Japanese file about the synchronization function. 
https://drive.google.com/file/d/18kpCb63gIkRybfgT4Fe6OHDgZFphSEb7/view?usp=sharing
I also compiled a version of readboard-1.5.6-shaded.jar that supports Japanese. Is it possible to use this? 
https://drive.google.com/file/d/1a6bLE26o664qb7KlP2p97Gdquhn2NQOg/view?usp=sharing

**Comment by yzyray** [comment]
Do you also have translated `readme_jp.rtf` or just a copy of `readme_en.rtf`?

**Comment by hope366** [comment]
Yes, I have created them as well. I just uploaded it. 
It is readme_jp.rtf. 
https://drive.google.com/file/d/18kpCb63gIkRybfgT4Fe6OHDgZFphSEb7/view?usp=sharing
It is help_jp.docx. 
https://drive.google.com/file/d/1XUyvmdHJ9NciIHWP80yEulmKITCtrSps/view?usp=sharing

**Comment by yzyray** [comment]
The first link seems like language_jp.txt

**Comment by hope366** [comment]
I'm sorry, I think I made a mistake. Is this okay? 
https://drive.google.com/file/d/13u1EYJ9Ut8ovatm07Zp7puo8X7jZDigu/view?usp=sharing

**Comment by yzyray** [comment]
> I'm sorry, I think I made a mistake. Is this okay? https://drive.google.com/file/d/13u1EYJ9Ut8ovatm07Zp7puo8X7jZDigu/view?usp=sharing

Yes,it works fine.thanks for all the detailed translation.

**Comment by hope366** [comment]
I also created a Japanese version of readme.pdf, but since I created it a while ago, the image is in English. It is troublesome to replace the image with the Japanese version, so it is undecided at the moment whether to create a new one. 
https://drive.google.com/file/d/1sImonJpaEMukxy_cp1SCWyqb-KiTIRhS/view?usp=sharing

**Comment by yzyray** [comment]
Chinese version readme.pdf is also a bit out of date,and the `introduction` menu does not support multilanguage yet.
I'll hold your translated readme until for a while until I make a new Chinese version readme and maybe an English one.

**Comment by hope366** [comment]
If you create a new readme.pdf, I would like to create a new Japanese version of readme.pdf accordingly.
