### ISSUE TITLE
The characters in the sync window are misaligned 

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#94]
If you use Japanese, the red frame will shift to the left and will not be displayed correctly. 
![sync](https://user-images.githubusercontent.com/63999713/147846100-3ed523fa-3d23-4a6c-b4db-7cbb627b4817.png)

**Comment by yzyray** [comment]
I have changed to use a new layout.
[readboard.zip](https://github.com/yzyray/lizzieyzy/files/7798754/readboard.zip)

**Comment by hope366** [comment]
I was able to confirm that it is displayed correctly 😄
Thank you. 
![無題1](https://user-images.githubusercontent.com/63999713/147870186-981ac943-d3f7-4ab8-913e-337b071d7dc0.png)
