### ISSUE TITLE
If you change the engine name, you will not be able to analyze it. 

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#95]
In the latest main branch, if you rename the engine and then click Save, you will not be able to run the analysis. It seems to return to normal by changing the engine name back or switching to another engine.
![無題](https://user-images.githubusercontent.com/63999713/148009186-7666451d-3654-4891-8328-cbabe53a2717.png)

**Comment by yzyray** [comment]
It should be fixed now,but if changed both name and engine order,it will load another engine.which is in the older order of previous using engine,dut to can not find same name engine.But I think it is fine,no misleading.

**Comment by hope366** [comment]
https://github.com/yzyray/lizzieyzy/commit/ceeb3db12ea02e5e607d6b8cfbcd93609a483cfb I applied this and confirmed that it would reload when I renamed it.
It was trivial and unnoticeable that another engine would load when I changed both the name and the order.
Thank you for fixing it.
